"""Editorial layouts for the three East Sicily city guides (Arnaud, 5 Oct 2026: "limit to 3 the places by
subcategory ... select the more authentic and interesting, always what they shouldn't miss; 4 when you really
can't decide"). Every group below holds at most 3 cards; a 4 is marked # 4: and says why.

Card refs: "PL:<title>" place card · "DN:" drink card · "SS:" street/sweet card · "SEA:<title>" sea card or story
· "GEM:<name>" a gem told as a card · "V:<venue id>" a pointer to the full table card.
Lanes: venue ids kept per table lane (the rest of that city's venues are cut from the guide and the CSV)."""

CITIES = {}

# ═══════════════════════════════ SIRACUSA + VAL DI NOTO ═══════════════════════════════
CITIES["siracusa"] = dict(
  slug="Siracusa-Sicilia", city="Siracusa", listeSlug="siracusa", country="Italy",
  title="Siracusa & the Val di Noto — Terroir Guide",
  desc="Siracusa for people who cook: Ortigia's market before nine, a Doric temple inside a cathedral, Greek tragedy in the rock at dusk, Corrado Assenza's almond granita in Noto and the cold-worked chocolate of Modica — every place checked in October 2026.",
  center=[36.98, 15.05], zoom=10, radiusKm=60,
  region="Ortigia · Val di Noto · Sicilia",
  berths=["duomo", "cortile-spirito-santo", "crocifisso"],
  lanes={
    "creme": ["duomo", "cortile-spirito-santo", "crocifisso"],
    "rising": ["dabbanna", "lorenzo-ruta"],
    "houses": ["latteria-mamma-iabica", "don-camillo", "regina-lucia", "radici"],  # 4: Regina Lucia is the verified last-minute table on Piazza Duomo
    "seafood": ["taverna-la-cialoma", "cortile-arabo", "campisi"],
    "cantine": ["cantine-pupillo", "cos", "arianna-occhipinti"],
    "pastry": ["caffe-sicilia", "antica-dolceria-bonajuto", "rosy-bar"],
    "cocktail": ["barcollo", "grand-hotel-ortigia", "enoteca-solaria"],   # one lane: the drink before dinner
    "street": ["caseificio-borderi", "fratelli-burgio"],
  },
  short={"Last minute — save the night": ["regina-lucia", "grand-hotel-ortigia", "don-camillo"],
         "Plan ahead — this week": ["cortile-spirito-santo", "crocifisso", "taverna-la-cialoma"],
         "Plan ahead — the grand night": ["duomo"]},
  folds=[
   # chapter, id, title, desc, lede, groups[(title, desc, [refs])]
   ("tables", "provisioning", "The larder — the market and three protected names",
    "Ortigia's market before nine, and the tomato, the almond and the tuna this corner of the island is known for",
    "Go to the market early, eat at it, and buy what the land here protects.",
    [("The market", "Before nine for the fish.", ["SS:Ortigia market"]),
     ("Three names worth knowing", "What the label means, and the one famous almond that has no label at all.",
      ["SS:Pomodoro di Pachino IGP", "SS:Mandorla di Noto (Slow Food presidium, not a DOP)", "SS:Marzamemi tuna: bottarga, ventresca, mosciame"])]),
   ("flaner", "teatro", "The Greek theatre at dusk",
    "Tragedy in the rock it was written for, every spring since 1914",
    "Siracusa is uniquely for one evening: an ancient play, in the ancient theatre, as the light goes. If you have one evening, do this one — a June performance, a seat high in the cavea, a cushion and water in the bag.",
    [("The theatre and the season", "", ["PL:Teatro Greco, Siracusa", "PL:INDA: Greek tragedy where it was first played"])]),
   ("flaner", "granita", "Almond, ice and cold chocolate",
    "Corrado Assenza's subtraction in Noto, Modica's cremolata and the chocolate that is never conched",
    "The south-east's sweet table is the most serious in Sicily. If you have one morning, do Caffè Sicilia in Noto at opening, then drive to Modica for the chocolate.",
    [("Why it is like this", "", ["GEM:Corrado Assenza's subtraction", "GEM:Cremolata, Modica's granita", "GEM:Chocolate without conching"]),
     ("Where", "The full cards sit in the lane «Granita, brioche & the pasticceria».", ["V:caffe-sicilia", "V:rosy-bar", "V:antica-dolceria-bonajuto"])]),
   ("flaner", "sea-stories", "The old sailors' harbour — true stories of this sea",
    "An Athenian fleet trapped, the claw of Archimedes, Nelson at the spring, and the village built round a tuna trap",
    "Every story is sourced, with the arguments left in. Each ends with what an old hand would want you to understand, and where you can still stand and see it.",
    [("War in the harbour", "Siracusa's two great sieges, and the admiral who watered at the spring.",
      ["SEA:The harbour that ate a fleet", "SEA:Archimedes' claw", "SEA:Watering at Arethusa"]),
     ("The tuna and the wreck", "A village built round a trap, and the Christmas wreck the state ignored.",
      ["SEA:Marzamemi: a village built around a tuna trap", "SEA:The Christmas wreck off Portopalo"]),
     ("The working sea", "", ["SEA:Ortigia: an island with two harbours"])]),
   ("flaner", "calas", "The sea — coves and the reserve", "A cove you can only walk to, a marine reserve at the harbour mouth, freshwater springs in the sea", "",
    [("Where to swim", "South to north.", ["PL:Vendicari and the Calamosche cove", "PL:Plemmirio marine reserve", "PL:Fontane Bianche"])]),
   ("flaner", "walks", "Walks", "Ortigia by the water, and a canyon of pools", "",
    [("On foot", "", ["PL:Ortigia by the water, a full loop", "PL:Cavagrande del Cassibile"])]),
   ("flaner", "landmarks", "The incontournables — read through the table",
    "A Doric temple inside a cathedral, the quarry the Athenians died in, a Caravaggio painted on the run, and a town rebuilt in one stone",
    "The big sights are not skipped; they are told for what they explain.",
    [("Ortigia", "Twenty-seven centuries on one island.",
      ["PL:Duomo di Siracusa: a temple still standing inside a church", "PL:Fonte Aretusa and its papyrus", "PL:The Miqwe of Via Alagona"]),
     ("The mainland", "Neapolis, the museum, and the saint's basilica in the Borgata.",
      ["PL:The Ear of Dionysius", "PL:Museo Archeologico Paolo Orsi", "PL:Caravaggio's Burial of Saint Lucy",
       "PL:Catacombe di San Giovanni"]),  # 4: the Caravaggio hangs in Santa Lucia al Sepolcro (back since 2021), over the catacomb — one visit
     ("The Val di Noto", "The towns that rose after 1693.", ["PL:Noto: a city moved and rebuilt", "PL:Palazzo Nicolaci and the Infiorata"])]),
   ("flaner", "small-wonders", "Squares and small wonders",
    "One piazza that holds a whole city, an architect's lizard, a spring that ran under the sea, and the tomb that isn't Archimedes'", "",
    [("The little beautiful things", "", ["PL:Piazza Duomo, Ortigia", "GEM:Vermexio's lizard", "GEM:Arethusa and Alpheus"]),
     ("Curiosities", "", ["PL:The greatest of the Greek cities", "PL:The tomb that isn't Archimedes'"])]),
   ("flaner", "culture", "Born here", "Archimedes, Quasimodo and Vittorini — and where to find their trace", "",
    [("Three lives", "Read one of the books before you go.", ["GEM:Archimedes", "GEM:Salvatore Quasimodo", "GEM:Elio Vittorini"])]),
   ("flaner", "craft", "Craftsmanship — where you can watch it made",
    "The puppeteers of Ortigia make every knight they fight with; the papyrus makers are the other craft, with what it is missing said plainly", "",
    [("Do this one", "", ["PL:Opera dei Pupi in Ortigia: the Vaccaro-Mauceri family"]),
     ("The other, and what it is missing", "", ["PL:Papyrus making in Siracusa"])]),
   ("around", "around", "Autour — the baroque towns, the gorge and the necropolis",
    "Noto Antica on its ridge, Pantalica's five thousand tombs and the town tucked into three valleys", "",
    [("Worth the drive", "Modica, Noto and Ragusa Ibla are under «The towns».", ["PL:Noto Antica", "PL:Pantalica", "PL:Scicli"])]),
   ("sortir", "vino", "The wines of the south-east — Moscato, Nero d'Avola and the clay of Vittoria",
    "The sweet white that nearly vanished, the clay amphorae of Vittoria and the cellars that open the door",
    "The south-east's own wines are an hour from Ortigia. Nothing is walk-in; book every cellar ahead.",
    [("How to read it", "", ["DN:Moscato of Siracusa and Noto: the oldest wine story in Italy", "DN:Vittoria: clay pots and Sicily's only DOCG"]),
     ("The cellars", "", ["V:cantine-pupillo", "V:cos", "V:arianna-occhipinti"])]),
   ("sortir", "bars", "Aperitivo, a rooftop and a thousand labels",
    "Siracusa's best cocktail bar, the grand hotel's terrace over the marina, and an enoteca that is eighty percent natural", "",
    [("Before dinner", "", ["V:barcollo", "V:grand-hotel-ortigia", "V:enoteca-solaria"])]),
   ("fast", "street-food", "Sur le pouce — the market counter", "Borderi's queue and the salumeria where you sit down", "",
    [("At the market", "", ["V:caseificio-borderi", "V:fratelli-burgio"])]),
   ("practical", "avoid", "Before you go", "The camera fines, the August canyon and the papyrus that is banana leaf", "",
    [("The warnings", "None of them is a reason not to come.", ["PL:Driving into Ortigia and Taormina", "PL:Cavagrande in August, and papyrus 'art' in Ortigia"])]),
   ("practical", "follow", "Follow", "The writers who explain this coast, and who to check before you go", "",
    [("Who knows", "", ["PL:Read before you go: Verga, Vittorini, Quasimodo, Brancati", "PL:Who to follow"])]),
   ("practical", "events", "The calendar", "Santa Lucia's procession, the film week in the courtyards and the puppets of San Martino", "",
    [("Through the year", "", ["PL:Festa di Santa Lucia, 13 December", "PL:Ortigia Film Festival", "PL:San Martino Puppet Fest, Siracusa"])]),
  ],
  sea_lede=True,
)

# ═══════════════════════════════ CATANIA + ETNA SOUTH ═══════════════════════════════
CITIES["catania"] = dict(
  slug="Catania-Sicilia", city="Catania", listeSlug="catania", country="Italy",
  title="Catania & Etna's south slope — Terroir Guide",
  desc="Catania for people who cook: the Pescheria shouting under the walls, granita and brioche at seven, the pointed arancino eaten standing, a city rebuilt in its own lava, and Etna's south slope from the cable car to the cellars of Milo — every place checked in October 2026.",
  center=[37.56, 15.08], zoom=10, radiusKm=45,
  region="Catania · Etna · Sicilia",
  berths=["sapio", "coria", "me-cumpari-turiddu"],
  lanes={
    "creme": ["sapio", "coria"],
    "rising": ["materia-spazio-cucina", "angio-macelleria-di-mare", "sabir"],
    "houses": ["me-cumpari-turiddu", "osteria-4-archi", "da-rinuccio"],
    "seafood": ["osteria-antica-marina", "faraglioni-restaurant", "nitto-ognina-bay-civico-8"],
    "cantine": ["benanti", "i-vigneri-di-salvo-foti"],
    "pastry": ["pasticceria-savia", "bar-alecci", "pasticceria-quaranta"],
    "cocktail": ["vermut", "nelson-sicily", "oliva-co-cocktail-society"],   # one lane: the Gemmellaro aperitivo and the late drink
    "late-night": ["monk-jazz-club", "chiosco-giammona"],
    "street": ["antica-friggitoria-stella", "scirocco-sicilian-fish-lab", "canusciuti"],
  },
  short={"Last minute — save the night": ["materia-spazio-cucina", "osteria-antica-marina", "sapio"],
         "Plan ahead — this week": ["me-cumpari-turiddu", "angio-macelleria-di-mare", "faraglioni-restaurant"],
         "Plan ahead — the grand night": ["coria"]},
  folds=[
   ("tables", "provisioning", "The larder — the fish market, the Monday fair and what the volcano grows",
    "The Pescheria's shouting, 'a Fera 'o Luni, the horse grills of Via Plebiscito, and the pistachio, the lemon and the blood orange",
    "Markets here are for looking and eating as much as buying. Both are mornings, Monday to Saturday; go early.",
    [("The markets", "", ["SS:La Pescheria, Catania", "SS:Fiera di Catania ('a Fera 'o Luni')", "SS:Via Plebiscito: arrusti e mancia"]),
     ("What the volcano grows", "Three protected names from Etna's soil.", ["SS:Pistacchio Verde di Bronte DOP", "SS:Limone dell'Etna IGP", "SS:Arancia Rossa di Sicilia IGP"])]),
   ("flaner", "granita", "Granita at seven — the morning ritual",
    "Almond ice and a warm brioche for breakfast, and the snow that used to come down from the volcano",
    "In Catania breakfast is a glass of granita and a brioche col tuppo, at a counter, all year. Order 'una granita di mandorla con la brioche' and never ask for it to go. If you have one morning, go to Savia on Via Etnea at opening.",
    [("Why it is like this", "", ["GEM:Granita is Arab sherbet plus Etna snow", "GEM:Brioche col tuppo"]),
     ("Where", "The full cards sit in the lane «Granita, brioche & the pasticceria».", ["V:pasticceria-savia", "V:bar-alecci", "V:pasticceria-quaranta"])]),
   ("flaner", "etna", "'A Muntagna — Etna from the south",
    "The cable car, the valley where the lava goes, the summit rules since August 2026 — and the day the lava reached Catania",
    "Sicilians on its slopes call it the Mountain and treat it as weather. Since 14 August 2026 hiking in the inner summit zone has been suspended except with licensed guides, and it erupted again on 24 September: read the observatory's bulletin before you plan.",
    [("Going up, honestly", "", ["PL:The summit rules, as of October 2026", "PL:Etna from the south: Rifugio Sapienza and the Funivia", "PL:Valle del Bove"]),
     ("The city and its volcano", "", ["PL:1669: when the lava reached Catania", "PL:The city built of its volcano", "GEM:Pappalardo's cut, 1669"])]),
   ("flaner", "sea-stories", "The Cyclops coast — true stories of this sea",
    "Verga's fishermen and the boat called Providence, the morning the harbour ran dry, and the fish market that still shouts", "",
    [("True stories", "", ["SEA:Aci Trezza: the Cyclops' rocks", "SEA:11 January 1693", "SEA:The working sea: 'a piscaria, Catania"])]),
   ("flaner", "landmarks", "The black city — read through the stone",
    "A lava elephant, two hundred metres of baroque convents, a monastery that is now a university and a castle the lava left inland", "",
    [("The centre", "", ["PL:Piazza Duomo, Catania and 'u Liotru", "PL:Via Crociferi", "PL:Monastero dei Benedettini"]),
     ("Small wonders", "Castello Ursino is closed for restoration until early 2027 (La Sicilia, May 2026), so it is not listed.", ["GEM:The nuns' bridge on Via Crociferi", "DN:A reading room in a Benedictine monastery"])]),
   ("flaner", "culture", "Born here", "Bellini and Verga — the opera house, the novel of the fishermen", "",
    [("Two lives", "", ["GEM:Vincenzo Bellini", "GEM:Giovanni Verga", "PL:Bellini's Catania"])]),
   ("flaner", "craft", "Craftsmanship — where you can watch it made",
    "The Napoli family's knights, the painted carts of Aci Sant'Antonio, Caltagirone's majolica and glazed lava", "",
    [("Do this one", "", ["PL:Marionettistica Fratelli Napoli, Catania"]),
     ("The others, and what each is missing", "", ["PL:Painted carts of Aci Sant'Antonio", "PL:Caltagirone: the ceramics town", "PL:Glazed lava stone"])]),
   ("flaner", "calas", "The sea — the Cyclops' rocks", "Basalt stacks said to be the boulders Polyphemus threw", "",
    [("Where to swim", "", ["PL:Aci Trezza and the Cyclops' rocks"])]),
   ("around", "around", "Autour — the honey town and the pistachio town",
    "Zafferana under the Valle del Bove, Bronte on its lava, and Acireale's carnival terrace", "",
    [("Worth the drive", "", ["PL:Zafferana Etnea", "PL:Bronte"])]),
   ("sortir", "vino", "Etna wine — the south and east slopes",
    "Sicily's mountain wine: a DOC since 1968, Carricante from Milo, and two cellars that open the door",
    "Etna wine is volcanic, high and recent in its fame. Nothing is walk-in: book every cellar ahead, and in October expect the winemaker to be in the vines.",
    [("How to read it", "", ["DN:Etna DOC: the volcano as a wine region", "DN:Reading a contrada on the label", "DN:Milo and the Bianco Superiore rule"]),
     ("The cellars", "", ["V:benanti", "V:i-vigneri-di-salvo-foti"])]),
   ("sortir", "bars", "Aperitivo, the night and the jazz club",
    "Via Gemmellaro's vermouth bar, two cocktail rooms down the steps, and the honest note on hi-fi", "",
    [("How the night works", "", ["DN:The Catania night: Gemmellaro to Montesano", "V:vermut", "V:oliva-co-cocktail-society"]),
     ("Music", "", ["V:monk-jazz-club", "DN:No listening bars yet"])]),
   ("fast", "street-food", "Sur le pouce — the counter and the kiosk",
    "The pointed arancino, the old fry shop, fish fried in the market and lemon-and-salt soda at the kiosk",
    "Catania is the street-food capital of this coast. Eat standing, pay at the till first.",
    [("Eat it standing", "", ["V:antica-friggitoria-stella", "V:scirocco-sicilian-fish-lab", "V:canusciuti"]),
     ("After midnight", "", ["V:chiosco-giammona"])]),
   ("practical", "avoid", "Before you go", "The summit tour that isn't", "",
    [("The warning", "", ["PL:Etna 'summit' tours sold from Taormina"])]),
   ("practical", "follow", "Follow", "The writers who explain this coast, and the observatory to check before you go", "",
    [("Who knows", "", ["PL:Read before you go: Verga, Vittorini, Quasimodo, Brancati", "PL:Who to follow"])]),
   ("practical", "events", "The calendar", "Sant'Agata's three days, and the October Sundays in Zafferana", "",
    [("Through the year", "", ["PL:Sant'Agata, 3-5 February", "PL:Ottobrata Zafferanese", "PL:Sagra del Pistacchio, Bronte"])]),
  ],
)

# ═══════════════════════════════ TAORMINA + ETNA NORTH ═══════════════════════════════
CITIES["taormina"] = dict(
  slug="Taormina-Sicilia", city="Taormina", listeSlug="taormina", country="Italy",
  title="Taormina & Etna's north slope — Terroir Guide",
  desc="Taormina for people who cook: the Greek-Roman theatre framing Etna, Lady Trevelyan's garden on the cliff, the swordfish boats of the strait, and the north slope's contrade cellars and Bib Gourmand trattorie between Linguaglossa and Randazzo — every place checked in October 2026.",
  center=[37.86, 15.15], zoom=10, radiusKm=45,
  region="Taormina · Etna nord · Sicilia",
  berths=["st-george-by-heinz-beck", "zash", "shalai"],
  lanes={
    "creme": ["st-george-by-heinz-beck", "la-capinera", "zash", "shalai"],  # 4: the two-star, the sea, the palmento and the north slope are four different evenings
    "rising": ["kiste", "vico-astemio", "casu-osteria-contemporanea"],   # Kisté verified 5 Oct: the last-minute table inside Taormina
    "houses": ["in-cucina-dai-pennisi", "san-giorgio-e-il-drago", "veneziano"],
    "seafood": ["a-putia"],
    "cantine": ["tenuta-delle-terre-nere", "graci", "frank-cornelissen"],
    "pastry": ["bam-bar", "pasticceria-gelateria-santo-musumeci", "antico-caffe-san-giorgio"],
    "cocktail": ["morgana", "casamatta"],
    "hotel-bar": ["bar-timeo", "bar-sant-andrea-and-gwendoline-s", "san-domenico-palace"],
  },
  short={"Last minute — save the night": ["kiste", "vico-astemio", "casu-osteria-contemporanea"],
         "Plan ahead — this week": ["la-capinera", "shalai", "zash"],
         "Plan ahead — the grand night": ["st-george-by-heinz-beck"]},
  folds=[
   ("flaner", "teatro", "The theatre that frames Etna",
    "Greek-founded, Roman-rebuilt, and laid out so the bay and the volcano are the backdrop",
    "Taormina is uniquely for one view, and the theatre is where it was composed. Go at opening, before the day visitors, or for a summer concert.",
    [("The theatre", "", ["PL:Teatro Antico, Taormina", "GEM:Goethe in Taormina"])]),
   ("flaner", "etna", "'A Muntagna — Etna from the north",
    "The quiet side: pine and birch woods, the 1614 lava under the vines, and the summit rules since August 2026",
    "The north side is the quieter way up. Since 14 August 2026 the inner summit zone is closed to walkers except with licensed guides; read the INGV bulletin first. If you have one day, drive up from Linguaglossa in the morning and take a cellar on the way down.",
    [("Going up, honestly", "", ["PL:The summit rules, as of October 2026", "PL:Etna from the north: Piano Provenzana", "GEM:Etna birch"])]),
   ("flaner", "sea-stories", "The strait — true stories of this sea",
    "What the Strait of Messina really does, the swordfish boats with a mast and a gangway, and the Russian sailors of 1908", "",
    [("True stories", "", ["SEA:Scylla, Charybdis and the rema", "SEA:The feluca", "GEM:The Russian sailors of Messina, 1908"])]),
   ("flaner", "calas", "The sea — Isola Bella", "A tiny island joined to the beach by a sandbar, bought by an English gardener", "",
    [("Where to swim", "", ["PL:Isola Bella"])]),
   ("flaner", "walks", "Walks", "The old stepped path up to the village on the rock", "",
    [("On foot", "", ["PL:Taormina to Castelmola on the old path"])]),
   ("flaner", "landmarks", "The incontournables — the street, the garden and the people who came",
    "One main street, Lady Trevelyan's follies on the cliff, a baron's photographs and Lawrence's snake", "",
    [("Taormina", "", ["PL:Corso Umberto, Taormina", "PL:Villa Comunale and Lady Florence Trevelyan"]),
     ("The visitors", "", ["PL:Wilhelm von Gloeden", "PL:D.H. Lawrence at Fontana Vecchia", "PL:The White Lotus effect"])]),
   ("around", "around", "Autour — the gorge, the Godfather's villages and the lava towns",
    "Basalt columns in a cold river, Michael Corleone's bar, a rock-top wine village and a town built of black lava", "",
    [("Worth the drive", "", ["PL:Gole dell'Alcantara", "PL:Savoca and Forza d'Agro", "PL:Castiglione di Sicilia",
                             "PL:Randazzo"])]),  # 4: Randazzo is the north slope's lava town and its two best trattorie
   ("sortir", "vino", "Etna wine — the north slope, the contrade, the cellar door",
    "Nerello on lava terraces between Castiglione and Randazzo, and the three cellars that open the door",
    "The north slope is where Etna wine was reborn. Nothing is walk-in; book every cellar ahead. If you have one afternoon, book a contrada tasting between Castiglione and Randazzo and drive back by Linguaglossa for dinner.",
    [("How to read it", "", ["DN:Reading a contrada on the label", "DN:How an Etna wine day works", "DN:The palmento: a winery made of stone and gravity"]),
     ("The cellars", "", ["V:tenuta-delle-terre-nere", "V:graci", "V:frank-cornelissen"])]),
   ("sortir", "bars", "One apéritif in a grand hotel, and the cocktail bar",
    "The terraces where Taormina's view was invented, and the bar redesigned every year", "",
    [("The terraces", "", ["V:bar-timeo", "V:bar-sant-andrea-and-gwendoline-s", "V:san-domenico-palace"]),
     ("The bars", "", ["V:morgana", "V:casamatta"])]),
   ("fast", "street-food", "Sur le pouce — granita and almond wine",
    "The granita queue on Via di Giovanni, the gelateria of the year in Randazzo and the almond wine of Castelmola", "",
    [("At the counter", "", ["V:bam-bar", "V:pasticceria-gelateria-santo-musumeci", "V:antico-caffe-san-giorgio"])]),
   ("practical", "avoid", "Before you go", "Corso Umberto at noon, the camera fines and the summit tour that isn't", "",
    [("The warnings", "", ["PL:Corso Umberto at midday, and Isola Bella sunbeds in August", "PL:Driving into Ortigia and Taormina", "PL:Etna 'summit' tours sold from Taormina"])]),
   ("practical", "follow", "Follow", "The writers who explain this coast, and who to check before you go", "",
    [("Who knows", "", ["PL:Read before you go: Verga, Vittorini, Quasimodo, Brancati", "PL:Who to follow"])]),
   ("practical", "events", "The calendar", "The Etna harvest and the week the cellars open their doors", "",
    [("Through the year", "", ["PL:Etna harvest, October", "DN:Le Contrade dell'Etna"])]),
  ],
)
