/* Terroir — Faro — auto-generated by publish-terroir.py */
window.PCV_DATA = (function () {
    const COLORS = { berth:'#c4a35a', market:'#d97706', shop:'#059669', mainland:'#7c3aed', logistics:'#2d4a5e' };
    const CAT_LABELS = { berth:'Signature', market:'Market / Direct', shop:'Restaurant / Bar', mainland:'Out of town', logistics:'Logistics' };
    const PRODUCT_COLORS = {
    'Michelin':'#7f1d1d','Contemporary':'#1f2937','Traditional':'#a16207',
    'Cult':'#7c3aed','Cafe':'#92400e','Wine':'#7c2d12','Bacaro':'#7c3aed',
    'Drink':'#0ea5e9','Street Food':'#dc2626','Market':'#d97706',
    'Produce':'#15803d','Fish':'#3b82f6','Meat':'#b91c1c',
    'Cheese':'#eab308','Bread':'#a16207','Charcuterie':'#9d174d',
    'Hi-Fi':'#1f2937'
};
    const VENUES = [
  {
    "id": "v01-alameda",
    "cat": "shop",
    "tier": "berth_top",
    "priority": 1,
    "badge": "MICHELIN",
    "name": "Alameda",
    "short": "Alameda",
    "lat": 37.01936,
    "lng": -7.9322,
    "tags": [
      "Michelin one star (awarded March 2026 — Faro's first ever)",
      "EUR 90-130 menu",
      "Essential",
      "Dinner"
    ],
    "productTags": [
      "Michelin",
      "Contemporary"
    ],
    "why": "Michelin one star (awarded March 2026 — Faro's first ever). À commander : the tasting menu — Origami (12 courses) or Umami (8 courses) — the kitchen reads the Ria, oyster with eucalyptus ponzu and lime, octopus from Olhão, smoked eel. Chef Rui Sequeira, ex-Ocean (Hans Neuner) and direct alumnus of the Vila Vita kitchen. The star reads as a line drawn under three decades of Algarve being only resort cooking. Thu–Mon dinner, Sunday lunch slots.",
    "address": "Rua da Polícia da Segurança Pública 10, 8000 Faro",
    "phone": "+351 289 824 831",
    "hours": "Dinner",
    "maps": "https://www.google.com/maps/search/?api=1&query=Alameda+Faro"
  },
  {
    "id": "v02-checkin-by-leonel-pereira",
    "cat": "shop",
    "tier": "berth_top",
    "priority": 2,
    "badge": "CONTEMPOR",
    "name": "CHECKin by Leonel Pereira",
    "short": "CHECKin by Leonel Pereir",
    "lat": 37.0146,
    "lng": -7.9354,
    "tags": [
      "Michelin Bib Gourmand (2025/2026)",
      "EUR 25-45",
      "Recommended",
      "Dinner"
    ],
    "productTags": [
      "Contemporary",
      "Michelin"
    ],
    "why": "Michelin Bib Gourmand (2025/2026). À commander : the seasonal menu — Check-in / Cozinhados no Tacho / Momentos Especiais / Check-out; ask the sommelier for niche Portuguese producers. Leonel Pereira held a star at São Gabriel (Almancil), gave it up to open a more democratic concept inside the walls. 26 seats indoors + 30-seat terrace. Wine list among the most curious in the city.",
    "address": "Rua do Castelo 7-13, 8000-243 Faro",
    "phone": "+351 968 070 776",
    "hours": "Dinner",
    "maps": "https://www.google.com/maps/search/?api=1&query=CHECKin+by+Leonel+Pereira+Faro"
  },
  {
    "id": "v03-estamin-ilha-deserta",
    "cat": "shop",
    "tier": "berth_top",
    "priority": 3,
    "badge": "CULT",
    "name": "Estaminé — Ilha Deserta",
    "short": "Estaminé — Ilha Deserta",
    "lat": 36.97022,
    "lng": -7.9242,
    "tags": [
      "The cult lunch of southern Portugal — solar-powered restaurant on an uninhabited barrier island",
      "EUR 25-50",
      "Essential",
      "Lunch"
    ],
    "productTags": [
      "Cult"
    ],
    "why": "The cult lunch of southern Portugal — solar-powered restaurant on an uninhabited barrier island. À commander : whatever the Ria gave that morning — oysters, grilled sea bream, conquilhas, arroz de lingueirão; the tuna and octopus estupetas. Animaris ferry from the marina (~30 min through the lagoon, return ~€10). Rebuilt August 2021 after a March fire. Photovoltaic plant covers all energy; seawater desalination for drinking water. First boat out, last boat back.",
    "address": "Ilha da Barreta — Animaris boat from Cais das Portas do Mar, Faro marina",
    "phone": "+351 917 811 856",
    "hours": "Lunch",
    "maps": "https://www.google.com/maps/search/?api=1&query=Estaminé+—+Ilha+Deserta+Faro"
  },
  {
    "id": "v04-tasca-do-ricky",
    "cat": "shop",
    "tier": "several",
    "priority": 4,
    "badge": "TRADITION",
    "name": "Tasca do Ricky",
    "short": "Tasca do Ricky",
    "lat": 37.0156,
    "lng": -7.9356,
    "tags": [
      "The canonical Faro tasca — organic ingredients, ancestral recipes, no more than four per table",
      "EUR 25-40",
      "Booking 19:00-19:45, walk-in until 21:30",
      "Dinner"
    ],
    "productTags": [
      "Traditional"
    ],
    "why": "The canonical Faro tasca — organic ingredients, ancestral recipes, no more than four per table. À commander : cataplana de marisco, arroz de lingueirão, amêijoas à bulhão pato, whatever's on the chalkboard. Mon–Sat 19:00–22:00; closed Sundays. The cataplana here is repeatedly cited as the best in the city. The waiter knows what you should order better than you do.",
    "address": "Rua do Forno 21, 8000-299 Faro",
    "phone": "",
    "hours": "Dinner",
    "maps": "https://www.google.com/maps/search/?api=1&query=Tasca+do+Ricky+Faro"
  },
  {
    "id": "v05-faz-gostos",
    "cat": "shop",
    "tier": "several",
    "priority": 5,
    "badge": "TRADITION",
    "name": "Faz Gostos",
    "short": "Faz Gostos",
    "lat": 37.0148,
    "lng": -7.9359,
    "tags": [
      "Michelin Plate — local gastronomic reference inside the walls",
      "EUR 20-40",
      "Recommended",
      "Dinner"
    ],
    "productTags": [
      "Traditional",
      "Wine"
    ],
    "why": "Michelin Plate — local gastronomic reference inside the walls. À commander : arroz de marisco (≈ €40 for two), cataplana, the day's fish. Established 2009. Two halls (up to 150 covers — unusually large for Michelin-listed but the consistency holds). 18th-c. underground wine cellar. Modern Algarve cooking that opens the Cidade Velha to serious eaters.",
    "address": "Rua do Castelo 13, 8000-243 Faro",
    "phone": "+351 914 133 668",
    "hours": "Dinner",
    "maps": "https://www.google.com/maps/search/?api=1&query=Faz+Gostos+Faro"
  },
  {
    "id": "v06-vila-adentro",
    "cat": "shop",
    "tier": "several",
    "priority": 6,
    "badge": "TRADITION",
    "name": "Vila Adentro",
    "short": "Vila Adentro",
    "lat": 37.0149,
    "lng": -7.9358,
    "tags": [
      "Azulejo-tiled 18th-c. building on the central walled square",
      "EUR 14-28",
      "Walk-in",
      "All day"
    ],
    "productTags": [
      "Traditional"
    ],
    "why": "Azulejo-tiled 18th-c. building on the central walled square. À commander : vegetable cataplana (proof the copper pot works without shellfish), octopus, prawn-curry rice. Open 10:00–22:30 daily — one of the rare all-day options inside the walls. Vegan-friendly without being only that.",
    "address": "Praça Dom Afonso III 17, 8000-167 Faro",
    "phone": "+351 289 052 173",
    "hours": "All day",
    "maps": "https://www.google.com/maps/search/?api=1&query=Vila+Adentro+Faro"
  },
  {
    "id": "v07-tert-lia-algarvia",
    "cat": "shop",
    "tier": "several",
    "priority": 7,
    "badge": "TRADITION",
    "name": "Tertúlia Algarvia",
    "short": "Tertúlia Algarvia",
    "lat": 37.0156,
    "lng": -7.9352,
    "tags": [
      "Traditional Algarve dishes plus cooking classes — the place to learn cataplana technique",
      "EUR 15-30",
      "Walk-in",
      "Lunch / Dinner"
    ],
    "productTags": [
      "Traditional"
    ],
    "why": "Traditional Algarve dishes plus cooking classes — the place to learn cataplana technique. À commander : seasonal menu tied to what the land and sea give that week; sign up for the class. Regional-products focus. The cooking class makes it more useful than another menu.",
    "address": "Praça Afonso III 13, 8000-167 Faro",
    "phone": "",
    "hours": "Lunch / Dinner",
    "maps": "https://www.google.com/maps/search/?api=1&query=Tertúlia+Algarvia+Faro"
  },
  {
    "id": "v08-adega-nova",
    "cat": "shop",
    "tier": "several",
    "priority": 8,
    "badge": "TRADITION",
    "name": "Adega Nova",
    "short": "Adega Nova",
    "lat": 37.017,
    "lng": -7.934,
    "tags": [
      "Converted tile-and-brick warehouse, open 11:00–23:00 daily, an extensive Dão / Douro list",
      "EUR 10-18",
      "Walk-in",
      "Lunch / Dinner"
    ],
    "productTags": [
      "Traditional",
      "Wine"
    ],
    "why": "Converted tile-and-brick warehouse, open 11:00–23:00 daily, an extensive Dão / Douro list. À commander : grilled fish, arroz de marisco, choco frito; two with a bottle around €40. Since 1986. The value benchmark of central Faro — honest portions, real fish, real wine.",
    "address": "Rua Francisco Barreto 24, 8000-034 Faro",
    "phone": "+351 289 813 433",
    "hours": "Lunch / Dinner",
    "maps": "https://www.google.com/maps/search/?api=1&query=Adega+Nova+Faro"
  },
  {
    "id": "v09-a-venda",
    "cat": "shop",
    "tier": "several",
    "priority": 9,
    "badge": "TRADITION",
    "name": "A Venda",
    "short": "A Venda",
    "lat": 37.0166,
    "lng": -7.9348,
    "tags": [
      "Petiscos in a grandmother's lounge — open kitchen, sharing plates",
      "EUR 15-25 sharing",
      "Recommended",
      "Dinner"
    ],
    "productTags": [
      "Traditional"
    ],
    "why": "Petiscos in a grandmother's lounge — open kitchen, sharing plates. À commander : pork cheeks, marinated vegetables, local cheese board, anything off the daily list. Tue–Sat 13:00-15:00 and 19:30-23:00. Vegan-, vegetarian- and meat-eater-friendly without forcing the joke.",
    "address": "Rua do Compromisso 60, 8000-252 Faro",
    "phone": "",
    "hours": "Dinner",
    "maps": "https://www.google.com/maps/search/?api=1&query=A+Venda+Faro"
  },
  {
    "id": "v10-a-do-pinto",
    "cat": "shop",
    "tier": "several",
    "priority": 10,
    "badge": "TRADITION",
    "name": "A Do Pinto",
    "short": "A Do Pinto",
    "lat": 37.0178,
    "lng": -7.9337,
    "tags": [
      "Family-run cataplana house, honest portions",
      "EUR 15-30",
      "Walk-in",
      "Lunch / Dinner"
    ],
    "productTags": [
      "Traditional"
    ],
    "why": "Family-run cataplana house, honest portions. À commander : cataplana with shrimp and clams, grilled fish. Word-of-mouth Faro address. Not for tourists — which is exactly why you go.",
    "address": "Faro Centro",
    "phone": "",
    "hours": "Lunch / Dinner",
    "maps": "https://www.google.com/maps/search/?api=1&query=A+Do+Pinto+Faro"
  },
  {
    "id": "v11-mercado-de-olh-o",
    "cat": "market",
    "tier": "plenty",
    "priority": 11,
    "badge": "MARKET",
    "name": "Mercado de Olhão",
    "short": "Mercado de Olhão",
    "lat": 37.0282,
    "lng": -7.8425,
    "tags": [
      "Two red-brick halls on the waterfront — the Algarve's largest fish market",
      "EUR variable",
      "Walk-in",
      "Mon–Sat 07:00-13:00"
    ],
    "productTags": [
      "Market",
      "Produce"
    ],
    "why": "Two red-brick halls on the waterfront — the Algarve's largest fish market. À commander : Saturday before 09:00: sardines (~€4/kg) off the boats, octopus, Pacific oysters, amêijoa-boa, Ria Formosa salt and flor de sal. Built 1912–1916, inaugurated 1916. Two halls — east is fish, west is fruit/vegetables. Neo-Arabic green domes, 20th-c. azulejo panels of Algarve fishing life inside. Saturday is the experience.",
    "address": "Av. 5 de Outubro, 8700-307 Olhão",
    "phone": "",
    "hours": "Mon–Sat 07:00-13:00",
    "maps": "https://www.google.com/maps/search/?api=1&query=Mercado+de+Olhão+Faro"
  },
  {
    "id": "v12-mercado-municipal-de-faro",
    "cat": "market",
    "tier": "plenty",
    "priority": 12,
    "badge": "MARKET",
    "name": "Mercado Municipal de Faro",
    "short": "Mercado Municipal de Far",
    "lat": 37.0193,
    "lng": -7.9302,
    "tags": [
      "Faro's city market — fish, vegetables, the city's reference bifana inside",
      "EUR variable",
      "Walk-in",
      "Mon–Sat morning"
    ],
    "productTags": [
      "Market"
    ],
    "why": "Faro's city market — fish, vegetables, the city's reference bifana inside. À commander : bifana from Snack Bar da Xica; daily fish; fruit and bread. Less theatre than Olhão; more utility. Go early. Snack Bar da Xica's bifana is repeatedly cited as the city's best.",
    "address": "Largo Dr. Francisco Sá Carneiro, 8000 Faro",
    "phone": "",
    "hours": "Mon–Sat morning",
    "maps": "https://www.google.com/maps/search/?api=1&query=Mercado+Municipal+de+Faro+Faro"
  },
  {
    "id": "v13-bago-wine-bar",
    "cat": "shop",
    "tier": "several",
    "priority": 13,
    "badge": "DRINK",
    "name": "Bago Wine Bar",
    "short": "Bago Wine Bar",
    "lat": 37.0175,
    "lng": -7.9345,
    "tags": [
      "Faro's natural-wine reference — ~180 Portuguese references, 30–50 natural / organic / biodynamic",
      "EUR 5-12 glass · EUR 8-18 food",
      "Walk-in",
      "Evening"
    ],
    "productTags": [
      "Wine",
      "Bacaro"
    ],
    "why": "Faro's natural-wine reference — ~180 Portuguese references, 30–50 natural / organic / biodynamic. À commander : by-the-glass tour of the Algarve list; tiborna open-toasts, cheese, charcuterie, fish tapas, roast black-pork sausage. 10:00-23:00, closed Sun–Mon. Live music most Fridays from 19:30. Raisin-listed.",
    "address": "Rua José Maria Brandeiro 10, 8000-382 Faro",
    "phone": "",
    "hours": "Evening",
    "maps": "https://www.google.com/maps/search/?api=1&query=Bago+Wine+Bar+Faro"
  },
  {
    "id": "v14-hotel-faro-rooftop",
    "cat": "shop",
    "tier": "plenty",
    "priority": 14,
    "badge": "DRINK",
    "name": "Hotel Faro Rooftop",
    "short": "Hotel Faro Rooftop",
    "lat": 37.0166,
    "lng": -7.9319,
    "tags": [
      "The best rooftop view in the city — harbour, Ria Formosa, the barrier islands",
      "EUR 8-15 / drink",
      "Walk-in",
      "Sunset"
    ],
    "productTags": [
      "Drink"
    ],
    "why": "The best rooftop view in the city — harbour, Ria Formosa, the barrier islands. À commander : anything cold at sunset. Touristy but the view actually pays. Go at sunset, leave before the music.",
    "address": "Praça D. Francisco Gomes 2, 8000 Faro",
    "phone": "",
    "hours": "Sunset",
    "maps": "https://www.google.com/maps/search/?api=1&query=Hotel+Faro+Rooftop+Faro"
  },
  {
    "id": "v15-morgado-do-quint-o",
    "cat": "shop",
    "tier": "plenty",
    "priority": 15,
    "badge": "CULT",
    "name": "Morgado do Quintão",
    "short": "Morgado do Quintão",
    "lat": 37.1583,
    "lng": -8.4083,
    "tags": [
      "Family-owned since 1810; Algarve's largest certified-organic vineyard; consultant Joana Maçanita",
      "EUR 20-40 tasting",
      "Book ahead",
      "Afternoon"
    ],
    "productTags": [
      "Wine",
      "Cult"
    ],
    "why": "Family-owned since 1810; Algarve's largest certified-organic vineyard; consultant Joana Maçanita. À commander : monovarietal Crato Branco (the canonical Algarve white); Negra Mole rosé under the 2,000-year-old olive tree; farmers' table lunch pairing family recipes with the wines. Mon–Sat 16:00 visit slots. Won \"Best Wine in Portugal – Algarve\" (Revista de Vinhos) two years running. Farmstay on the estate.",
    "address": "Estrada das Relíquias, between Silves and Lagoa",
    "phone": "",
    "hours": "Afternoon",
    "maps": "https://www.google.com/maps/search/?api=1&query=Morgado+do+Quintão+Faro"
  },
  {
    "id": "v16-vila-joya",
    "cat": "shop",
    "tier": "plenty",
    "priority": 16,
    "badge": "MICHELIN",
    "name": "Vila Joya",
    "short": "Vila Joya",
    "lat": 37.0884,
    "lng": -8.2825,
    "tags": [
      "Michelin two stars — held since 1999, the longest-running ★★ on the Algarve coast",
      "EUR 200+ menu",
      "Essential",
      "Dinner"
    ],
    "productTags": [
      "Michelin"
    ],
    "why": "Michelin two stars — held since 1999, the longest-running ★★ on the Algarve coast. À commander : the daily-changing tasting; no dish appears twice across the year. Austrian chef Dieter Koschina, in the Algarve since 1991; first star 1995, second 1999 — the first ★★ in Portugal. 30 seats. Cliffside Atlantic terrace.",
    "address": "Estrada da Galé, Praia da Galé, 8201-902 Albufeira",
    "phone": "+351 289 591 839",
    "hours": "Dinner",
    "maps": "https://www.google.com/maps/search/?api=1&query=Vila+Joya+Faro"
  },
  {
    "id": "v17-ocean-restaurant",
    "cat": "shop",
    "tier": "plenty",
    "priority": 17,
    "badge": "MICHELIN",
    "name": "Ocean Restaurant",
    "short": "Ocean Restaurant",
    "lat": 37.093,
    "lng": -8.4019,
    "tags": [
      "Michelin two stars since 2011; Best Service Award 2026",
      "EUR 200+ menu",
      "Essential",
      "Dinner"
    ],
    "productTags": [
      "Michelin"
    ],
    "why": "Michelin two stars since 2011; Best Service Award 2026. À commander : the discovery menu — Atlantic fish read through Portugal's Age of Discovery routes. Chef Hans Neuner (Portugal's Chef of the Year 2009 and 2012). Rui Sequeira of Alameda passed through this kitchen — the lineage is direct.",
    "address": "Vila Vita Parc, Alporchinhos, 8400-450 Porches",
    "phone": "+351 282 310 100",
    "hours": "Dinner",
    "maps": "https://www.google.com/maps/search/?api=1&query=Ocean+Restaurant+Faro"
  },
  {
    "id": "v18-bon-bon",
    "cat": "shop",
    "tier": "plenty",
    "priority": 18,
    "badge": "MICHELIN",
    "name": "Bon Bon",
    "short": "Bon Bon",
    "lat": 37.1018,
    "lng": -8.4731,
    "tags": [
      "Michelin one star (held)",
      "EUR 120-160 menu",
      "Essential",
      "Dinner"
    ],
    "productTags": [
      "Michelin"
    ],
    "why": "Michelin one star (held). À commander : the Essence menu — a tightly edited celebration of Algarve biodiversity. Chef José Lopes (succeeding Louis Anjos in the 2026 guide). Less resort, more personal vision than Vila Joya or Ocean.",
    "address": "Sesmarias, 8400-525 Carvoeiro",
    "phone": "+351 282 341 496",
    "hours": "Dinner",
    "maps": "https://www.google.com/maps/search/?api=1&query=Bon+Bon+Faro"
  }
];
    const NEIGHBORHOODS = [
  {
    "id": "n-cidade-velha",
    "name": "Cidade Velha (intra-muros)",
    "center": [
      37.0145,
      -7.9358
    ],
    "radius": 200,
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Cidade+Velha+Faro"
  },
  {
    "id": "n-faro-centro",
    "name": "Faro Centro & Rua de Santo António",
    "center": [
      37.0175,
      -7.935
    ],
    "radius": 380,
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Faro+Centro"
  },
  {
    "id": "n-marina",
    "name": "Marina & Jardim Manuel Bívar",
    "center": [
      37.0166,
      -7.9319
    ],
    "radius": 250,
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Marina+de+Faro"
  },
  {
    "id": "n-mercado-faro",
    "name": "Mercado Municipal",
    "center": [
      37.0193,
      -7.9302
    ],
    "radius": 130,
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Mercado+Municipal+Faro"
  },
  {
    "id": "n-praia-faro",
    "name": "Praia de Faro / Ilha",
    "center": [
      36.9961,
      -7.9929
    ],
    "radius": 600,
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Praia+de+Faro"
  },
  {
    "id": "n-olhao",
    "name": "Olhão",
    "center": [
      37.0282,
      -7.8425
    ],
    "radius": 700,
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Olhao+waterfront"
  },
  {
    "id": "n-out-of-town",
    "name": "Out of town — Tavira / Estói / Loulé / Lagoa",
    "center": [
      37.1,
      -7.8
    ],
    "radius": 1500,
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Tavira+old+town"
  }
];
    const WALKS = [
  {
    "id": "p-walk-cidade-velha",
    "name": "The Cidade Velha walls",
    "start": [
      37.0143,
      -7.9359
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Cidade+Velha+Faro"
  },
  {
    "id": "p-walk-ilha-deserta",
    "name": "Ilha Deserta day trip",
    "start": [
      37.0136,
      -7.9333
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Ilha+Deserta+ferry+Faro"
  },
  {
    "id": "p-walk-ludo-trail",
    "name": "The Ludo Trail",
    "start": [
      37.0143,
      -7.955
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Ludo+Trail+Faro"
  },
  {
    "id": "p-walk-olhao",
    "name": "Olhão — fishing port + 1916 market",
    "start": [
      37.0282,
      -7.8425
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Olhao+market"
  },
  {
    "id": "p-walk-tavira",
    "name": "Tavira — the eastern Algarve's elegance",
    "start": [
      37.1262,
      -7.6498
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Tavira+old+town"
  },
  {
    "id": "p-walk-cabo-sao-vicente",
    "name": "Cabo de São Vicente",
    "start": [
      37.0234,
      -8.9947
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Cabo+de+Sao+Vicente"
  }
];
    const WORK_SPOTS = [
  {
    "id": "p-work-jardim-manuel-bivar",
    "name": "Jardim Manuel Bívar",
    "start": [
      37.0162,
      -7.9347
    ]
  },
  {
    "id": "p-work-cafe-alianca",
    "name": "Café Aliança",
    "start": [
      37.0163,
      -7.9335
    ]
  },
  {
    "id": "p-work-pastelaria-gardy",
    "name": "Pastelaria Gardy",
    "start": [
      37.017,
      -7.9342
    ]
  },
  {
    "id": "p-work-biblioteca",
    "name": "Biblioteca Municipal A. Ramos Rosa",
    "start": [
      37.0192,
      -7.9325
    ]
  },
  {
    "id": "p-work-marina",
    "name": "Marina de Faro",
    "start": [
      37.0166,
      -7.9319
    ]
  }
];
    const LANDMARKS = [
  {
    "id": "l-se-faro",
    "name": "Sé (Faro Cathedral)",
    "coords": [
      37.0143,
      -7.9359
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Sé+de+Faro"
  },
  {
    "id": "l-arco-da-vila",
    "name": "Arco da Vila",
    "coords": [
      37.0156,
      -7.9362
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Arco+da+Vila+Faro"
  },
  {
    "id": "l-ria-formosa",
    "name": "Ria Formosa Natural Park",
    "coords": [
      37.005,
      -7.88
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Ria+Formosa+Natural+Park"
  },
  {
    "id": "l-ilha-deserta",
    "name": "Ilha Deserta",
    "coords": [
      36.97022,
      -7.9242
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Ilha+Deserta+Faro"
  },
  {
    "id": "l-capela-ossos",
    "name": "Capela dos Ossos (Igreja do Carmo)",
    "coords": [
      37.0191,
      -7.9318
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Capela+dos+Ossos+Faro"
  },
  {
    "id": "l-teatro-lethes",
    "name": "Teatro Lethes",
    "coords": [
      37.0165,
      -7.934
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Teatro+Lethes+Faro"
  },
  {
    "id": "l-tavira",
    "name": "Tavira (old town)",
    "coords": [
      37.1262,
      -7.6498
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Tavira+old+town"
  }
];
    return { VENUES, COLORS, CAT_LABELS, PRODUCT_COLORS, NEIGHBORHOODS, WALKS, WORK_SPOTS, LANDMARKS };
})();
