/* ============================================================================
   LITTORALICIOUS — Galley Order · Produce extension
   Adds the Produce category to PANTRY_DATA. Loaded AFTER data.js.
   Quality bias: ★ organic / certified, ★★ heirloom / single-origin / AOP,
   ★★★ luxury / hero (Amalfi lemons, Bronte pistachios fresh, Padrón etc.).
   ============================================================================ */
(function () {
  if (!window.PANTRY_DATA) {
    console.warn("PANTRY_DATA missing — produce extension cannot load.");
    return;
  }
  const cat = {
    id: "produce",
    label: "Produce · Veg & Fruit",
    sections: [
      {
        title: "Leafy Greens",
        items: [
          { name: "Baby spinach — organic", brand: "Bio · loose-leaf bag", tier: 1, unit: "kg" },
          { name: "Wild rocket / arugula (organic)", brand: "Sharp peppery · Italian preferred", tier: 1, unit: "kg" },
          { name: "Watercress — Le Cresson (organic)", brand: "Fresh-cut bunch · French / English", tier: 2, unit: "bunch" },
          { name: "Butter lettuce / Bibb (organic)", brand: "Heads with root attached", tier: 1, unit: "heads" },
          { name: "Little Gem / Baby Gem (organic)", brand: "Salad heart · whole heads", tier: 2, unit: "heads" },
          { name: "Romaine (organic)", brand: "Whole heads", tier: 1, unit: "heads" },
          { name: "Frisée (curly endive)", brand: "Pale yellow center · French", tier: 2, unit: "heads" },
          { name: "Mâche / lamb's lettuce", brand: "French · delicate small leaf", tier: 2, unit: "bag" },
          { name: "Radicchio di Treviso (in season)", brand: "Late Dec–Feb · IGP", tier: 3, unit: "heads" },
          { name: "Radicchio di Chioggia", brand: "Round red Italian", tier: 2, unit: "heads" },
          { name: "Endive — Belgian (chicon)", brand: "Pale yellow tight head", tier: 1, unit: "heads" },
          { name: "Castelfranco (variegated radicchio)", brand: "Cream-and-pink rosette", tier: 3, unit: "heads" },
          { name: "Swiss chard rainbow", brand: "Bunch · stems yellow/red/pink", tier: 2, unit: "bunch" },
          { name: "Tuscan / lacinato kale (cavolo nero)", brand: "Dark dimpled leaves", tier: 2, unit: "bunch" },
          { name: "Curly kale (organic)", brand: "Bunch · frilled", tier: 1, unit: "bunch" },
          { name: "Mustard greens — Asian", brand: "Spicy · gai choy / mizuna", tier: 2, unit: "bunch" },
          { name: "Dandelion greens", brand: "Wild or cultivated · spring", tier: 2, unit: "bunch" },
          { name: "Pea shoots / pea tendrils", brand: "Fresh sweet · for plating", tier: 2, unit: "pack" },
          { name: "Mixed baby leaves (mesclun)", brand: "Organic Provence mix preferred", tier: 1, unit: "kg" },
        ],
      },
      {
        title: "Brassicas",
        items: [
          { name: "Broccoli (organic)", brand: "Long-stem or crown", tier: 1, unit: "kg" },
          { name: "Broccolini / sprouting broccoli", brand: "Tender stems", tier: 2, unit: "bunch" },
          { name: "Cauliflower — white (organic)", brand: "Heads · trimmed", tier: 1, unit: "heads" },
          { name: "Cauliflower — Romanesco", brand: "Fractal green · Italian heirloom", tier: 2, unit: "heads" },
          { name: "Purple cauliflower", brand: "Heirloom · firm purple", tier: 2, unit: "heads" },
          { name: "Brussels sprouts — on the stalk", brand: "Whole stalk · winter peak", tier: 2, unit: "stalks" },
          { name: "Cabbage Savoy", brand: "Crinkled leaves", tier: 1, unit: "heads" },
          { name: "Cabbage red / Napa / pointed", brand: "By variety", tier: 1, unit: "heads" },
          { name: "Kohlrabi", brand: "Green or purple · whole with leaves", tier: 2, unit: "pcs" },
          { name: "Bok choy / pak choy", brand: "Baby or full · Asian fresh", tier: 1, unit: "kg" },
          { name: "Choy sum / yu choy", brand: "Asian fresh", tier: 1, unit: "kg" },
        ],
      },
      {
        title: "Roots & Tubers",
        items: [
          { name: "Carrots — heirloom rainbow (organic)", brand: "Berchères or local farm · with tops", tier: 2, unit: "kg" },
          { name: "Carrots — orange (organic)", brand: "With tops", tier: 1, unit: "kg" },
          { name: "Carrots — baby", brand: "Bunches with tops", tier: 2, unit: "bunch" },
          { name: "Parsnips (organic)", brand: "Whole · root vegetables", tier: 1, unit: "kg" },
          { name: "Beetroot — chioggia (candy-stripe)", brand: "Heirloom · raw service", tier: 2, unit: "kg" },
          { name: "Beetroot — golden", brand: "Heirloom · yellow flesh", tier: 2, unit: "kg" },
          { name: "Beetroot — red (organic)", brand: "With tops", tier: 1, unit: "kg" },
          { name: "Turnips — baby Tokyo", brand: "Small white sweet · raw", tier: 2, unit: "bunch" },
          { name: "Turnips — purple top (organic)", brand: "Cooking turnip", tier: 1, unit: "kg" },
          { name: "Celeriac (organic)", brand: "Whole knob", tier: 1, unit: "kg" },
          { name: "Salsify (scorzonera)", brand: "Black-skinned root", tier: 2, unit: "kg" },
          { name: "Daikon", brand: "Long white radish · Asian", tier: 1, unit: "kg" },
          { name: "Watermelon radish", brand: "Pink centre · heirloom", tier: 2, unit: "kg" },
          { name: "Breakfast radish (French)", brand: "Bunch with greens", tier: 2, unit: "bunch" },
          { name: "Sweet potato — orange / white / purple", brand: "By variety", tier: 1, unit: "kg" },
          { name: "Sweet potato — Murasaki (Japanese)", brand: "Purple skin yellow flesh", tier: 2, unit: "kg" },
          { name: "Potato — Yukon Gold (organic)", brand: "Yellow buttery flesh", tier: 1, unit: "kg" },
          { name: "Potato — fingerling (organic)", brand: "Multicolour · Russian Banana, Purple Peruvian", tier: 2, unit: "kg" },
          { name: "Potato — baby new", brand: "Spring peak · whole skin-on", tier: 2, unit: "kg" },
          { name: "Potato — La Ratte", brand: "French fingerling · creamy", tier: 2, unit: "kg" },
          { name: "Potato — Charlotte / Cyprus", brand: "Waxy small", tier: 1, unit: "kg" },
          { name: "Potato — Bintje / Maris Piper", brand: "Floury · frites", tier: 1, unit: "kg" },
          { name: "Jerusalem artichoke (sunchoke)", brand: "Knobby tuber · nutty", tier: 2, unit: "kg" },
          { name: "Yuca / cassava (fresh)", brand: "Cross-ref Caribbean", tier: 1, unit: "kg" },
        ],
      },
      {
        title: "Alliums",
        items: [
          { name: "Spanish / yellow onion", brand: "Storage cooking", tier: 1, unit: "kg" },
          { name: "Red onion", brand: "Salad + service", tier: 1, unit: "kg" },
          { name: "Sweet Vidalia / Cévennes", brand: "Sweet AOP onion", tier: 2, unit: "kg" },
          { name: "Cipollini onions", brand: "Small flat Italian", tier: 2, unit: "kg" },
          { name: "Pearl onions (white + red)", brand: "Pickling / glazing", tier: 1, unit: "kg" },
          { name: "Shallots — banana / Échalion", brand: "French long shallot", tier: 2, unit: "kg" },
          { name: "Shallots — round French (échalote grise)", brand: "Grey AOP · most aromatic", tier: 3, unit: "kg" },
          { name: "Garlic — fresh organic", brand: "Whole heads · French / Spanish", tier: 1, unit: "kg" },
          { name: "Garlic — purple Lautrec AOP", brand: "Premium French", tier: 3, unit: "kg" },
          { name: "Garlic — black (aged)", brand: "Cross-ref Chinese / specialty", tier: 2, unit: "g" },
          { name: "Garlic — wet / green / spring (in season)", brand: "Spring only · whole bulb + stem", tier: 2, unit: "bunch" },
          { name: "Garlic scapes (in season)", brand: "Late spring · curled green", tier: 2, unit: "bunch" },
          { name: "Leeks (organic)", brand: "Whole · trimmed", tier: 1, unit: "kg" },
          { name: "Baby leeks", brand: "Pencil-thin · whole", tier: 2, unit: "bunch" },
          { name: "Scallions / spring onions", brand: "Bunch · trimmed", tier: 1, unit: "bunch" },
          { name: "Chives — fresh", brand: "Cut · long stems", tier: 1, unit: "bunch" },
          { name: "Wild ramps (in season, Apr-May)", brand: "Foraged · spring only", tier: 3, unit: "bunch" },
          { name: "Welsh onion / Calçot (in season)", brand: "Catalan winter specialty", tier: 3, unit: "bunch" },
        ],
      },
      {
        title: "Tomatoes",
        items: [
          { name: "Heirloom tomatoes — mixed", brand: "Black Krim, Brandywine, Cherokee Purple, Green Zebra", tier: 3, unit: "kg" },
          { name: "San Marzano DOP — fresh", brand: "Italian Campania · only in season", tier: 3, unit: "kg" },
          { name: "Pomodorino del Piennolo DOP", brand: "Vesuvio vine-tomato bunch", tier: 3, unit: "kg" },
          { name: "Datterino", brand: "Sicilian cherry-plum", tier: 2, unit: "kg" },
          { name: "Cherry tomatoes — on the vine", brand: "Cluster · red", tier: 1, unit: "kg" },
          { name: "Cherry tomatoes — yellow / sungold", brand: "Sweet golden cherry", tier: 2, unit: "kg" },
          { name: "Roma / plum tomato", brand: "For sauces, dehydrated", tier: 1, unit: "kg" },
          { name: "Beefsteak tomato", brand: "Slicing · large red", tier: 1, unit: "kg" },
          { name: "Green zebra (heirloom)", brand: "Striped green · tangy", tier: 2, unit: "kg" },
          { name: "Tomatillos (green)", brand: "Husked · Mexican (cross-ref)", tier: 1, unit: "kg" },
        ],
      },
      {
        title: "Squash · Gourd · Marrow",
        items: [
          { name: "Courgette / zucchini — green (organic)", brand: "Small to medium", tier: 1, unit: "kg" },
          { name: "Courgette — yellow / striped", brand: "Heirloom mix", tier: 2, unit: "kg" },
          { name: "Courgette flowers (in season)", brand: "Late spring / summer · for stuffing", tier: 3, unit: "pcs" },
          { name: "Patty pan / pattypan", brand: "Small UFO-shape · summer", tier: 2, unit: "kg" },
          { name: "Cucumber — English long", brand: "Wrapped", tier: 1, unit: "pcs" },
          { name: "Cucumber — Persian / Lebanese (organic)", brand: "Small ridged · fresh", tier: 2, unit: "kg" },
          { name: "Cucumber — Armenian", brand: "Ribbed pale", tier: 2, unit: "kg" },
          { name: "Pickling cucumber (Kirby)", brand: "For house-pickles", tier: 2, unit: "kg" },
          { name: "Butternut squash (organic)", brand: "Cooking squash", tier: 1, unit: "kg" },
          { name: "Kabocha squash", brand: "Japanese · dense sweet", tier: 2, unit: "kg" },
          { name: "Delicata / acorn / spaghetti squash", brand: "Specialty squashes", tier: 2, unit: "kg" },
          { name: "Pumpkin — sugar / pie", brand: "Cooking pumpkin · Oct-Dec", tier: 2, unit: "kg" },
          { name: "Calabaza / kabocha (Caribbean cross-ref)", brand: "Tropical pumpkin", tier: 1, unit: "kg" },
          { name: "Bottle gourd / opo (Asian)", brand: "Long pale gourd", tier: 2, unit: "kg" },
        ],
      },
      {
        title: "Mushrooms — Cultivated + Wild",
        items: [
          { name: "Button mushrooms (white / brown)", brand: "Whole · for general use", tier: 1, unit: "kg" },
          { name: "Cremini (baby bella)", brand: "Slightly aged button", tier: 1, unit: "kg" },
          { name: "Portobello — large cap", brand: "Grilling · whole", tier: 1, unit: "kg" },
          { name: "Shiitake — fresh", brand: "Wood-grown · whole + stems", tier: 2, unit: "kg" },
          { name: "Oyster mushroom — king (eryngii)", brand: "Thick stems · meaty", tier: 2, unit: "kg" },
          { name: "Oyster mushroom — yellow / pink", brand: "Specialty colours", tier: 2, unit: "kg" },
          { name: "Enoki", brand: "Long thin white bunch · Asian", tier: 1, unit: "pack" },
          { name: "Maitake (hen of the woods)", brand: "Cluster · forest mushroom", tier: 3, unit: "kg" },
          { name: "Chanterelle (in season Jun-Oct)", brand: "Wild-foraged · golden", tier: 3, unit: "kg" },
          { name: "Black trompette de la mort", brand: "Wild · Sep-Nov", tier: 3, unit: "kg" },
          { name: "Porcini — fresh (in season)", brand: "Wild Italian · Sep-Nov", tier: 3, unit: "kg" },
          { name: "Morels — fresh (Mar-May)", brand: "Wild · spring only", tier: 3, unit: "kg" },
          { name: "Hedgehog mushrooms (pied de mouton)", brand: "Wild · autumn", tier: 3, unit: "kg" },
          { name: "Mousseron / pied bleu", brand: "Wild French", tier: 3, unit: "kg" },
        ],
      },
      {
        title: "Peppers — Sweet + Hot",
        items: [
          { name: "Bell pepper — red / yellow / orange (organic)", brand: "Whole", tier: 1, unit: "kg" },
          { name: "Bell pepper — green", brand: "Less sweet", tier: 1, unit: "kg" },
          { name: "Padrón peppers (Galician)", brand: "Spanish · pan-fry whole", tier: 2, unit: "kg" },
          { name: "Shishito peppers (Japanese)", brand: "Mild · for blistering", tier: 2, unit: "kg" },
          { name: "Piquillo peppers — fresh", brand: "Spanish · Lodosa DOP-region", tier: 3, unit: "kg" },
          { name: "Jalapeño — fresh green / red", brand: "Mexican (cross-ref)", tier: 1, unit: "kg" },
          { name: "Serrano (Mexican)", brand: "Hot small", tier: 1, unit: "kg" },
          { name: "Habanero (Caribbean) / Scotch bonnet", brand: "Fresh whole", tier: 2, unit: "kg" },
          { name: "Thai bird's eye chili — fresh", brand: "SEA cross-ref", tier: 1, unit: "g" },
          { name: "Long red Italian peppers", brand: "Friggitelli / cubanelle", tier: 2, unit: "kg" },
          { name: "Ají amarillo — fresh (S America)", brand: "Peruvian yellow chili", tier: 2, unit: "kg" },
          { name: "Espelette pepper — fresh (in season Aug-Oct)", brand: "Basque AOP · fresh whole", tier: 3, unit: "kg" },
        ],
      },
      {
        title: "Aubergine · Fennel · Mediterranean",
        items: [
          { name: "Aubergine — globe (organic)", brand: "Black purple · medium", tier: 1, unit: "kg" },
          { name: "Aubergine — Japanese / Chinese", brand: "Long slim purple", tier: 2, unit: "kg" },
          { name: "Aubergine — Sicilian Striato di Napoli", brand: "Heirloom · striped", tier: 2, unit: "kg" },
          { name: "Aubergine — baby Indian / Thai", brand: "Small round green / purple", tier: 2, unit: "kg" },
          { name: "Aubergine — Graffiti / Listada", brand: "Heirloom · striped purple", tier: 2, unit: "kg" },
          { name: "Fennel bulb — Florence (organic)", brand: "Crisp bulb with fronds", tier: 1, unit: "kg" },
          { name: "Baby fennel", brand: "Whole small bulbs", tier: 2, unit: "kg" },
          { name: "Artichoke — globe French", brand: "Whole · Provence / Brittany", tier: 2, unit: "pcs" },
          { name: "Artichoke — purple Italian", brand: "Romanesco / Carciofo Romanesco", tier: 3, unit: "pcs" },
          { name: "Artichoke — baby (poivrade)", brand: "Eaten whole", tier: 3, unit: "pcs" },
          { name: "Asparagus — green (organic)", brand: "Standard or jumbo", tier: 1, unit: "kg" },
          { name: "Asparagus — white French (in season Apr-Jun)", brand: "Landes / Loire AOP", tier: 3, unit: "kg" },
          { name: "Asparagus — wild thin / sprue", brand: "Spring foraged", tier: 3, unit: "bunch" },
          { name: "Asparagus — purple", brand: "Heirloom · raw service", tier: 3, unit: "bunch" },
          { name: "Cardoon (cardon)", brand: "Like artichoke stem · winter", tier: 3, unit: "kg" },
          { name: "Sea kale / chou marin", brand: "British coastal · winter forced", tier: 3, unit: "bunch" },
          { name: "Samphire / sea beans", brand: "Marsh-grown · fresh", tier: 2, unit: "kg" },
        ],
      },
      {
        title: "Avocado · Tropical Fruit",
        items: [
          { name: "Avocado — Hass (organic)", brand: "Ripening at room temp", tier: 1, unit: "pcs" },
          { name: "Avocado — Pinkerton / Reed (large)", brand: "Bigger fruit", tier: 2, unit: "pcs" },
          { name: "Avocado — Bacon (smooth-skinned)", brand: "Smooth Italian-style", tier: 2, unit: "pcs" },
          { name: "Mango — Alphonso (in season May-Jul)", brand: "Indian premium", tier: 3, unit: "kg" },
          { name: "Mango — Ataulfo / Honey", brand: "Yellow smooth flesh", tier: 2, unit: "kg" },
          { name: "Mango — Kent / Tommy", brand: "Standard varieties", tier: 1, unit: "kg" },
          { name: "Papaya (Mexican / Hawaiian)", brand: "Whole · ripe-orange", tier: 1, unit: "kg" },
          { name: "Pineapple — Sugarloaf (white)", brand: "South American sweet white", tier: 2, unit: "pcs" },
          { name: "Pineapple — gold (Costa Rican)", brand: "Standard sweet pineapple", tier: 1, unit: "pcs" },
          { name: "Passion fruit", brand: "Whole · for sauce + plating", tier: 2, unit: "kg" },
          { name: "Dragon fruit (pitaya) — red or white", brand: "Tropical · for plating", tier: 2, unit: "kg" },
          { name: "Lychee — fresh", brand: "Asian · in season May-Jul", tier: 2, unit: "kg" },
          { name: "Rambutan — fresh", brand: "Hairy lychee cousin · SE Asia", tier: 2, unit: "kg" },
          { name: "Mangosteen — fresh", brand: "Queen of fruits · SE Asia", tier: 3, unit: "kg" },
          { name: "Guava — pink or white", brand: "Tropical · for plating, juice", tier: 2, unit: "kg" },
          { name: "Cape gooseberry (physalis)", brand: "Husk-wrapped · garnish", tier: 2, unit: "pcs" },
          { name: "Pomegranate (Wonderful)", brand: "Whole · for seeds", tier: 1, unit: "pcs" },
          { name: "Persimmon (Hachiya / Fuyu)", brand: "Autumn fruit", tier: 2, unit: "kg" },
          { name: "Fig — fresh black mission / brown turkey", brand: "Summer + autumn", tier: 2, unit: "kg" },
          { name: "Fig — green / violetta", brand: "Specialty varieties", tier: 3, unit: "kg" },
        ],
      },
      {
        title: "Citrus",
        items: [
          { name: "Lemon — Eureka (organic)", brand: "Standard cooking lemon", tier: 1, unit: "kg" },
          { name: "Lemon — Meyer", brand: "Sweeter, less acid · Californian", tier: 2, unit: "kg" },
          { name: "Lemon — Amalfi (in season)", brand: "IGP · large fragrant Sfusato", tier: 3, unit: "kg" },
          { name: "Lemon — Sorrento IGP", brand: "Italian premium · perfumed", tier: 3, unit: "kg" },
          { name: "Lemon — Sicilian (femminello)", brand: "Italian premium", tier: 2, unit: "kg" },
          { name: "Lime — Persian (Tahitian)", brand: "Standard cooking lime", tier: 1, unit: "kg" },
          { name: "Lime — Key (Mexican)", brand: "Small intense · for pie", tier: 2, unit: "kg" },
          { name: "Lime — Kaffir / makrut leaves", brand: "Cross-ref SEA", tier: 2, unit: "g" },
          { name: "Lime — finger lime / citrus caviar", brand: "Australian native", tier: 3, unit: "kg" },
          { name: "Yuzu — fresh (in season Oct-Jan)", brand: "Japanese · for juice + zest", tier: 3, unit: "kg" },
          { name: "Sudachi — fresh (Aug-Oct)", brand: "Japanese small green citrus", tier: 3, unit: "kg" },
          { name: "Kabosu — fresh", brand: "Japanese citrus", tier: 3, unit: "kg" },
          { name: "Orange — Valencia (organic)", brand: "Juicing", tier: 1, unit: "kg" },
          { name: "Orange — Cara Cara", brand: "Pink-flesh navel", tier: 2, unit: "kg" },
          { name: "Orange — blood (sanguine / Tarocco)", brand: "Sicilian · late winter", tier: 3, unit: "kg" },
          { name: "Orange — Seville (bitter)", brand: "For marmalade · Jan-Feb only", tier: 2, unit: "kg" },
          { name: "Mandarin / clementine — Corsican (in season)", brand: "AOP · winter only", tier: 3, unit: "kg" },
          { name: "Bergamot (in season)", brand: "Calabrian · Nov-Mar", tier: 3, unit: "kg" },
          { name: "Grapefruit — pink / ruby", brand: "Whole", tier: 1, unit: "kg" },
          { name: "Kumquat", brand: "Whole skin-on · for confit", tier: 2, unit: "kg" },
          { name: "Calamondin / calamansi", brand: "Filipino lime-orange hybrid", tier: 2, unit: "kg" },
        ],
      },
      {
        title: "Stone Fruit · Berries · Pome",
        items: [
          { name: "Peach — white (in season Jul-Sep)", brand: "Honey-flesh · Italian preferred", tier: 2, unit: "kg" },
          { name: "Peach — yellow", brand: "Standard", tier: 1, unit: "kg" },
          { name: "Donut / Saturn peach", brand: "Flat sweet variety", tier: 2, unit: "kg" },
          { name: "Apricot — fresh (Jun-Aug)", brand: "Provence Bergeron / Sicily", tier: 2, unit: "kg" },
          { name: "Plum — Italian prune (Damson / Quetsche)", brand: "Late summer · for tarts", tier: 2, unit: "kg" },
          { name: "Plum — Mirabelle (Aug-Sep)", brand: "Yellow Lorraine PGI", tier: 3, unit: "kg" },
          { name: "Plum — Reine Claude (greengage)", brand: "Late summer green plum", tier: 3, unit: "kg" },
          { name: "Cherry — Burlat / Bing (early summer)", brand: "Premium · season Jun-Jul", tier: 2, unit: "kg" },
          { name: "Sour cherry (Morello / Amarena, in season)", brand: "For clafoutis · brief season", tier: 3, unit: "kg" },
          { name: "Nectarine — white / yellow", brand: "Stone fruit summer", tier: 1, unit: "kg" },
          { name: "Strawberry — Gariguette / Mara des Bois", brand: "French heirloom · perfumed", tier: 3, unit: "kg" },
          { name: "Strawberry — standard", brand: "Whole", tier: 1, unit: "kg" },
          { name: "Strawberry — wild (fraises des bois)", brand: "Tiny intense · summer", tier: 3, unit: "pack" },
          { name: "Raspberry — fresh (red)", brand: "Whole · for service", tier: 2, unit: "kg" },
          { name: "Raspberry — golden", brand: "Specialty colour", tier: 3, unit: "kg" },
          { name: "Blackberry / mulberry", brand: "Wild or cultivated", tier: 2, unit: "kg" },
          { name: "Blueberry — wild Maine (in season Jul-Sep)", brand: "Smaller intense · for desserts", tier: 3, unit: "kg" },
          { name: "Blueberry — cultivated", brand: "Standard whole", tier: 1, unit: "kg" },
          { name: "Redcurrant / blackcurrant — fresh (summer)", brand: "Whole strands · for garnish", tier: 3, unit: "kg" },
          { name: "Gooseberry — green or red", brand: "Tart · British / Northern Europe", tier: 2, unit: "kg" },
          { name: "Apple — Pink Lady (organic)", brand: "Premium crunchy", tier: 2, unit: "kg" },
          { name: "Apple — Honeycrisp", brand: "Premium sweet-crisp", tier: 2, unit: "kg" },
          { name: "Apple — Granny Smith (organic)", brand: "Tart green", tier: 1, unit: "kg" },
          { name: "Apple — Reinette / Bramley", brand: "Cooking apple", tier: 2, unit: "kg" },
          { name: "Pear — Comice (Doyenné)", brand: "French dessert pear · winter", tier: 3, unit: "kg" },
          { name: "Pear — Williams / Bartlett", brand: "Cooking + dessert", tier: 1, unit: "kg" },
          { name: "Pear — Bosc", brand: "Brown skin · firm", tier: 2, unit: "kg" },
          { name: "Pear — Asian (nashi)", brand: "Crisp apple-textured", tier: 2, unit: "kg" },
          { name: "Quince — fresh (Sep-Dec)", brand: "Hard fragrant · for paste, poaching", tier: 2, unit: "kg" },
        ],
      },
      {
        title: "Melons · Grapes",
        items: [
          { name: "Watermelon — seedless or seeded", brand: "Whole", tier: 1, unit: "pcs" },
          { name: "Cantaloupe — French Charentais", brand: "Premium small · Cavaillon PDO", tier: 3, unit: "pcs" },
          { name: "Cantaloupe — standard", brand: "Whole", tier: 1, unit: "pcs" },
          { name: "Honeydew melon", brand: "Whole", tier: 1, unit: "pcs" },
          { name: "Galia / Piel de Sapo melon", brand: "Spanish whole", tier: 2, unit: "pcs" },
          { name: "Grapes — Muscat (white / black)", brand: "Italian / French · in season", tier: 2, unit: "kg" },
          { name: "Grapes — Thompson seedless", brand: "Standard table", tier: 1, unit: "kg" },
          { name: "Grapes — Concord / Champagne", brand: "Specialty varieties", tier: 2, unit: "kg" },
        ],
      },
      {
        title: "Fresh Herbs",
        items: [
          { name: "Basil — Genovese DOP (organic)", brand: "Ligurian PDO · for pesto", tier: 2, unit: "bunch" },
          { name: "Basil — Thai (horapha / holy)", brand: "Anise / spicy", tier: 2, unit: "bunch" },
          { name: "Basil — purple opal", brand: "Plating + Asian", tier: 2, unit: "bunch" },
          { name: "Parsley — flat-leaf Italian", brand: "Bunch", tier: 1, unit: "bunch" },
          { name: "Parsley — curly", brand: "Bunch", tier: 1, unit: "bunch" },
          { name: "Coriander / cilantro — with roots", brand: "For Thai pastes", tier: 1, unit: "bunch" },
          { name: "Mint — peppermint / spearmint", brand: "Bunch", tier: 1, unit: "bunch" },
          { name: "Mint — Moroccan (nana)", brand: "For tea + tabbouleh", tier: 2, unit: "bunch" },
          { name: "Dill — fresh", brand: "Bunch", tier: 1, unit: "bunch" },
          { name: "Tarragon — French", brand: "Bunch", tier: 2, unit: "bunch" },
          { name: "Chervil — French", brand: "Bunch · delicate", tier: 2, unit: "bunch" },
          { name: "Oregano — fresh", brand: "Bunch", tier: 1, unit: "bunch" },
          { name: "Thyme — common / lemon", brand: "Bunches", tier: 1, unit: "bunch" },
          { name: "Rosemary", brand: "Bunches", tier: 1, unit: "bunch" },
          { name: "Sage — Dalmatian", brand: "Bunch", tier: 1, unit: "bunch" },
          { name: "Bay leaves — fresh", brand: "Branches", tier: 2, unit: "bunch" },
          { name: "Marjoram — fresh", brand: "Bunch", tier: 2, unit: "bunch" },
          { name: "Savory — fresh", brand: "Bunch", tier: 2, unit: "bunch" },
          { name: "Lemon balm / verveine / lemon verbena", brand: "Bunches", tier: 2, unit: "bunch" },
          { name: "Sorrel — French", brand: "Lemony · for fish", tier: 2, unit: "bunch" },
          { name: "Lovage — fresh", brand: "Strong celery-like", tier: 2, unit: "bunch" },
          { name: "Lemongrass — fresh", brand: "Stalks · SEA cross-ref", tier: 1, unit: "bunch" },
          { name: "Kaffir lime leaves — fresh", brand: "SEA cross-ref", tier: 2, unit: "g" },
          { name: "Pandan — fresh leaves", brand: "Asian · for desserts + rice", tier: 2, unit: "bunch" },
          { name: "Vietnamese mint / rau ram", brand: "Bunch", tier: 2, unit: "bunch" },
          { name: "Shiso — green + red (perilla)", brand: "Japanese · whole leaves", tier: 2, unit: "pack" },
          { name: "Curry leaves — fresh", brand: "Indian · cross-ref", tier: 1, unit: "bunch" },
          { name: "Holy basil (kaprao)", brand: "Thai", tier: 2, unit: "bunch" },
          { name: "Epazote — fresh", brand: "Mexican · cross-ref", tier: 2, unit: "bunch" },
          { name: "Hoja santa — fresh", brand: "Mexican · cross-ref", tier: 2, unit: "g" },
          { name: "Chadon beni / culantro — fresh", brand: "Caribbean · cross-ref", tier: 2, unit: "bunch" },
        ],
      },
      {
        title: "Asian Vegetables — Greens · Roots · Aromatics",
        items: [
          { name: "Bok choy — Shanghai (baby)", brand: "Tender small green-stem", tier: 2, unit: "kg" },
          { name: "Pak choy — full size", brand: "White stem · steam or stir-fry", tier: 1, unit: "kg" },
          { name: "Choy sum (yu choy / cai xin)", brand: "Yellow-flowered Chinese green", tier: 1, unit: "kg" },
          { name: "Chinese broccoli (gai lan / kai lan)", brand: "Thick stems · oyster-sauce classic", tier: 1, unit: "kg" },
          { name: "Water spinach (kangkong / ong choy / morning glory)", brand: "Hollow-stemmed · stir-fry with garlic & chili", tier: 1, unit: "kg" },
          { name: "Mustard greens (gai choy)", brand: "Spicy Asian · braise or pickle", tier: 1, unit: "kg" },
          { name: "Yu choy sum (cai xin baby)", brand: "Sweet Chinese greens · whole bunches", tier: 2, unit: "kg" },
          { name: "Garlic chives (Chinese chives / nira / gow choy)", brand: "Flat green leaf · for dumplings + pancakes", tier: 2, unit: "bunch" },
          { name: "Mizuna (Japanese mustard)", brand: "Frilled jagged leaf · salads", tier: 2, unit: "bunch" },
          { name: "Tatsoi (Asian spinach)", brand: "Rosette dark green · stir-fry or raw", tier: 2, unit: "bunch" },
          { name: "Komatsuna (Japanese mustard spinach)", brand: "Mild green · soups + sides", tier: 2, unit: "bunch" },
          { name: "Mitsuba (Japanese parsley)", brand: "Three-leaflet · clear soups, chawanmushi", tier: 3, unit: "bunch" },
          { name: "Shungiku (chrysanthemum greens / tong ho)", brand: "Edible chrysanthemum · hot pot, sukiyaki", tier: 2, unit: "bunch" },
          { name: "Banana blossom / banana flower", brand: "Whole or pre-cleaned · Vietnamese salads", tier: 2, unit: "pcs" },
          { name: "Lotus root (renkon)", brand: "Whole · slice and braise / stir-fry", tier: 2, unit: "kg" },
          { name: "Lotus stem (in Vietnamese / Indian)", brand: "Tender stem · pickled or stir-fried", tier: 2, unit: "kg" },
          { name: "Bamboo shoots — fresh", brand: "Whole · winter or spring · boil before use", tier: 2, unit: "kg" },
          { name: "Burdock root (gobo)", brand: "Long brown root · Japanese kinpira", tier: 2, unit: "kg" },
          { name: "Snow peas (mangetout)", brand: "Whole pod · stir-fry, raw", tier: 1, unit: "kg" },
          { name: "Sugar snap peas", brand: "Sweet whole pod", tier: 1, unit: "kg" },
          { name: "Long beans / yard-long beans", brand: "Chinese · 60 cm long · stir-fry", tier: 1, unit: "kg" },
          { name: "Bitter melon (karela / fu gua)", brand: "Wrinkly green · braise or stuff", tier: 2, unit: "kg" },
          { name: "Winter melon (dong gua)", brand: "Large pale gourd · soups", tier: 2, unit: "kg" },
          { name: "Snake gourd", brand: "Long ribbed gourd · Asian", tier: 2, unit: "kg" },
          { name: "Wing bean", brand: "Square-ridged Asian bean · whole pod", tier: 3, unit: "kg" },
          { name: "Edamame — fresh in pod", brand: "Soybean · summer Japan-imported", tier: 2, unit: "kg" },
          { name: "Mung bean sprouts", brand: "White short sprouts · banh mi, stir-fry", tier: 1, unit: "kg" },
          { name: "Soybean sprouts", brand: "Bigger head · Korean kongnamul-guk", tier: 2, unit: "kg" },
          { name: "Chinese long onion / Welsh onion (negi)", brand: "Thick green-white scallion · Japanese", tier: 2, unit: "bunch" },
          { name: "Ginger root — fresh young (in season)", brand: "Pink-tipped, mild · summer specialty", tier: 3, unit: "kg" },
          { name: "Ginger root — mature", brand: "Aromatic · for cooking", tier: 1, unit: "kg" },
          { name: "Galangal — fresh root", brand: "Thai / Indonesian · for curries", tier: 2, unit: "kg" },
          { name: "Turmeric — fresh root", brand: "Orange / yellow finger · grate fresh", tier: 2, unit: "kg" },
          { name: "Fingerroot (krachai)", brand: "Thai · for jungle curry, pomelo salad", tier: 3, unit: "kg" },
          { name: "Wasabi — fresh root", brand: "Real Daio Shizuoka · grate at service (cross-ref Japan)", tier: 3, unit: "pcs" },
          { name: "Sawtooth coriander (ngo gai / culantro Asian)", brand: "Vietnamese pho + Caribbean cross-ref", tier: 2, unit: "bunch" },
          { name: "Daikon — Korean (mu)", brand: "Shorter, fatter Korean radish · kimchi base", tier: 2, unit: "kg" },
          { name: "Asian eggplant — Thai pea", brand: "Small green peas · Thai green curry", tier: 3, unit: "kg" },
          { name: "Asian eggplant — Indian baby", brand: "Small round · stuff or curry", tier: 2, unit: "kg" },
          { name: "Asian pumpkin / Kabocha leaves", brand: "Squash tips · stir-fry", tier: 3, unit: "bunch" },
          { name: "Lemongrass — fresh stalks", brand: "Whole stalks · SEA cross-ref", tier: 2, unit: "bunch" },
          { name: "Kaffir lime leaves — fresh", brand: "Whole leaves · SEA cross-ref", tier: 2, unit: "g" },
          { name: "Curry leaves — fresh sprigs", brand: "Indian Madras / Kashmiri · cross-ref India", tier: 2, unit: "bunch" },
          { name: "Pandan leaves — fresh", brand: "Long green blade · SEA desserts + rice", tier: 2, unit: "bunch" },
          { name: "Vietnamese coriander (rau ram)", brand: "Stronger than cilantro · pho garnish", tier: 2, unit: "bunch" },
          { name: "Thai basil (horapa / holy)", brand: "Anise / spicy · curries", tier: 2, unit: "bunch" },
          { name: "Vietnamese perilla (tía tô)", brand: "Red-green · bún chả wraps", tier: 3, unit: "pack" },
          { name: "Holy basil (kaprao / krapao)", brand: "For pad kra pao · fragrant", tier: 2, unit: "bunch" },
        ],
      },
      {
        title: "Tropical Fruit · Caribbean Roots · Polynesian",
        items: [
          { name: "Jackfruit — fresh whole / pre-cut", brand: "Tropical · ripe sweet OR green for cooking", tier: 3, unit: "kg" },
          { name: "Young coconut (drinking)", brand: "Whole · for coconut water + tender meat", tier: 2, unit: "pcs" },
          { name: "Mature coconut — whole", brand: "For grating, milk-pressing", tier: 1, unit: "pcs" },
          { name: "Coconut — pre-grated frozen", brand: "Backup for fresh", tier: 1, unit: "kg" },
          { name: "Durian — fresh (in season Apr-Jun)", brand: "Thai Mon Thong or Musang King premium", tier: 3, unit: "kg" },
          { name: "Sapodilla / sapote / chiku", brand: "Brown sweet pear-textured fruit", tier: 2, unit: "kg" },
          { name: "Soursop / graviola (in season)", brand: "Spiky green · tart custard flesh · juices + sorbets", tier: 3, unit: "kg" },
          { name: "Cherimoya (custard apple)", brand: "Andean · scaly green skin · creamy flesh", tier: 3, unit: "kg" },
          { name: "Atemoya (Cherimoya × Sugar apple)", brand: "Tropical hybrid · custard texture", tier: 3, unit: "kg" },
          { name: "Sugar apple / sweetsop", brand: "Round bumpy green · sweet creamy", tier: 3, unit: "kg" },
          { name: "Mamey sapote", brand: "Tropical · salmon-orange flesh", tier: 3, unit: "kg" },
          { name: "Naranjilla / lulo (Andean)", brand: "Frozen pulp · for batidos + sorbets", tier: 3, unit: "kg" },
          { name: "Loquat (in season Mar-May)", brand: "Stone fruit · Mediterranean & East Asia", tier: 3, unit: "kg" },
          { name: "Bilimbi (Indian)", brand: "Sour green Asian fruit · for chutney", tier: 3, unit: "kg" },
          { name: "Pomelo (Asian)", brand: "Largest citrus · pink or white · Thai salad", tier: 2, unit: "kg" },
          { name: "Star fruit (carambola)", brand: "Five-star cross-section · garnish + salad", tier: 2, unit: "kg" },
          { name: "Dragon fruit — pink / yellow / white flesh", brand: "Specialty varieties · plating", tier: 3, unit: "kg" },
          { name: "Tamarind pods — fresh", brand: "Brown bean-pod · for fresh pulping", tier: 3, unit: "kg" },
          { name: "Cacao pod — fresh (specialty)", brand: "Whole pod · fresh pulp + bean", tier: 3, unit: "pcs" },
          { name: "Green almond — fresh (Mar-May)", brand: "Whole fuzzy pod · Mediterranean specialty", tier: 3, unit: "kg" },
          { name: "Green pistachio — fresh in shell", brand: "Sicilian Bronte fresh · summer only · ultra-rare", tier: 3, unit: "kg" },
          { name: "Plantain — green", brand: "For tostones (cross-ref Caribbean)", tier: 1, unit: "kg" },
          { name: "Plantain — yellow ripe", brand: "For maduros · sweet fried", tier: 1, unit: "kg" },
          { name: "Plantain — black very ripe", brand: "For maduros + dessert", tier: 2, unit: "kg" },
          { name: "Hearts of palm — fresh", brand: "Whole cylinder · Brazilian / Costa Rican", tier: 3, unit: "kg" },
          { name: "Taro / dasheen root", brand: "Caribbean / Hawaiian / Asian · brown hairy root", tier: 2, unit: "kg" },
          { name: "Eddoes / coco yam", brand: "Smaller taro · Caribbean", tier: 2, unit: "kg" },
          { name: "Yam — Caribbean (white or yellow)", brand: "Cross-ref Caribbean", tier: 1, unit: "kg" },
          { name: "Yam — Japanese yamaimo (nagaimo)", brand: "For tororo (grated raw) · slime trail", tier: 3, unit: "kg" },
          { name: "Cassava / yuca — fresh", brand: "Cross-ref Caribbean + S America", tier: 1, unit: "kg" },
          { name: "Christophine / chayote (Caribbean)", brand: "Cross-ref · pear-shaped squash", tier: 2, unit: "kg" },
          { name: "Cassava leaves — fresh", brand: "African + Brazilian · must cook thoroughly", tier: 3, unit: "kg" },
          { name: "Callaloo / dasheen leaves — fresh", brand: "Caribbean greens · for callaloo", tier: 2, unit: "bunch" },
          { name: "Ackee — fresh (when in season)", brand: "Jamaica · arils only · BLOOD-RED outside means RIPE", tier: 3, unit: "kg" },
          { name: "Breadfruit — fresh", brand: "Caribbean + Polynesian · roast or fry", tier: 2, unit: "pcs" },
          { name: "Banana leaves — fresh", brand: "For wrapping, plating · cross-ref SEA", tier: 2, unit: "pack" },
          { name: "Hoja santa leaves — fresh (Mexican)", brand: "Anise / sassafras notes · wrapping fish", tier: 3, unit: "pack" },
          { name: "Avocado leaf — fresh (Mexican Oaxacan)", brand: "Anise scent · for braises", tier: 3, unit: "pack" },
          { name: "Sour orange / naranja agria (Caribbean)", brand: "For Cuban mojo · cross-ref", tier: 2, unit: "kg" },
          { name: "Calamondin / calamansi — fresh", brand: "Filipino baby-lime-orange · juice + zest", tier: 3, unit: "kg" },
          { name: "Buddha's hand citrus", brand: "Finger-shaped citron · zest + perfume", tier: 3, unit: "pcs" },
          { name: "Coconut water — fresh (young coconut)", brand: "Drinking from whole coconut", tier: 2, unit: "L" },
          { name: "Aji dulce (Trinidadian sweet seasoning pepper)", brand: "Looks like habanero, sweet flavour · green seasoning base", tier: 2, unit: "g" },
        ],
      },
      {
        title: "Microgreens · Sprouts · Edible Flowers",
        items: [
          { name: "Micro red radish", brand: "Pinch · plating", tier: 2, unit: "pack" },
          { name: "Micro cilantro / coriander", brand: "Plating", tier: 2, unit: "pack" },
          { name: "Micro basil", brand: "Plating", tier: 2, unit: "pack" },
          { name: "Micro mustard / arugula", brand: "Sharp plating", tier: 2, unit: "pack" },
          { name: "Micro pea shoots", brand: "Sweet plating", tier: 2, unit: "pack" },
          { name: "Micro shiso (red + green)", brand: "Japanese", tier: 2, unit: "pack" },
          { name: "Micro nasturtium", brand: "Peppery", tier: 2, unit: "pack" },
          { name: "Micro amaranth (red)", brand: "Plating colour", tier: 2, unit: "pack" },
          { name: "Sprouted alfalfa", brand: "Whole sprouts", tier: 1, unit: "pack" },
          { name: "Sprouted broccoli", brand: "Sulforaphane-rich", tier: 2, unit: "pack" },
          { name: "Sprouted mung bean / lentil", brand: "Whole · Asian", tier: 1, unit: "pack" },
          { name: "Edible flowers — nasturtium", brand: "Yellow + orange", tier: 3, unit: "pack" },
          { name: "Edible flowers — pansy / viola", brand: "Mini multi-coloured", tier: 3, unit: "pack" },
          { name: "Edible flowers — borage (blue starflower)", brand: "Spring · cucumber-flavoured", tier: 3, unit: "pack" },
          { name: "Edible flowers — rose petal (organic)", brand: "Untreated", tier: 3, unit: "pack" },
          { name: "Edible flowers — marigold (calendula)", brand: "Orange petals", tier: 2, unit: "pack" },
          { name: "Edible flowers — courgette / squash", brand: "Summer only · for stuffing", tier: 3, unit: "pcs" },
        ],
      },
    ],
  };

  // Assign stable IDs
  cat.sections.forEach((s, si) => {
    s.items.forEach((it, ii) => {
      it.id = `produce-${si}-${ii}`;
    });
  });

  // Insert Produce just after Meat (position 2) so it sits with proteins/produce in flow
  const insertAt = window.PANTRY_DATA.findIndex(c => c.id === "freezer");
  if (insertAt > 0) {
    window.PANTRY_DATA.splice(insertAt, 0, cat);
  } else {
    window.PANTRY_DATA.push(cat);
  }
})();
