/* Terroir — Costa Brava — auto-generated by publish-terroir.py */
window.TERROIR_DATA = (function () {
    const COLORS = { berth:'#c4a35a', market:'#d97706', shop:'#059669', mainland:'#7c3aed', logistics:'#2d4a5e' };
    const CAT_LABELS = { berth:'Signature', market:'Market / Direct', shop:'Restaurant / Bar', mainland:'Out of town', logistics:'Logistics' };
    const PRODUCT_COLORS = {
    'Michelin':'#7f1d1d','Contemporary':'#1f2937','Traditional':'#a16207',
    'Cult':'#7c3aed','Cafe':'#92400e','Wine':'#7c2d12','Bacaro':'#7c3aed',
    'Drink':'#0ea5e9','Street Food':'#dc2626','Market':'#d97706',
    'Produce':'#15803d','Fish':'#3b82f6','Meat':'#b91c1c',
    'Cheese':'#eab308','Bread':'#a16207','Charcuterie':'#9d174d',
    'Hi-Fi':'#1f2937'
};
    const VENUES = [
  {
    "id": "v01-el-celler-de-can-roca",
    "cat": "shop",
    "tier": "berth_top",
    "priority": 1,
    "badge": "MICHELIN",
    "name": "El Celler de Can Roca",
    "short": "El Celler de Can Roca",
    "lat": 41.9934,
    "lng": 2.80777,
    "tags": [
      "★★★; twice World's #1; the Roca brothers' flagship",
      "EUR 250-365 menu (before wine)",
      "Essential",
      "Dinner"
    ],
    "productTags": [
      "Michelin",
      "Contemporary",
      "Wine"
    ],
    "why": "★★★; twice World's #1; the Roca brothers' flagship. To order: the long \"Festival\" tasting menu (the only format); the perfume-inspired desserts; the legendary cellar pairing. The defining pilgrimage of Catalan gastronomy — books roughly eleven months ahead the instant the monthly slot opens; reserve before you plan the trip.",
    "address": "Carrer de Can Sunyer 48, 17007 Girona",
    "phone": "",
    "hours": "Dinner",
    "maps": "https://www.google.com/maps/search/?api=1&query=El+Celler+de+Can+Roca+Costa+Brava"
  },
  {
    "id": "v02-bo-tic",
    "cat": "shop",
    "tier": "berth_top",
    "priority": 2,
    "badge": "MICHELIN",
    "name": "Bo.TiC",
    "short": "Bo.TiC",
    "lat": 41.9879,
    "lng": 3.016,
    "tags": [
      "★★ (second star 2018); chef Albert Sastregener, in a converted carriage factory",
      "EUR 150-210 menu",
      "Essential",
      "Lunch"
    ],
    "productTags": [
      "Michelin",
      "Contemporary"
    ],
    "why": "★★ (second star 2018); chef Albert Sastregener, in a converted carriage factory. To order: the tasting menu; the seasonal Empordà vegetable courses; pigeon and game in season. Empordanet's quiet two-star, refined regional cooking without the Roca crowds. Coordinate is approximate — sources disagree by ~1.4 km along the C-66; verify the exact building on arrival.",
    "address": "Avinguda Costa Brava 6, 17121 Corçà",
    "phone": "",
    "hours": "Lunch",
    "maps": "https://www.google.com/maps/search/?api=1&query=Bo.TiC+Costa+Brava"
  },
  {
    "id": "v03-compartir-cadaqu-s",
    "cat": "shop",
    "tier": "berth_top",
    "priority": 3,
    "badge": "CONTEMPOR",
    "name": "Compartir Cadaqués",
    "short": "Compartir Cadaqués",
    "lat": 42.28934,
    "lng": 3.27602,
    "tags": [
      "From Castro, Xatruch & Casañas — the elBulli trio behind three-star Disfrutar",
      "EUR 70-110",
      "Essential in summer",
      "Lunch on the patio"
    ],
    "productTags": [
      "Contemporary",
      "Fish"
    ],
    "why": "From Castro, Xatruch & Casañas — the elBulli trio behind three-star Disfrutar. To order: the \"to share\" small plates — gambas, the spherified snacks, seasonal fish; the playful desserts. Disfrutar-level creativity at a fraction of the price, in a whitewashed courtyard in Dalí's village.",
    "address": "Riera de Sant Vicenç s/n, 17488 Cadaqués",
    "phone": "",
    "hours": "Lunch on the patio",
    "maps": "https://www.google.com/maps/search/?api=1&query=Compartir+Cadaqués+Costa+Brava"
  },
  {
    "id": "v04-casamar",
    "cat": "shop",
    "tier": "several",
    "priority": 4,
    "badge": "CONTEMPOR",
    "name": "Casamar",
    "short": "Casamar",
    "lat": 41.89302,
    "lng": 3.1906,
    "tags": [
      "Chef Quim Casellas; held a Michelin star c.2011–2021, no longer starred as of 2026",
      "EUR 75-120 menus",
      "Recommended (Essential in summer)",
      "Dinner at sunset for the bay view"
    ],
    "productTags": [
      "Contemporary",
      "Fish"
    ],
    "why": "Chef Quim Casellas; held a Michelin star c.2011–2021, no longer starred as of 2026. To order: the tasting menu; local rock-fish and shellfish; Cap-de-Creus-influenced plates. Star or not, the most ambitious cooking in the Palafrugell coves; its door opens onto the camí de ronda steps.",
    "address": "Carrer del Nero 3, 17211 Llafranc (Palafrugell)",
    "phone": "",
    "hours": "Dinner at sunset for the bay view",
    "maps": "https://www.google.com/maps/search/?api=1&query=Casamar+Costa+Brava"
  },
  {
    "id": "v05-restaurant-massana",
    "cat": "shop",
    "tier": "several",
    "priority": 5,
    "badge": "MICHELIN",
    "name": "Restaurant Massana",
    "short": "Restaurant Massana",
    "lat": 41.98489,
    "lng": 2.81944,
    "tags": [
      "★ since 2007; chef Pere Massana — the city's reliable counterpoint to the Rocas",
      "EUR 110-160",
      "Recommended/Essential",
      "Lunch"
    ],
    "productTags": [
      "Michelin",
      "Contemporary"
    ],
    "why": "★ since 2007; chef Pere Massana — the city's reliable counterpoint to the Rocas. To order: the truffle dishes in season; the à-la-carte classics; the tasting menu. A walkable one-star inside Girona if Can Roca is booked out.",
    "address": "Carrer de Bonastruc de Porta 10, 17001 Girona",
    "phone": "",
    "hours": "Lunch",
    "maps": "https://www.google.com/maps/search/?api=1&query=Restaurant+Massana+Costa+Brava"
  },
  {
    "id": "v06-els-tinars",
    "cat": "shop",
    "tier": "several",
    "priority": 6,
    "badge": "MICHELIN",
    "name": "Els Tinars",
    "short": "Els Tinars",
    "lat": 41.82763,
    "lng": 2.95388,
    "tags": [
      "★; the Gascons family (now Marc Gascons) — elevated Catalan tradition",
      "EUR 70-120",
      "Recommended",
      "Long Sunday lunch"
    ],
    "productTags": [
      "Michelin",
      "Traditional"
    ],
    "why": "★; the Gascons family (now Marc Gascons) — elevated Catalan tradition. To order: the arròs/rice dishes; seasonal game; classic Empordà mar-i-muntanya. The benchmark for \"elevated traditional\" — a country masia, not a lab.",
    "address": "Ctra. de Sant Feliu a Girona (C-65) km 7.2, 17240 Llagostera",
    "phone": "",
    "hours": "Long Sunday lunch",
    "maps": "https://www.google.com/maps/search/?api=1&query=Els+Tinars+Costa+Brava"
  },
  {
    "id": "v07-can-bonay",
    "cat": "shop",
    "tier": "several",
    "priority": 7,
    "badge": "TRADITION",
    "name": "Can Bonay",
    "short": "Can Bonay",
    "lat": 41.97781,
    "lng": 3.08988,
    "tags": [
      "Family restaurant since 1936, in an ancestral stone manor with a small wine cellar/museum",
      "EUR 30-50",
      "Recommended (busy weekends)",
      "Lunch under the arcades"
    ],
    "productTags": [
      "Traditional"
    ],
    "why": "Family restaurant since 1936, in an ancestral stone manor with a small wine cellar/museum. To order: the slow-cooked guisats; canelons; classic Empordà mar-i-muntanya. The archetypal old-village Catalan table — stone walls, linen, slow food. Coordinate is village-centre precision (the medieval core is only ~100 m wide).",
    "address": "Plaça de les Voltes 13, 17113 Peratallada (Forallac)",
    "phone": "",
    "hours": "Lunch under the arcades",
    "maps": "https://www.google.com/maps/search/?api=1&query=Can+Bonay+Costa+Brava"
  },
  {
    "id": "v08-la-gamba",
    "cat": "shop",
    "tier": "several",
    "priority": 8,
    "badge": "TRADITION",
    "name": "La Gamba",
    "short": "La Gamba",
    "lat": 41.84488,
    "lng": 3.12857,
    "tags": [
      "The Cuadrat family since 1967, in a former fish depot — the prawn temple of Palamós",
      "EUR 50-90 (prawns priced by market weight)",
      "Recommended",
      "Lunch overlooking the harbour"
    ],
    "productTags": [
      "Traditional",
      "Fish"
    ],
    "why": "The Cuadrat family since 1967, in a former fish depot — the prawn temple of Palamós. To order: gamba de Palamós (the star, simply grilled); arròs with prawn; whatever's fresh off the auction. Order the Palamós prawn here first, and nowhere else.",
    "address": "Plaça de Sant Pere 1, 17230 Palamós",
    "phone": "",
    "hours": "Lunch overlooking the harbour",
    "maps": "https://www.google.com/maps/search/?api=1&query=La+Gamba+Costa+Brava"
  },
  {
    "id": "v09-cal-tet",
    "cat": "shop",
    "tier": "several",
    "priority": 9,
    "badge": "TRADITION",
    "name": "Cal Tet",
    "short": "Cal Tet",
    "lat": 42.05536,
    "lng": 3.20159,
    "tags": [
      "Long-running family marisqueria/hostal — the go-to for the catch off the Illes Medes",
      "EUR 35-60",
      "Walk-in (Recommended in August)",
      "Lunch"
    ],
    "productTags": [
      "Traditional",
      "Fish"
    ],
    "why": "Long-running family marisqueria/hostal — the go-to for the catch off the Illes Medes. To order: suquet de peix; rice with local fish and shellfish; whole grilled fish of the day. Honest Medes-coast seafood without the resort markup.",
    "address": "Carrer de Santa Anna 38, 17258 L'Estartit (Torroella de Montgrí)",
    "phone": "",
    "hours": "Lunch",
    "maps": "https://www.google.com/maps/search/?api=1&query=Cal+Tet+Costa+Brava"
  },
  {
    "id": "v10-rafa-s",
    "cat": "shop",
    "tier": "plenty",
    "priority": 10,
    "badge": "CULT",
    "name": "Rafa's",
    "short": "Rafa's",
    "lat": 42.26163,
    "lng": 3.17815,
    "tags": [
      "A ~5-table counter beloved by Ferran Adrià and the elBulli crew; no printed menu",
      "EUR 60-100+ (by weight)",
      "Essential (it's tiny; call ahead)",
      "Early lunch; closed parts of the week"
    ],
    "productTags": [
      "Cult",
      "Fish"
    ],
    "why": "A ~5-table counter beloved by Ferran Adrià and the elBulli crew; no printed menu. To order: grilled red prawns of Roses; house anchovies with tomato and toast; espardenyes (sea cucumbers); oysters and clams off the planxa. A pilgrimage for purists — fish, salt, olive oil, nothing else.",
    "address": "Carrer de Sant Sebastià 56, 17480 Roses",
    "phone": "",
    "hours": "Early lunch; closed parts of the week",
    "maps": "https://www.google.com/maps/search/?api=1&query=Rafa's+Costa+Brava"
  },
  {
    "id": "v11-mercat-del-lle",
    "cat": "market",
    "tier": "plenty",
    "priority": 11,
    "badge": "MARKET",
    "name": "Mercat del Lleó",
    "short": "Mercat del Lleó",
    "lat": 41.97915,
    "lng": 2.82255,
    "tags": [
      "Girona's historic covered market (1944), ~60 stalls; where the city's chefs shop",
      "EUR (produce)",
      "Walk-in",
      "Morning, Mon–Sat (closed Sun); arrive before 1:30pm"
    ],
    "productTags": [
      "Market",
      "Produce",
      "Fish"
    ],
    "why": "Girona's historic covered market (1944), ~60 stalls; where the city's chefs shop. To order: seasonal bolets (wild mushrooms); local embotits (botifarra, fuet); Empordà cheeses; Roses and Palamós fish at the stalls. Start any Girona food day here.",
    "address": "Plaça de Francesc Calvet i Rubalcaba, 17002 Girona",
    "phone": "",
    "hours": "Morning, Mon–Sat (closed Sun); arrive before 1:30pm",
    "maps": "https://www.google.com/maps/search/?api=1&query=Mercat+del+Lleó+Costa+Brava"
  },
  {
    "id": "v12-espai-del-peix-llotja-de-palam-s",
    "cat": "market",
    "tier": "plenty",
    "priority": 12,
    "badge": "PRODUCE",
    "name": "Espai del Peix / Llotja de Palamós",
    "short": "Espai del Peix / Llotja ",
    "lat": 41.84454,
    "lng": 3.12712,
    "tags": [
      "Working fish auction; the interpretation centre runs guided auction visits and show-cooking on the same quay",
      "EUR (visit/workshop fee)",
      "Recommended (visits sell out; auction Mon–Fri ~4–8pm)",
      "Late afternoon for the live auction"
    ],
    "productTags": [
      "Fish",
      "Produce",
      "Market"
    ],
    "why": "Working fish auction; the interpretation centre runs guided auction visits and show-cooking on the same quay. To order: book the afternoon auction visit + tasting (the prawn straight off the boats). See the gamba de Palamós sold at the descending Dutch auction before it ever hits a plate.",
    "address": "Edifici de la Llotja, Moll Pesquer s/n, 17230 Palamós",
    "phone": "",
    "hours": "Late afternoon for the live auction",
    "maps": "https://www.google.com/maps/search/?api=1&query=Espai+del+Peix+/+Llotja+de+Palamós+Costa+Brava"
  },
  {
    "id": "v13-anxoves-sol-s",
    "cat": "market",
    "tier": "plenty",
    "priority": 13,
    "badge": "PRODUCE",
    "name": "Anxoves Solés",
    "short": "Anxoves Solés",
    "lat": 42.12597,
    "lng": 3.13366,
    "tags": [
      "L'Escala anchovy house, 1888 lineage, five generations; the heritage name",
      "EUR (jars/tins)",
      "Walk-in",
      "Daytime; pair with a visit to a factory-museum"
    ],
    "productTags": [
      "Produce",
      "Fish"
    ],
    "why": "L'Escala anchovy house, 1888 lineage, five generations; the heritage name. To order: salt-cured anchovy fillets in olive oil; whole salted anchovies; seitons (boquerones). The definitive Empordà larder souvenir; the other historic house, Anxoves de l'Escala, is nearby.",
    "address": "Plaça de la Sardana, 17130 L'Escala",
    "phone": "",
    "hours": "Daytime; pair with a visit to a factory-museum",
    "maps": "https://www.google.com/maps/search/?api=1&query=Anxoves+Solés+Costa+Brava"
  },
  {
    "id": "v14-la-tabarra",
    "cat": "shop",
    "tier": "plenty",
    "priority": 14,
    "badge": "DRINK",
    "name": "La Tabarra",
    "short": "La Tabarra",
    "lat": 41.98567,
    "lng": 2.8253,
    "tags": [
      "Old-Town wine bar with a strong DO Empordà list and a terrace on the medieval Força",
      "EUR 20-40 (wine + plates)",
      "Recommended evenings",
      "Early-evening apéritif on the Força"
    ],
    "productTags": [
      "Drink",
      "Wine"
    ],
    "why": "Old-Town wine bar with a strong DO Empordà list and a terrace on the medieval Força. To order: a flight of DO Empordà reds and whites; the fried-prawn brioche; small plates. The easiest way to drink the Empordà by the glass in the Old Town.",
    "address": "Carrer de la Força 4, 17004 Girona",
    "phone": "",
    "hours": "Early-evening apéritif on the Força",
    "maps": "https://www.google.com/maps/search/?api=1&query=La+Tabarra+Costa+Brava"
  },
  {
    "id": "v15-la-f-brica",
    "cat": "shop",
    "tier": "plenty",
    "priority": 15,
    "badge": "CAFE",
    "name": "La Fábrica",
    "short": "La Fábrica",
    "lat": 41.98393,
    "lng": 2.82595,
    "tags": [
      "Girona's pioneering specialty café, run by a pro cyclist and his wife — the cycling community's clubhouse",
      "EUR 5-18",
      "Walk-in",
      "Morning (opens ~9am); expect a queue"
    ],
    "productTags": [
      "Cafe"
    ],
    "why": "Girona's pioneering specialty café, run by a pro cyclist and his wife — the cycling community's clubhouse. To order: flat white or single-origin filter; the brunch plates (eggs, avocado, local produce). Where Girona's pro-cyclist scene fuels up — the coffee is the real reason.",
    "address": "Carrer de la Llebre 3, 17004 Girona",
    "phone": "",
    "hours": "Morning (opens ~9am); expect a queue",
    "maps": "https://www.google.com/maps/search/?api=1&query=La+Fábrica+Costa+Brava"
  },
  {
    "id": "v16-rocambolesc",
    "cat": "shop",
    "tier": "plenty",
    "priority": 16,
    "badge": "CAFE",
    "name": "Rocambolesc",
    "short": "Rocambolesc",
    "lat": 41.98474,
    "lng": 2.82351,
    "tags": [
      "Jordi Roca's playful gelateria (opened 2012) — the Roca-universe sweet spot you can walk into",
      "EUR 4-8",
      "Walk-in",
      "Afternoon stroll along Santa Clara"
    ],
    "productTags": [
      "Cafe"
    ],
    "why": "Jordi Roca's playful gelateria (opened 2012) — the Roca-universe sweet spot you can walk into. To order: the panet (gelato in brioche); the soft-serve with toppings; seasonal Roca flavours. The most accessible taste of the Roca brothers — no months-ahead booking required.",
    "address": "Carrer de Santa Clara 50, 17001 Girona",
    "phone": "",
    "hours": "Afternoon stroll along Santa Clara",
    "maps": "https://www.google.com/maps/search/?api=1&query=Rocambolesc+Costa+Brava"
  }
];
    const NEIGHBORHOODS = [
  {
    "id": "n-girona",
    "name": "Girona",
    "center": [
      41.98311,
      2.82493
    ],
    "radius": 700,
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Girona+Barri+Vell"
  },
  {
    "id": "n-cadaques",
    "name": "Cadaqués & Portlligat",
    "center": [
      42.28855,
      3.27843
    ],
    "radius": 600,
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Cadaques"
  },
  {
    "id": "n-palafrugell-coves",
    "name": "Calella de Palafrugell & Llafranc",
    "center": [
      41.8918,
      3.1846
    ],
    "radius": 900,
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Calella+de+Palafrugell"
  },
  {
    "id": "n-palamos",
    "name": "Palamós",
    "center": [
      41.8466,
      3.1288
    ],
    "radius": 700,
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Palamos+port"
  },
  {
    "id": "n-lescala",
    "name": "L'Escala & Empúries",
    "center": [
      42.1248,
      3.1324
    ],
    "radius": 1200,
    "maps_url": "https://www.google.com/maps/search/?api=1&query=L'Escala+Empuries"
  },
  {
    "id": "n-roses",
    "name": "Roses",
    "center": [
      42.262,
      3.176
    ],
    "radius": 1000,
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Roses+Girona"
  },
  {
    "id": "n-pals-peratallada",
    "name": "Pals & Peratallada",
    "center": [
      41.9712,
      3.083
    ],
    "radius": 1500,
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Peratallada"
  },
  {
    "id": "n-out-of-town",
    "name": "Out of town — Olot, Garrotxa & Besalú",
    "center": [
      42.199,
      2.699
    ],
    "radius": 6000,
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Besalu"
  }
];
    const WALKS = [
  {
    "id": "w-calella-llafranc",
    "name": "Camí de ronda: Calella → Llafranc",
    "start": [
      41.8884,
      3.1819
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Port+Bo+Calella+de+Palafrugell"
  },
  {
    "id": "w-cadaques",
    "name": "Cadaqués lanes at dawn",
    "start": [
      42.28855,
      3.27843
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Cadaques+old+town"
  },
  {
    "id": "w-cap-de-creus",
    "name": "Cap de Creus to the lighthouse",
    "start": [
      42.319,
      3.317
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Cap+de+Creus+lighthouse"
  },
  {
    "id": "w-empuries",
    "name": "Empúries shore path",
    "start": [
      42.1356,
      3.1226
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Sant+Marti+d'Empuries"
  },
  {
    "id": "w-pals",
    "name": "Pals to the rice paddies",
    "start": [
      41.9709,
      3.1476
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Pals+Girona"
  }
];
    const WORK_SPOTS = [
  {
    "id": "p-work-la-fabrica",
    "name": "La Fábrica, Girona",
    "start": [
      41.98393,
      2.82595
    ]
  },
  {
    "id": "p-work-independencia",
    "name": "Plaça de la Independència, Girona",
    "start": [
      41.98447,
      2.822
    ]
  },
  {
    "id": "p-work-cap-roig",
    "name": "Jardins de Cap Roig",
    "start": [
      41.8815,
      3.1776
    ]
  },
  {
    "id": "p-work-cadaques-riva",
    "name": "Riva of Cadaqués",
    "start": [
      42.2876,
      3.2789
    ]
  }
];
    const LANDMARKS = [
  {
    "id": "l-cap-de-creus",
    "name": "Cap de Creus lighthouse",
    "coords": [
      42.319,
      3.317
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Cap+de+Creus+lighthouse"
  },
  {
    "id": "l-empuries",
    "name": "Ruïnes d'Empúries",
    "coords": [
      42.1342,
      3.1218
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Ruines+Empuries"
  },
  {
    "id": "l-dali-figueres",
    "name": "Teatre-Museu Dalí, Figueres",
    "coords": [
      42.2671,
      2.9596
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Teatre-Museu+Dali+Figueres"
  },
  {
    "id": "l-portlligat",
    "name": "Dalí House, Portlligat",
    "coords": [
      42.2935,
      3.2884
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Salvador+Dali+House+Portlligat"
  },
  {
    "id": "l-sant-pere-rodes",
    "name": "Sant Pere de Rodes",
    "coords": [
      42.3234,
      3.1667
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Sant+Pere+de+Rodes"
  },
  {
    "id": "l-castello",
    "name": "Santa Maria de Castelló d'Empúries",
    "coords": [
      42.2577,
      3.0732
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Santa+Maria+Castello+d'Empuries"
  },
  {
    "id": "l-besalu",
    "name": "Pont Vell de Besalú",
    "coords": [
      42.1984,
      2.6987
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Besalu+Pont+Vell"
  },
  {
    "id": "l-montgri",
    "name": "Montgrí castle",
    "coords": [
      42.0476,
      3.1493
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Castell+del+Montgri"
  }
];
    return { VENUES, COLORS, CAT_LABELS, PRODUCT_COLORS, NEIGHBORHOODS, WALKS, WORK_SPOTS, LANDMARKS };
})();

/* PHOTOS — verified CC images, placed by guide-extras.js */
if (window.TERROIR_DATA) window.TERROIR_DATA.PHOTOS = [{"src": "/terroir/Costa-Brava-Catalunya/img/1-vista.jpg", "caption": "A traditional Catalan lateen-rigged llaut, the Santa Espina, sailing the waters off Calella de Palafrugell with crew aboard and the wooded Sant Sebastia headland behind.", "credit": "Photo: Mdeprada · CC BY-SA 4.0 · Wikimedia"}, {"src": "/terroir/Costa-Brava-Catalunya/img/2-human-food.jpg", "caption": "The corner facade and fish-logo signage of the Anxoves de l'Escala M. Sureda anchovy house, the salted-anchovy industry that l'Escala is famous for.", "credit": "Photo: Jorge Franganillo · CC BY 2.0 · Wikimedia"}, {"src": "/terroir/Costa-Brava-Catalunya/img/3-texture.jpg", "caption": "The fractured, weathered rock strata and garrigue scrub of Cala Jugadora in the Cap de Creus natural park, Catalonia.", "credit": "Photo: Alan Mattingly · CC0 · Wikimedia"}];
