/* Terroir — Barcelona — auto-generated by publish-terroir.py */
window.TERROIR_DATA = (function () {
    const COLORS = { berth:'#c4a35a', market:'#d97706', shop:'#059669', mainland:'#7c3aed', logistics:'#2d4a5e' };
    const CAT_LABELS = { berth:'Signature', market:'Market / Direct', shop:'Restaurant / Bar', mainland:'Out of town', logistics:'Logistics' };
    const PRODUCT_COLORS = {
    'Michelin':'#7f1d1d','Contemporary':'#1f2937','Traditional':'#a16207',
    'Cult':'#7c3aed','Cafe':'#92400e','Wine':'#7c2d12','Bacaro':'#7c3aed',
    'Drink':'#0ea5e9','Street Food':'#dc2626','Market':'#d97706',
    'Produce':'#15803d','Fish':'#3b82f6','Meat':'#b91c1c',
    'Cheese':'#eab308','Bread':'#a16207','Charcuterie':'#9d174d',
    'Hi-Fi':'#1f2937'
};
    const VENUES = [
  {
    "id": "v01-disfrutar",
    "cat": "shop",
    "tier": "berth_top",
    "priority": 1,
    "badge": "MICHELIN",
    "name": "Disfrutar",
    "short": "Disfrutar",
    "lat": 41.38781,
    "lng": 2.15315,
    "tags": [
      "★★★ since 2024 · World's 50 Best #1 in 2024 · Michelin Green Star",
      "EUR 315 menu (pairing +150–200)",
      "Essential — book 10–12 months ahead",
      "Dinner Tue–Sat"
    ],
    "productTags": [
      "Michelin",
      "Contemporary"
    ],
    "why": "★★★ since 2024 · World's 50 Best #1 in 2024 · Michelin Green Star. To order: the tasting menu only — 30+ courses of textural illusions, ferments, and Mediterranean reinvention. Xatruch + Castro + Casañas, all senior elBulli alumni. The hardest table in Spain. Closed Sun–Mon. The 'false dishes' (one thing tastes of another) are the signature trick.",
    "address": "Carrer de Villarroel 163, 08036 Barcelona",
    "phone": "+34 933 48 68 96",
    "hours": "Dinner Tue–Sat",
    "maps": "https://www.google.com/maps/search/?api=1&query=Disfrutar+Barcelona"
  },
  {
    "id": "v02-lasarte",
    "cat": "shop",
    "tier": "berth_top",
    "priority": 2,
    "badge": "MICHELIN",
    "name": "Lasarte",
    "short": "Lasarte",
    "lat": 41.39406,
    "lng": 2.15934,
    "tags": [
      "★★★ (Martín Berasategui's Barcelona satellite under Paolo Casagrande)",
      "EUR 345 dinner / EUR 225 lunch",
      "Essential, weeks ahead, dress code",
      "Weekday lunch"
    ],
    "productTags": [
      "Michelin",
      "Contemporary"
    ],
    "why": "★★★ (Martín Berasategui's Barcelona satellite under Paolo Casagrande). To order: the dinner tasting; or the weekday lunch (€225) — better value, same kitchen. Inside the 5GL Monument Hotel. The 'Il Milione' private counter (8 seats, kitchen-front) is bookable separately. Berasategui himself doesn't cook here — Casagrande does.",
    "address": "Carrer de Mallorca 259 (Monument Hotel), 08008 Barcelona",
    "phone": "+34 934 45 32 42",
    "hours": "Weekday lunch",
    "maps": "https://www.google.com/maps/search/?api=1&query=Lasarte+Barcelona"
  },
  {
    "id": "v03-enigma",
    "cat": "shop",
    "tier": "berth_top",
    "priority": 3,
    "badge": "MICHELIN",
    "name": "Enigma",
    "short": "Enigma",
    "lat": 41.38187,
    "lng": 2.15509,
    "tags": [
      "★★ (promoted from ★ in November 2025 — the news of the 2026 guide)",
      "EUR 280 menu",
      "Wed–Fri eves only, book via enigmaconcept.es",
      "Wednesday evening"
    ],
    "productTags": [
      "Michelin",
      "Cult"
    ],
    "why": "★★ (promoted from ★ in November 2025 — the news of the 2026 guide). To order: the 25-course tasting; dishes are not named until after you eat them. Albert Adrià — Ferran's brother, the elBarri group founder. Bodega 1900, Tickets, Pakta, Hoja Santa all closed in 2020; Enigma was the sole survivor. Now promoted to ★★ and the elBulli legacy lives most directly here.",
    "address": "Carrer de Sepúlveda 38–40, 08015 Barcelona",
    "phone": "+34 616 69 63 22",
    "hours": "Wednesday evening",
    "maps": "https://www.google.com/maps/search/?api=1&query=Enigma+Barcelona"
  },
  {
    "id": "v04-cocina-hermanos-torres",
    "cat": "shop",
    "tier": "several",
    "priority": 4,
    "badge": "MICHELIN",
    "name": "Cocina Hermanos Torres",
    "short": "Cocina Hermanos Torres",
    "lat": 41.38348,
    "lng": 2.13441,
    "tags": [
      "★★★ + Michelin Green Star — the only triple-star in Barcelona with the sustainability award",
      "EUR 310 menu",
      "Essential, months ahead — phone Mon–Fri 10–12 / 18–20",
      "Dinner"
    ],
    "productTags": [
      "Michelin",
      "Cult"
    ],
    "why": "★★★ + Michelin Green Star — the only triple-star in Barcelona with the sustainability award. To order: the theatrical tasting menu — three open cooking stations in the centre of the converted industrial space, you eat surrounded by the kitchen. Sergio + Javier Torres. Single most photogenic dining room of any starred restaurant in the city. The artichoke with truffle is canonical.",
    "address": "Carrer del Taquígraf Serra 20, 08029 Barcelona",
    "phone": "+34 934 10 00 20",
    "hours": "Dinner",
    "maps": "https://www.google.com/maps/search/?api=1&query=Cocina+Hermanos+Torres+Barcelona"
  },
  {
    "id": "v05-mont-bar",
    "cat": "shop",
    "tier": "several",
    "priority": 5,
    "badge": "MICHELIN",
    "name": "Mont Bar",
    "short": "Mont Bar",
    "lat": 41.38617,
    "lng": 2.15631,
    "tags": [
      "★★ (promoted from ★ in November 2025 — most discussed promotion of the 2026 guide)",
      "EUR 190–240",
      "Essential — counter seats are kitchen-front",
      "Dinner"
    ],
    "productTags": [
      "Michelin",
      "Contemporary"
    ],
    "why": "★★ (promoted from ★ in November 2025 — most discussed promotion of the 2026 guide). To order: sobrasada and Mahón cheese mochi; the sea-cucumber 'carbonara'; the creative pintxo opening series. Chef Fran Agudo, ex-Tickets (elBarri). The gastrobar format reaches ★★ — a Barcelona statement.",
    "address": "Carrer de la Diputació 220, 08011 Barcelona",
    "phone": "+34 933 23 95 90",
    "hours": "Dinner",
    "maps": "https://www.google.com/maps/search/?api=1&query=Mont+Bar+Barcelona"
  },
  {
    "id": "v06-aleia",
    "cat": "shop",
    "tier": "several",
    "priority": 6,
    "badge": "MICHELIN",
    "name": "Aleia",
    "short": "Aleia",
    "lat": 41.40275,
    "lng": 2.15474,
    "tags": [
      "★★ (promoted from ★ in November 2025)",
      "EUR 200 menu",
      "Via hotel or TheFork",
      "Dinner"
    ],
    "productTags": [
      "Michelin",
      "Contemporary"
    ],
    "why": "★★ (promoted from ★ in November 2025). To order: the ingredient-led seasonal tasting — pared-back plates that let produce speak. Chefs Paulo Airaudo (Italo-Argentine) + Rafa de Bedoya (Jerez). Inside Hotel Casa Fuster, a 1908 Domènech i Montaner Modernista building.",
    "address": "Passeig de Gràcia 132, 08008 Barcelona",
    "phone": "+34 932 55 30 00",
    "hours": "Dinner",
    "maps": "https://www.google.com/maps/search/?api=1&query=Aleia+Barcelona"
  },
  {
    "id": "v07-bar-ca-ete",
    "cat": "shop",
    "tier": "several",
    "priority": 7,
    "badge": "CONTEMPOR",
    "name": "Bar Cañete",
    "short": "Bar Cañete",
    "lat": 41.38019,
    "lng": 2.17245,
    "tags": [
      "Michelin recommended — the canonical Raval table",
      "EUR 35–55",
      "Essential at dinner; counter seats for the kitchen view",
      "Lunch Thu–Sat"
    ],
    "productTags": [
      "Contemporary",
      "Traditional"
    ],
    "why": "Michelin recommended — the canonical Raval table. To order: anchoas de Santoña (Cantabrian anchovies), gamba de Palamós (the great prawn — €19–22), fideuà Cañete, the pa amb tomàquet. Two blocks from the Liceu. The ringside counter is the best seat. Tapas €5–20 each.",
    "address": "Carrer de la Unió 17, 08001 Barcelona",
    "phone": "+34 932 70 34 58",
    "hours": "Lunch Thu–Sat",
    "maps": "https://www.google.com/maps/search/?api=1&query=Bar+Cañete+Barcelona"
  },
  {
    "id": "v08-cinc-sentits",
    "cat": "shop",
    "tier": "several",
    "priority": 8,
    "badge": "CONTEMPOR",
    "name": "Cinc Sentits",
    "short": "Cinc Sentits",
    "lat": 41.38408,
    "lng": 2.15467,
    "tags": [
      "★ — small-producer Catalan",
      "EUR 185–219",
      "Book 3–4 weeks ahead at cincsentits.com",
      "Dinner"
    ],
    "productTags": [
      "Michelin",
      "Contemporary"
    ],
    "why": "★ — small-producer Catalan. To order: the Tasting (longer) or Essence (shorter) menu — pa amb tomàquet sequence, Penedès wine pairing. Jordi Artal, Canadian-Catalan, self-taught. The relationships with small Catalan producers (cheese, oil, vegetables) are the spine.",
    "address": "Carrer d'Entença 60, 08015 Barcelona",
    "phone": "+34 933 23 94 90",
    "hours": "Dinner",
    "maps": "https://www.google.com/maps/search/?api=1&query=Cinc+Sentits+Barcelona"
  },
  {
    "id": "v09-can-culleretes",
    "cat": "shop",
    "tier": "several",
    "priority": 9,
    "badge": "TRADITION",
    "name": "Can Culleretes",
    "short": "Can Culleretes",
    "lat": 41.38147,
    "lng": 2.17462,
    "tags": [
      "Founded 1786 — oldest restaurant in Catalonia, second oldest in Spain (Guinness-recognised)",
      "EUR 25–35 / menu del dia EUR 15–18",
      "Recommended weekends",
      "Lunch Tue–Sun"
    ],
    "productTags": [
      "Traditional"
    ],
    "why": "Founded 1786 — oldest restaurant in Catalonia, second oldest in Spain (Guinness-recognised). To order: escudella i carn d'olla (the ur-Catalan meat-and-veg stew), botifarra amb mongetes, canelons d'espinacs amb brandada de bacallà, civet de porc senglar, crema catalana. Agut Manubens family, continuously since 1786. Bib Gourmand 2026. Closed Monday.",
    "address": "Carrer de Quintana 5, 08002 Barcelona",
    "phone": "+34 933 17 30 22",
    "hours": "Lunch Tue–Sun",
    "maps": "https://www.google.com/maps/search/?api=1&query=Can+Culleretes+Barcelona"
  },
  {
    "id": "v10-7-portes-set-portes",
    "cat": "shop",
    "tier": "several",
    "priority": 10,
    "badge": "TRADITION",
    "name": "7 Portes (Set Portes)",
    "short": "7 Portes (Set Portes)",
    "lat": 41.38273,
    "lng": 2.18293,
    "tags": [
      "Since 1836 — the paella institution; the Paella Parellada was invented here",
      "EUR 40",
      "Via 7portes.com",
      "Dinner — the piano sets"
    ],
    "productTags": [
      "Traditional"
    ],
    "why": "Since 1836 — the paella institution; the Paella Parellada was invented here. To order: Paella Parellada (boneless meat + shellfish, the house classic), arròs amb llagosta, fideuà, suquet de peix. Daily 13:00–01:00 (continuous service). The 19th-century vaulted dining room with name-plates of historic patrons is the experience.",
    "address": "Passeig d'Isabel II 14, 08003 Barcelona",
    "phone": "+34 933 19 30 33",
    "hours": "Dinner — the piano sets",
    "maps": "https://www.google.com/maps/search/?api=1&query=7+Portes+(Set+Portes)+Barcelona"
  },
  {
    "id": "v11-quimet-quimet",
    "cat": "shop",
    "tier": "several",
    "priority": 11,
    "badge": "TRADITION",
    "name": "Quimet & Quimet",
    "short": "Quimet & Quimet",
    "lat": 41.37659,
    "lng": 2.16427,
    "tags": [
      "Founded 1914, fifth-generation Quimet — standing only, tiny, magnificent",
      "EUR 3–5 / montadito · EUR 20–30 standing",
      "Walk-in only — no reservations",
      "Open 12:00–16:00 + 18:00–22:30 Mon–Fri; 12:00–16:00 Sat; closed Sun"
    ],
    "productTags": [
      "Traditional",
      "Bacaro"
    ],
    "why": "Founded 1914, fifth-generation Quimet — standing only, tiny, magnificent. To order: montaditos (small open-faced bites on bread — truffled sturgeon roe, smoked salmon with caviar cream, boquerón with anchovy cream); cava or vermut by the glass. Arrive at opening or wait. Cult tinned-seafood selection on the back wall. Cash and card both.",
    "address": "Carrer del Poeta Cabanyes 25, 08004 Barcelona",
    "phone": "+34 934 42 31 42",
    "hours": "Open 12:00–16:00 + 18:00–22:30 Mon–Fri; 12:00–16:00 Sat; closed Sun",
    "maps": "https://www.google.com/maps/search/?api=1&query=Quimet+&+Quimet+Barcelona"
  },
  {
    "id": "v12-la-cova-fumada",
    "cat": "shop",
    "tier": "several",
    "priority": 12,
    "badge": "CULT",
    "name": "La Cova Fumada",
    "short": "La Cova Fumada",
    "lat": 41.37969,
    "lng": 2.1879,
    "tags": [
      "Cash-only, no sign — where la bomba was invented (Civil War era)",
      "EUR 15–25 · bomba EUR 3–4",
      "Walk-in only — no reservations, no phone bookings",
      "Mon–Fri 09:00–15:30, Sat 09:00–14:30; closed Sun"
    ],
    "productTags": [
      "Cult",
      "Traditional"
    ],
    "why": "Cash-only, no sign — where la bomba was invented (Civil War era). To order: la bomba (fried potato sphere holding seasoned meat, paprika dust, allioli + brava sauces), grilled sardines, clams, sepia. Family-run on a Barceloneta corner since 1944. Cash only. OAD Casual Europe #81 (2025). The bomba in any other bar is a copy of this one.",
    "address": "Carrer del Baluard 56, 08003 Barcelona",
    "phone": "+34 932 21 40 61",
    "hours": "Mon–Fri 09:00–15:30, Sat 09:00–14:30; closed Sun",
    "maps": "https://www.google.com/maps/search/?api=1&query=La+Cova+Fumada+Barcelona"
  },
  {
    "id": "v13-el-xampanyet",
    "cat": "shop",
    "tier": "several",
    "priority": 13,
    "badge": "DRINK",
    "name": "El Xampanyet",
    "short": "El Xampanyet",
    "lat": 41.38491,
    "lng": 2.18058,
    "tags": [
      "Cava and anchovy bar since 1929 — three generations of the Esteve family, on the Picasso Museum street",
      "EUR 2–4 / glass · EUR 15–25 head",
      "Walk-in",
      "Lunch / pre-dinner aperitif"
    ],
    "productTags": [
      "Wine",
      "Bacaro"
    ],
    "why": "Cava and anchovy bar since 1929 — three generations of the Esteve family, on the Picasso Museum street. To order: the house cava (lightly sweet, ceramic jug); anchovies from L'Escala; the montaditos; pa amb tomàquet. Narrow tile-decorated tavern. Tourist-known but genuinely excellent — the locals come earlier. Closed Sun + Mon.",
    "address": "Carrer de Montcada 22, 08003 Barcelona",
    "phone": "+34 933 19 70 03",
    "hours": "Lunch / pre-dinner aperitif",
    "maps": "https://www.google.com/maps/search/?api=1&query=El+Xampanyet+Barcelona"
  },
  {
    "id": "v14-els-pescadors",
    "cat": "shop",
    "tier": "plenty",
    "priority": 14,
    "badge": "TRADITION",
    "name": "Els Pescadors",
    "short": "Els Pescadors",
    "lat": 41.40235,
    "lng": 2.21078,
    "tags": [
      "The Poblenou seafood benchmark — suquet de peix with authority",
      "EUR 45–65",
      "Essential weekends, via elspescadors.com",
      "Lunch on the terrace of the old square"
    ],
    "productTags": [
      "Traditional"
    ],
    "why": "The Poblenou seafood benchmark — suquet de peix with authority. To order: suquet de peix (the fisherman's stew, definitive version), fideuà negra (squid-ink noodles), arròs a banda, fresh grilled catch of the day. Plaça de Prim is the old fishing-village square of Poblenou. The terrace is the reason.",
    "address": "Plaça de Prim 1, 08005 Barcelona",
    "phone": "+34 932 25 20 18",
    "hours": "Lunch on the terrace of the old square",
    "maps": "https://www.google.com/maps/search/?api=1&query=Els+Pescadors+Barcelona"
  },
  {
    "id": "v15-suculent",
    "cat": "shop",
    "tier": "plenty",
    "priority": 15,
    "badge": "CONTEMPOR",
    "name": "Suculent",
    "short": "Suculent",
    "lat": 41.37876,
    "lng": 2.16847,
    "tags": [
      "Michelin recommended — the elBulli-trained reading of Catalan classics",
      "EUR 55–80",
      "Via suculent.com",
      "Dinner"
    ],
    "productTags": [
      "Contemporary",
      "Traditional"
    ],
    "why": "Michelin recommended — the elBulli-trained reading of Catalan classics. To order: the 'Los Clásicos' or 'Suculent' sharing menu — reimagined Spanish-Mediterranean classics; octopus, brava, slow-cooked meats. Chef Toni Romero (elBulli alumni). Casual format, serious cooking.",
    "address": "Rambla del Raval 43, 08001 Barcelona",
    "phone": "+34 934 43 65 79",
    "hours": "Dinner",
    "maps": "https://www.google.com/maps/search/?api=1&query=Suculent+Barcelona"
  },
  {
    "id": "v16-mercat-de-la-boqueria",
    "cat": "market",
    "tier": "plenty",
    "priority": 16,
    "badge": "MARKET",
    "name": "Mercat de la Boqueria",
    "short": "Mercat de la Boqueria",
    "lat": 41.38157,
    "lng": 2.17158,
    "tags": [
      "Founded 1840 on the site of the former Convent of Sant Josep — Barcelona's flagship market",
      "EUR variable · the bar counters EUR 12–25",
      "Walk-in",
      "Tue–Sat morning 08:00–11:00 (avoid the lunchtime tourist crush)"
    ],
    "productTags": [
      "Market",
      "Produce"
    ],
    "why": "Founded 1840 on the site of the former Convent of Sant Josep — Barcelona's flagship market. To order: the back rows (Pinotxo Bar, Bar Central — locals eat here), jamón ibérico bellota, Catalan goat cheeses, salt-cured anchovies, fresh figs and tomatoes in season. Closed Sunday. The front-row stalls near La Rambla are tourist-oriented; the real market is at the back.",
    "address": "La Rambla 91, 08001 Barcelona",
    "phone": "+34 934 13 23 03",
    "hours": "Tue–Sat morning 08:00–11:00 (avoid the lunchtime tourist crush)",
    "maps": "https://www.google.com/maps/search/?api=1&query=Mercat+de+la+Boqueria+Barcelona"
  },
  {
    "id": "v17-mercat-de-sant-antoni",
    "cat": "market",
    "tier": "plenty",
    "priority": 17,
    "badge": "MARKET",
    "name": "Mercat de Sant Antoni",
    "short": "Mercat de Sant Antoni",
    "lat": 41.3795,
    "lng": 2.16282,
    "tags": [
      "1882 iron market by Antoni Rovira i Trias — reopened in 2018 after eight years of restoration",
      "EUR variable",
      "Walk-in",
      "Sunday morning for the books; Tue–Sat for fresh produce"
    ],
    "productTags": [
      "Market",
      "Produce"
    ],
    "why": "1882 iron market by Antoni Rovira i Trias — reopened in 2018 after eight years of restoration. To order: the Sunday morning book + collectibles market on the perimeter; the produce inside (Tue–Sat); after-market vermut at Bar Calders one block south. The Sant Antoni vermut neighborhood orbits this market.",
    "address": "Carrer del Comte d'Urgell 1, 08011 Barcelona",
    "phone": "",
    "hours": "Sunday morning for the books; Tue–Sat for fresh produce",
    "maps": "https://www.google.com/maps/search/?api=1&query=Mercat+de+Sant+Antoni+Barcelona"
  },
  {
    "id": "v18-codorn-u",
    "cat": "shop",
    "tier": "plenty",
    "priority": 18,
    "badge": "CULT",
    "name": "Codorníu",
    "short": "Codorníu",
    "lat": 41.43133,
    "lng": 1.78283,
    "tags": [
      "Founded 1551 · birthplace of Cava (1872, Josep Raventós i Fatjó) · cellars by Puig i Cadafalch 1895–1921, Spanish National Monument 1976",
      "EUR 17–35 / visit",
      "Book ahead at codorniu.com — slots fill weekends",
      "Morning tour"
    ],
    "productTags": [
      "Wine"
    ],
    "why": "Founded 1551 · birthplace of Cava (1872, Josep Raventós i Fatjó) · cellars by Puig i Cadafalch 1895–1921, Spanish National Monument 1976. To order: the cellar tour through 27 km of underground galleries; tasting of Cava de Paraje Calificado (El Tros Nou, La Pleta, La Fideuera) and the Anna de Codorníu range. Modernista brick architecture, ribbed cellars, a 27-km labyrinth on three levels. The R4 Renfe from Sants takes 45 minutes. Pair with Recaredo or Gramona by appointment.",
    "address": "Avinguda Jaume Codorníu s/n, 08770 Sant Sadurní d'Anoia",
    "phone": "+34 938 91 33 42",
    "hours": "Morning tour",
    "maps": "https://www.google.com/maps/search/?api=1&query=Codorníu+Barcelona"
  }
];
    const NEIGHBORHOODS = [
  {
    "id": "n-barri-gotic",
    "name": "Barri Gòtic",
    "center": [
      41.3826,
      2.17604
    ],
    "radius": 280,
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Barri+Gotic+Barcelona"
  },
  {
    "id": "n-born",
    "name": "El Born / La Ribera",
    "center": [
      41.38463,
      2.18147
    ],
    "radius": 260,
    "maps_url": "https://www.google.com/maps/search/?api=1&query=El+Born+Barcelona"
  },
  {
    "id": "n-raval",
    "name": "El Raval",
    "center": [
      41.38005,
      2.17033
    ],
    "radius": 380,
    "maps_url": "https://www.google.com/maps/search/?api=1&query=El+Raval+Barcelona"
  },
  {
    "id": "n-eixample",
    "name": "L'Eixample (Quadrat d'Or)",
    "center": [
      41.39391,
      2.1637
    ],
    "radius": 600,
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Quadrat+d+Or+Eixample"
  },
  {
    "id": "n-gracia",
    "name": "Gràcia",
    "center": [
      41.40175,
      2.1576
    ],
    "radius": 500,
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Gracia+Barcelona"
  },
  {
    "id": "n-sant-antoni",
    "name": "Sant Antoni",
    "center": [
      41.37987,
      2.16285
    ],
    "radius": 380,
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Sant+Antoni+Barcelona"
  },
  {
    "id": "n-poble-sec",
    "name": "Poble Sec",
    "center": [
      41.3751,
      2.1664
    ],
    "radius": 400,
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Poble+Sec+Barcelona"
  },
  {
    "id": "n-barceloneta",
    "name": "Barceloneta",
    "center": [
      41.38001,
      2.18937
    ],
    "radius": 380,
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Barceloneta+Barcelona"
  },
  {
    "id": "n-poblenou",
    "name": "Poblenou & 22@",
    "center": [
      41.40158,
      2.2006
    ],
    "radius": 700,
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Poblenou+Barcelona"
  },
  {
    "id": "n-montjuic",
    "name": "Montjuïc",
    "center": [
      41.36383,
      2.15838
    ],
    "radius": 900,
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Montjuic+Barcelona"
  },
  {
    "id": "n-out-of-town",
    "name": "Out of town — Sant Sadurní / Priorat / Sitges",
    "center": [
      41.3,
      1.8
    ],
    "radius": 3000,
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Sant+Sadurni+d+Anoia"
  }
];
    const WALKS = [
  {
    "id": "p-walk-gotic-dawn",
    "name": "Gothic Quarter at dawn",
    "start": [
      41.38,
      2.175
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Plaça+Reial+Barcelona"
  },
  {
    "id": "p-walk-modernisme",
    "name": "Passeig de Gràcia Modernisme strip",
    "start": [
      41.39163,
      2.16518
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Passeig+de+Gracia+Casa+Batllo"
  },
  {
    "id": "p-walk-park-guell",
    "name": "Park Güell from the back",
    "start": [
      41.41449,
      2.15268
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Park+Guell+Carrer+del+Carmel"
  },
  {
    "id": "p-walk-tres-tombs",
    "name": "Sant Antoni → Raval → Boqueria",
    "start": [
      41.3795,
      2.16282
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Mercat+de+Sant+Antoni"
  },
  {
    "id": "p-walk-blai-pintxos",
    "name": "Carrer de Blai pintxos crawl",
    "start": [
      41.37454,
      2.16557
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Carrer+de+Blai+Barcelona"
  },
  {
    "id": "p-walk-sant-sadurni",
    "name": "Sant Sadurní d'Anoia Cava day-trip",
    "start": [
      41.425,
      1.787
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Sant+Sadurni+d+Anoia+Cava"
  },
  {
    "id": "p-walk-montjuic",
    "name": "Montjuïc heritage loop (MNAC + Miró)",
    "start": [
      41.36869,
      2.15364
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=MNAC+Barcelona"
  }
];
    const WORK_SPOTS = [
  {
    "id": "p-work-jardim-bivar",
    "name": "Plaça Reial terrace",
    "start": [
      41.38033,
      2.17506
    ]
  },
  {
    "id": "p-work-cafe-mauri",
    "name": "Cafè Mauri (Rambla Catalunya 102)",
    "start": [
      41.39555,
      2.16178
    ]
  },
  {
    "id": "p-work-cccb",
    "name": "CCCB courtyard café (Raval)",
    "start": [
      41.38301,
      2.16798
    ]
  },
  {
    "id": "p-work-mnac-terrace",
    "name": "MNAC terrace (Montjuïc)",
    "start": [
      41.36869,
      2.15364
    ]
  },
  {
    "id": "p-work-park-bouzaise",
    "name": "Plaça de la Virreina (Gràcia)",
    "start": [
      41.40451,
      2.1581
    ]
  }
];
    const LANDMARKS = [
  {
    "id": "l-sagrada-familia",
    "name": "Sagrada Família",
    "coords": [
      41.40361,
      2.17436
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Sagrada+Familia"
  },
  {
    "id": "l-park-guell",
    "name": "Park Güell",
    "coords": [
      41.41449,
      2.15268
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Park+Guell"
  },
  {
    "id": "l-casa-batllo",
    "name": "Casa Batlló",
    "coords": [
      41.39163,
      2.16518
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Casa+Batllo"
  },
  {
    "id": "l-pedrera",
    "name": "Casa Milà / La Pedrera",
    "coords": [
      41.39536,
      2.16168
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=La+Pedrera"
  },
  {
    "id": "l-temple-augustus",
    "name": "Temple of Augustus columns",
    "coords": [
      41.38292,
      2.17661
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Temple+of+Augustus+Barcelona"
  },
  {
    "id": "l-catedral",
    "name": "Catedral de Barcelona",
    "coords": [
      41.38379,
      2.17616
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Catedral+de+Barcelona"
  },
  {
    "id": "l-palau-musica",
    "name": "Palau de la Música Catalana",
    "coords": [
      41.38731,
      2.17499
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Palau+de+la+Musica+Catalana"
  },
  {
    "id": "l-boqueria",
    "name": "Mercat de la Boqueria",
    "coords": [
      41.38157,
      2.17158
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Mercat+de+la+Boqueria"
  }
];
    return { VENUES, COLORS, CAT_LABELS, PRODUCT_COLORS, NEIGHBORHOODS, WALKS, WORK_SPOTS, LANDMARKS };
})();
