/* Terroir — Beaune — auto-generated by publish-terroir.py */
window.TERROIR_DATA = (function () {
    const COLORS = { berth:'#c4a35a', market:'#d97706', shop:'#059669', mainland:'#7c3aed', logistics:'#2d4a5e' };
    const CAT_LABELS = { berth:'Signature', market:'Market / Direct', shop:'Restaurant / Bar', mainland:'Out of town', logistics:'Logistics' };
    const PRODUCT_COLORS = {
    'Michelin':'#7f1d1d','Contemporary':'#1f2937','Traditional':'#a16207',
    'Cult':'#7c3aed','Cafe':'#92400e','Wine':'#7c2d12','Bacaro':'#7c3aed',
    'Drink':'#0ea5e9','Street Food':'#dc2626','Market':'#d97706',
    'Produce':'#15803d','Fish':'#3b82f6','Meat':'#b91c1c',
    'Cheese':'#eab308','Bread':'#a16207','Charcuterie':'#9d174d',
    'Hi-Fi':'#1f2937'
};
    const VENUES = [
  {
    "id": "v01-le-carmin",
    "cat": "shop",
    "tier": "berth_top",
    "priority": 1,
    "badge": "MICHELIN",
    "name": "Le Carmin",
    "short": "Le Carmin",
    "lat": 47.0234,
    "lng": 4.8388,
    "tags": [
      "Michelin one star (held 2025 and 2026)",
      "EUR 50 lunch / EUR 118-178 menu",
      "Essential",
      "Lunch"
    ],
    "productTags": [
      "Michelin",
      "Contemporary"
    ],
    "why": "Michelin one star (held 2025 and 2026). To order: the market tasting menu — the kitchen does not run a fixed signature; lunch 50–59 €, dinner menus 118 / 148 / 178 €. Chef Christophe Quéant, trained with Robuchon and Ducasse. An Henri-IV house on the central square, the menu rotating strictly with the market. Closed Sun, Mon, Tue lunch.",
    "address": "4B Place Carnot, 21200 Beaune",
    "phone": "",
    "hours": "Lunch",
    "maps": "https://www.google.com/maps/search/?api=1&query=Le+Carmin+Beaune"
  },
  {
    "id": "v02-clos-du-c-dre",
    "cat": "shop",
    "tier": "berth_top",
    "priority": 2,
    "badge": "MICHELIN",
    "name": "Clos du Cèdre",
    "short": "Clos du Cèdre",
    "lat": 47.0256,
    "lng": 4.8373,
    "tags": [
      "Michelin one star (awarded 2022, held 2025 and 2026)",
      "EUR 90-160 menu (verify)",
      "Essential",
      "Dinner"
    ],
    "productTags": [
      "Michelin",
      "Contemporary"
    ],
    "why": "Michelin one star (awarded 2022, held 2025 and 2026). To order: the seasonal tasting menu — terroir-anchored Burgundian, a wine list past 1,000 references. Chef Jordan Billan, inside the Hostellerie Cèdre & Spa under the great cedar that names it. Lunch Sat–Sun only; dinner Wed–Sun. Smart dress.",
    "address": "10-12 Boulevard Maréchal-Foch, 21200 Beaune",
    "phone": "",
    "hours": "Dinner",
    "maps": "https://www.google.com/maps/search/?api=1&query=Clos+du+Cèdre+Beaune"
  },
  {
    "id": "v03-ma-cuisine",
    "cat": "shop",
    "tier": "berth_top",
    "priority": 3,
    "badge": "TRADITION",
    "name": "Ma Cuisine",
    "short": "Ma Cuisine",
    "lat": 47.0223,
    "lng": 4.8387,
    "tags": [
      "The reference Burgundian table in Beaune, since 1996",
      "EUR 30-40 mains",
      "Recommended",
      "Dinner"
    ],
    "productTags": [
      "Traditional",
      "Wine"
    ],
    "why": "The reference Burgundian table in Beaune, since 1996. To order: escargots à la bourguignonne, bœuf bourguignon, roast pigeon — à la carte only, no set menu. A discreet table down a passage, beloved for its cellar — the wine list opens around 50 € and runs very deep. Reopened February 2026 under chef Mathieu Escoffier. Dinner only, closed Sunday.",
    "address": "Passage Sainte-Hélène, 21200 Beaune",
    "phone": "",
    "hours": "Dinner",
    "maps": "https://www.google.com/maps/search/?api=1&query=Ma+Cuisine+Beaune"
  },
  {
    "id": "v04-bissoh",
    "cat": "shop",
    "tier": "several",
    "priority": 4,
    "badge": "CONTEMPOR",
    "name": "Bissoh",
    "short": "Bissoh",
    "lat": 47.0218,
    "lng": 4.8376,
    "tags": [
      "The Japanese-Burgundian counter — sumibi-yaki on binchotan charcoal",
      "EUR 60-110",
      "Essential",
      "Dinner"
    ],
    "productTags": [
      "Contemporary"
    ],
    "why": "The Japanese-Burgundian counter — sumibi-yaki on binchotan charcoal. To order: aged Limousin and Miyazaki beef from the charcoal grill; the omakase counter. Chef Mikihiko Sawahata cooks in front of ten seats. A very large French wine list behind a Japanese grill. Wed–Sun dinner; closed Mon–Tue.",
    "address": "42 Rue Maufoux, 21200 Beaune",
    "phone": "+33 3 80 24 01 02",
    "hours": "Dinner",
    "maps": "https://www.google.com/maps/search/?api=1&query=Bissoh+Beaune"
  },
  {
    "id": "v05-le-bistro-de-l-h-tel",
    "cat": "shop",
    "tier": "several",
    "priority": 5,
    "badge": "CONTEMPOR",
    "name": "Le Bistro de l'Hôtel",
    "short": "Le Bistro de l'Hôtel",
    "lat": 47.0224,
    "lng": 4.8383,
    "tags": [
      "House table of the five-star Hôtel le Cep",
      "EUR 45-90",
      "Recommended",
      "Dinner"
    ],
    "productTags": [
      "Contemporary",
      "Traditional"
    ],
    "why": "House table of the five-star Hôtel le Cep. To order: whole roast poularde de Bresse for two; Charolais côte de bœuf. A small panelled room doing one thing supremely — the whole Bresse hen, carved at the table. The address for poultry without driving to the Bresse.",
    "address": "Rue Maufoux, 21200 Beaune",
    "phone": "+33 3 80 25 94 10",
    "hours": "Dinner",
    "maps": "https://www.google.com/maps/search/?api=1&query=Le+Bistro+de+l'Hôtel+Beaune"
  },
  {
    "id": "v06-caves-madeleine",
    "cat": "shop",
    "tier": "several",
    "priority": 6,
    "badge": "TRADITION",
    "name": "Caves Madeleine",
    "short": "Caves Madeleine",
    "lat": 47.0211,
    "lng": 4.8418,
    "tags": [
      "Bistrot with the bones of a wine cellar — shared tables",
      "EUR 22-34 mains",
      "Recommended",
      "Dinner"
    ],
    "productTags": [
      "Traditional",
      "Wine"
    ],
    "why": "Bistrot with the bones of a wine cellar — shared tables. To order: hanger-steak tartare with hazelnut and Parmesan; the producer-sourced plat du jour. Long communal tables, wine bought off the shelf at retail-plus, kitchen that cooks with real punch. Closed Wed and Sun.",
    "address": "8 Rue du Faubourg-Madeleine, 21200 Beaune",
    "phone": "+33 3 80 22 93 30",
    "hours": "Dinner",
    "maps": "https://www.google.com/maps/search/?api=1&query=Caves+Madeleine+Beaune"
  },
  {
    "id": "v07-le-bistrot-bourguignon",
    "cat": "shop",
    "tier": "several",
    "priority": 7,
    "badge": "TRADITION",
    "name": "Le Bistrot Bourguignon",
    "short": "Le Bistrot Bourguignon",
    "lat": 47.0225,
    "lng": 4.8377,
    "tags": [
      "The honest Burgundian bouchon — Menu Bourguignon 33 €",
      "EUR 33 menu",
      "Recommended",
      "Lunch"
    ],
    "productTags": [
      "Traditional",
      "Wine"
    ],
    "why": "The honest Burgundian bouchon — Menu Bourguignon 33 €. To order: œufs en meurette, bœuf bourguignon, andouillette sauce moutarde, entrecôte sauce Époisses. Chef Mickael Thibert; a wine list past 500 references in a small room. The canon dishes done straight, no folklore. Closed Sun–Mon.",
    "address": "8 Rue Monge, 21200 Beaune",
    "phone": "",
    "hours": "Lunch",
    "maps": "https://www.google.com/maps/search/?api=1&query=Le+Bistrot+Bourguignon+Beaune"
  },
  {
    "id": "v08-la-table-du-square",
    "cat": "shop",
    "tier": "several",
    "priority": 8,
    "badge": "CONTEMPOR",
    "name": "La Table du Square",
    "short": "La Table du Square",
    "lat": 47.0258,
    "lng": 4.8388,
    "tags": [
      "Michelin Bib Gourmand (since 2024)",
      "EUR 30-42 menu",
      "Recommended",
      "Lunch"
    ],
    "productTags": [
      "Contemporary"
    ],
    "why": "Michelin Bib Gourmand (since 2024). To order: the market menu — rewritten every fortnight. Chef Romain Escoffier. The best value-for-craft in Beaune by Michelin's own reckoning, a wine list past 1,000 labels. Closed Sun–Mon.",
    "address": "26 Boulevard Maréchal-Foch, 21200 Beaune",
    "phone": "+33 3 80 24 03 32",
    "hours": "Lunch",
    "maps": "https://www.google.com/maps/search/?api=1&query=La+Table+du+Square+Beaune"
  },
  {
    "id": "v09-loiseau-des-vignes",
    "cat": "shop",
    "tier": "several",
    "priority": 9,
    "badge": "DRINK",
    "name": "Loiseau des Vignes",
    "short": "Loiseau des Vignes",
    "lat": 47.0223,
    "lng": 4.838,
    "tags": [
      "Bernard Loiseau group — the wine-by-the-glass bistro",
      "EUR 40-70",
      "Recommended",
      "Dinner"
    ],
    "productTags": [
      "Wine",
      "Contemporary"
    ],
    "why": "Bernard Loiseau group — the wine-by-the-glass bistro. To order: œufs en meurette; pâté en croûte; 32 Burgundies poured by the glass from four oak cellars. The Saulieu three-star group's Beaune address. The point is the glass list — 32 wines kept properly, the way to drink across the Côte in one sitting. Its gougères are a benchmark. Closed Sun–Mon.",
    "address": "31 Rue Maufoux, 21200 Beaune",
    "phone": "+33 3 80 24 12 06",
    "hours": "Dinner",
    "maps": "https://www.google.com/maps/search/?api=1&query=Loiseau+des+Vignes+Beaune"
  },
  {
    "id": "v10-le-comptoir-des-tontons",
    "cat": "shop",
    "tier": "several",
    "priority": 10,
    "badge": "CONTEMPOR",
    "name": "Le Comptoir des Tontons",
    "short": "Le Comptoir des Tontons",
    "lat": 47.0205,
    "lng": 4.8426,
    "tags": [
      "Bistrot-épicerie — natural and biodynamic wine",
      "EUR 32-48 menu",
      "Essential",
      "Dinner"
    ],
    "productTags": [
      "Contemporary",
      "Wine"
    ],
    "why": "Bistrot-épicerie — natural and biodynamic wine. To order: the seasonal organic market plates; taste a wine, then buy the bottle off the shelf. A small room of natural-wine conviction on the Madeleine faubourg. Reserve — there are not many seats.",
    "address": "22 Rue du Faubourg-Madeleine, 21200 Beaune",
    "phone": "+33 3 80 24 19 64",
    "hours": "Dinner",
    "maps": "https://www.google.com/maps/search/?api=1&query=Le+Comptoir+des+Tontons+Beaune"
  },
  {
    "id": "v11-enstase",
    "cat": "shop",
    "tier": "several",
    "priority": 11,
    "badge": "DRINK",
    "name": "Enstase",
    "short": "Enstase",
    "lat": 47.0234,
    "lng": 4.8407,
    "tags": [
      "Cave à manger — the natural-wine address of Beaune",
      "EUR 6-15 glass",
      "Walk-in",
      "All day"
    ],
    "productTags": [
      "Wine",
      "Bacaro"
    ],
    "why": "Cave à manger — the natural-wine address of Beaune. To order: natural wine, cider and kefir; Thursday and Friday the kitchen opens — bao and elaborate small plates. A room built entirely of natural materials, a low-intervention wine list, and a kitchen that wakes up at the week's end. The counter where young Beaune drinks.",
    "address": "5 Rue Vergnette de Lamotte, 21200 Beaune",
    "phone": "+33 9 71 31 10 17",
    "hours": "All day",
    "maps": "https://www.google.com/maps/search/?api=1&query=Enstase+Beaune"
  },
  {
    "id": "v12-march-aux-vins",
    "cat": "shop",
    "tier": "plenty",
    "priority": 12,
    "badge": "DRINK",
    "name": "Marché aux Vins",
    "short": "Marché aux Vins",
    "lat": 47.0201,
    "lng": 4.8361,
    "tags": [
      "Self-guided tasting cellar in the former Cordeliers church",
      "EUR 25-65",
      "Walk-in",
      "Morning"
    ],
    "productTags": [
      "Wine"
    ],
    "why": "Self-guided tasting cellar in the former Cordeliers church. To order: Découverte (5 wines) 25 € or Prestige (7 wines) 49 € — taste as you walk the chapels. Three intact Gothic chapels turned tasting cellar, vintages stored 40 years underground. Go at opening, 10:00 on a weekday, when the stone is cold and empty.",
    "address": "2 Rue Nicolas Rolin, 21200 Beaune",
    "phone": "",
    "hours": "Morning",
    "maps": "https://www.google.com/maps/search/?api=1&query=Marché+aux+Vins+Beaune"
  },
  {
    "id": "v13-patriarche-p-re-fils",
    "cat": "shop",
    "tier": "plenty",
    "priority": 13,
    "badge": "CULT",
    "name": "Patriarche Père & Fils",
    "short": "Patriarche Père & Fils",
    "lat": 47.0209,
    "lng": 4.8405,
    "tags": [
      "The largest cellars in Burgundy — 5 km of galleries",
      "EUR 25 visit",
      "Walk-in",
      "All day"
    ],
    "productTags": [
      "Wine"
    ],
    "why": "The largest cellars in Burgundy — 5 km of galleries. To order: the self-guided cellar visit with a tasting of 6 wines, 25 €. Founded 1780, the galleries dug under a former Visitandine convent — around two million bottles ageing in the dark. The clearest sense of how much wine sleeps beneath Beaune. Verify hours before going.",
    "address": "5-7 Rue du Collège, 21200 Beaune",
    "phone": "+33 3 80 24 53 78",
    "hours": "All day",
    "maps": "https://www.google.com/maps/search/?api=1&query=Patriarche+Père+&+Fils+Beaune"
  },
  {
    "id": "v14-bouchard-p-re-fils",
    "cat": "shop",
    "tier": "plenty",
    "priority": 14,
    "badge": "CULT",
    "name": "Bouchard Père & Fils",
    "short": "Bouchard Père & Fils",
    "lat": 47.0252,
    "lng": 4.8405,
    "tags": [
      "Cellars inside a 15th-century royal fortress",
      "EUR 35-90 visit",
      "Recommended",
      "Afternoon"
    ],
    "productTags": [
      "Wine"
    ],
    "why": "Cellars inside a 15th-century royal fortress. To order: the guided fortress-cellar visit and tasting; the Beaune Grèves 'Vigne de l'Enfant Jésus'. Bouchard took the Château de Beaune — built for Louis XI — in 1820; the cellars run 10 m into the rampart, holding 19th-century bottles. Book ahead; tours Tue–Sat.",
    "address": "15 Rue du Château, 21200 Beaune",
    "phone": "+33 3 80 24 80 24",
    "hours": "Afternoon",
    "maps": "https://www.google.com/maps/search/?api=1&query=Bouchard+Père+&+Fils+Beaune"
  },
  {
    "id": "v15-march-des-halles-saturday",
    "cat": "market",
    "tier": "plenty",
    "priority": 15,
    "badge": "MARKET",
    "name": "Marché des Halles (Saturday)",
    "short": "Marché des Halles (Satur",
    "lat": 47.0213,
    "lng": 4.8392,
    "tags": [
      "The Saturday market — around 180 stalls, a real local event",
      "EUR variable",
      "Walk-in",
      "Morning"
    ],
    "productTags": [
      "Market",
      "Produce",
      "Cheese"
    ],
    "why": "The Saturday market — around 180 stalls, a real local event. To order: Époisses and Cîteaux cheese; jambon persillé; Fallot mustard from the stand; autumn girolles. 07:00–13:00 across Place de la Halle, Place Fleury and the covered halls. Saturday is the big one; Wednesday is the quieter, food-only market. Producers down from the hill villages.",
    "address": "Place de la Halle, 21200 Beaune",
    "phone": "",
    "hours": "Morning",
    "maps": "https://www.google.com/maps/search/?api=1&query=Marché+des+Halles+(Saturday)+Beaune"
  },
  {
    "id": "v16-p-tisserie-fabien-berteau",
    "cat": "shop",
    "tier": "several",
    "priority": 16,
    "badge": "CAFE",
    "name": "Pâtisserie Fabien Berteau",
    "short": "Pâtisserie Fabien Bertea",
    "lat": 47.0228,
    "lng": 4.8376,
    "tags": [
      "The pâtisserie address of Beaune",
      "EUR 3-9",
      "Walk-in",
      "All day"
    ],
    "productTags": [
      "Cafe",
      "Bread"
    ],
    "why": "The pâtisserie address of Beaune. To order: the seasonal-fruit cheesecake, the chef's signature; macarons; the morning viennoiserie. Revised French classics and house-made ice cream. The tea room Le Garden opposite does an affordable lunch under a shaded summer terrace. Closed Wednesday.",
    "address": "18 Rue Monge, 21200 Beaune",
    "phone": "",
    "hours": "All day",
    "maps": "https://www.google.com/maps/search/?api=1&query=Pâtisserie+Fabien+Berteau+Beaune"
  }
];
    const NEIGHBORHOODS = [
  {
    "id": "n-place-carnot",
    "name": "Place Carnot & Place de la Halle",
    "center": [
      47.0223,
      4.839
    ],
    "radius": 160,
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Place+Carnot+Beaune"
  },
  {
    "id": "n-rue-maufoux",
    "name": "Rue Maufoux & the cellar streets",
    "center": [
      47.022,
      4.8378
    ],
    "radius": 170,
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Rue+Maufoux+Beaune"
  },
  {
    "id": "n-place-madeleine",
    "name": "Place Madeleine & Faubourg Madeleine",
    "center": [
      47.0208,
      4.842
    ],
    "radius": 200,
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Place+Madeleine+Beaune"
  },
  {
    "id": "n-place-monge",
    "name": "Place Monge — the charcutier quarter",
    "center": [
      47.0227,
      4.8376
    ],
    "radius": 130,
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Place+Monge+Beaune"
  },
  {
    "id": "n-faubourg-bretonniere",
    "name": "Faubourg Bretonnière",
    "center": [
      47.023,
      4.833
    ],
    "radius": 260,
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Faubourg+Bretonniere+Beaune"
  },
  {
    "id": "n-vineyard-slope",
    "name": "The vineyard slope",
    "center": [
      47.0225,
      4.826
    ],
    "radius": 520,
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Clos+des+Mouches+Beaune"
  },
  {
    "id": "n-out-of-town",
    "name": "Out of town — the Route des Grands Crus",
    "center": [
      47.001,
      4.83
    ],
    "radius": 900,
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Route+des+Grands+Crus+Pommard"
  }
];
    const WALKS = [
  {
    "id": "p-walk-ramparts",
    "name": "The ramparts circuit",
    "start": [
      47.0254,
      4.8376
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Remparts+de+Beaune"
  },
  {
    "id": "p-walk-climats",
    "name": "Up into the climats",
    "start": [
      47.0218,
      4.8318
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Parc+de+la+Bouzaise+Beaune"
  },
  {
    "id": "p-walk-meursault",
    "name": "Beaune to Meursault by the vines",
    "start": [
      47.0218,
      4.8318
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Pommard+village"
  },
  {
    "id": "p-walk-corton",
    "name": "Corton hill from Pernand-Vergelesses",
    "start": [
      47.073,
      4.846
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Pernand-Vergelesses"
  },
  {
    "id": "p-walk-bouzaise",
    "name": "The Parc de la Bouzaise loop",
    "start": [
      47.0208,
      4.8318
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Parc+de+la+Bouzaise+Beaune"
  }
];
    const WORK_SPOTS = [
  {
    "id": "p-work-bouzaise",
    "name": "Parc de la Bouzaise",
    "start": [
      47.0208,
      4.8318
    ]
  },
  {
    "id": "p-work-cite-terrace",
    "name": "Cité des Climats — terraces",
    "start": [
      47.0295,
      4.8445
    ]
  },
  {
    "id": "p-work-cafe-carnot",
    "name": "A Place Carnot terrace",
    "start": [
      47.0234,
      4.8389
    ]
  },
  {
    "id": "p-work-rempart-dames",
    "name": "Rempart des Dames",
    "start": [
      47.0256,
      4.8368
    ]
  }
];
    const LANDMARKS = [
  {
    "id": "l-hotel-dieu",
    "name": "Hôtel-Dieu / Hospices de Beaune",
    "coords": [
      47.01983,
      4.83533
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Hospices+de+Beaune"
  },
  {
    "id": "l-collegiale",
    "name": "Collégiale Notre-Dame",
    "coords": [
      47.02382,
      4.83597
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Collegiale+Notre-Dame+Beaune"
  },
  {
    "id": "l-chateau-beaune",
    "name": "Château de Beaune (Bouchard)",
    "coords": [
      47.0252,
      4.8405
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Chateau+de+Beaune"
  },
  {
    "id": "l-porte-st-nicolas",
    "name": "Porte Saint-Nicolas",
    "coords": [
      47.0272,
      4.8403
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Porte+Saint-Nicolas+Beaune"
  },
  {
    "id": "l-marche-aux-vins",
    "name": "Marché aux Vins (Cordeliers)",
    "coords": [
      47.0201,
      4.8361
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Marche+aux+Vins+Beaune"
  },
  {
    "id": "l-cite-climats",
    "name": "Cité des Climats et Vins",
    "coords": [
      47.0295,
      4.8445
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Cite+des+Climats+et+Vins+Beaune"
  },
  {
    "id": "l-parc-bouzaise",
    "name": "Parc de la Bouzaise",
    "coords": [
      47.0208,
      4.8312
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Parc+de+la+Bouzaise+Beaune"
  }
];
    return { VENUES, COLORS, CAT_LABELS, PRODUCT_COLORS, NEIGHBORHOODS, WALKS, WORK_SPOTS, LANDMARKS };
})();

/* PHOTOS — verified CC images, placed by guide-extras.js */
if (window.TERROIR_DATA) window.TERROIR_DATA.PHOTOS = [{"src": "/terroir/beaune-bourgogne/img/1-vista.jpg", "caption": "The glazed polychrome diamond-pattern tile roofs and half-timbered dormers of the Hospices de Beaune (Hotel-Dieu).", "credit": "Photo: Jebulon · Public domain · Wikimedia"}, {"src": "/terroir/beaune-bourgogne/img/2-human-food.jpg", "caption": "Crates of freshly picked harvest grapes stacked at the vineyard edge during the vendange near Santenay in the Cote de Beaune.", "credit": "Photo: JopkeB · CC BY-SA 4.0 · Wikimedia"}, {"src": "/terroir/beaune-bourgogne/img/3-texture.jpg", "caption": "Vineyard-clad slopes of the Cote de Beaune rising toward the Cote d'Or, with a stone wall and village rooftops below.", "credit": "Photo: Megan Mallen · CC BY 2.0 · Wikimedia"}];
