/* Terroir — Lons-le-Saunier — auto-generated by publish-terroir.py */
window.TERROIR_DATA = (function () {
    const COLORS = { berth:'#c4a35a', market:'#d97706', shop:'#059669', mainland:'#7c3aed', logistics:'#2d4a5e' };
    const CAT_LABELS = { berth:'Signature', market:'Market / Direct', shop:'Restaurant / Bar', mainland:'Out of town', logistics:'Logistics' };
    const PRODUCT_COLORS = {
    'Michelin':'#7f1d1d','Contemporary':'#1f2937','Traditional':'#a16207',
    'Cult':'#7c3aed','Cafe':'#92400e','Wine':'#7c2d12','Bacaro':'#7c3aed',
    'Drink':'#0ea5e9','Street Food':'#dc2626','Market':'#d97706',
    'Produce':'#15803d','Fish':'#3b82f6','Meat':'#b91c1c',
    'Cheese':'#eab308','Bread':'#a16207','Charcuterie':'#9d174d',
    'Hi-Fi':'#1f2937'
};
    const VENUES = [
  {
    "id": "v01-la-table-du-grapiot",
    "cat": "shop",
    "tier": "berth_top",
    "priority": 1,
    "badge": "CULT",
    "name": "La Table du Grapiot",
    "short": "La Table du Grapiot",
    "lat": 46.8839,
    "lng": 5.7611,
    "tags": [
      "Michelin one star — new in March 2026 (Gault & Millau Jeune Talent on reopening)",
      "EUR 60-94 menu",
      "Essential",
      "Lunch / Dinner"
    ],
    "productTags": [
      "Michelin",
      "Contemporary"
    ],
    "why": "Michelin one star — new in March 2026 (Gault & Millau Jeune Talent on reopening). To order: the tasting menu — Vivien Sonzogni's cuisine of memory: pike & blette with miso; trout & Morteau sausage; artichoke & beef tongue. Chef Vivien Sonzogni (35), associates Noémie Paris / Violette / Hugo. Took over June 2024; first ★ March 2026. The village of Pierre Overnoy is across the road — a natural-wine pilgrimage with a star at the end of it. Bistrot side opens June–August (Thu–Mon).",
    "address": "Rue Bagier (opposite the Mairie), 39600 Pupillin",
    "phone": "+33 3 84 37 49 44",
    "hours": "Lunch / Dinner",
    "maps": "https://www.google.com/maps/search/?api=1&query=La+Table+du+Grapiot+Lons-le-Saunier"
  },
  {
    "id": "v02-le-bistron-me",
    "cat": "shop",
    "tier": "berth_top",
    "priority": 2,
    "badge": "CONTEMPOR",
    "name": "Le Bistronôme",
    "short": "Le Bistronôme",
    "lat": 46.9005,
    "lng": 5.7757,
    "tags": [
      "Michelin Bib Gourmand (held); Gault & Millau selected; Pudlowski: \"une leçon de haute bistronomie\"",
      "EUR 27 lunch / 37 dinner / 55 à la carte",
      "Recommended",
      "Lunch on the Cuisance terrace"
    ],
    "productTags": [
      "Michelin",
      "Contemporary"
    ],
    "why": "Michelin Bib Gourmand (held); Gault & Millau selected; Pudlowski: \"une leçon de haute bistronomie\". To order: ballottine of Planches trout stuffed with morels & oyster mushrooms in Vin Jaune sauce; veal picanha marinated in soy + Vin Jaune; roast veal sweetbreads with smoked-cheese sauce + salted churros. Chefs Jérôme Brousseau (kitchen) + Léa Vuillemin (pastry), both former apprentices of Jeunet and Naessens. Closed Sun-Mon; closed Thu eves Nov-Mar. Wine list exclusively Jura.",
    "address": "62 rue du Faramand, 39600 Arbois",
    "phone": "+33 3 84 53 08 51",
    "hours": "Lunch on the Cuisance terrace",
    "maps": "https://www.google.com/maps/search/?api=1&query=Le+Bistronôme+Lons-le-Saunier"
  },
  {
    "id": "v03-tablier",
    "cat": "shop",
    "tier": "berth_top",
    "priority": 3,
    "badge": "TRADITION",
    "name": "Ô Tablier",
    "short": "Ô Tablier",
    "lat": 46.6743,
    "lng": 5.5527,
    "tags": [
      "Gault & Millau selected; #1-rated restaurant in Lons (TripAdvisor 4.9/5, 300+ reviews)",
      "EUR 36-42 menu",
      "Recommended (small room)",
      "Weekday lunch"
    ],
    "productTags": [
      "Contemporary",
      "Traditional"
    ],
    "why": "Gault & Millau selected; #1-rated restaurant in Lons (TripAdvisor 4.9/5, 300+ reviews). To order: four starters / four mains / two desserts — rewritten regularly; the Comté and Morteau will be where they belong on the menu. Chefs Louise Crétin (kitchen) + Thomas Berthod (salle). Short-circuit, seasonal, local, organic where possible. The best expression of Jura terroir in central Lons. Unusual split hours — verify before going.",
    "address": "20 rue Émile Monot, 39000 Lons-le-Saunier",
    "phone": "+33 3 84 24 26 59",
    "hours": "Weekday lunch",
    "maps": "https://www.google.com/maps/search/?api=1&query=Ô+Tablier+Lons-le-Saunier"
  },
  {
    "id": "v04-la-com-die",
    "cat": "shop",
    "tier": "several",
    "priority": 4,
    "badge": "CONTEMPOR",
    "name": "La Comédie",
    "short": "La Comédie",
    "lat": 46.6748,
    "lng": 5.5528,
    "tags": [
      "The Place de la Comédie's resident table — renovated historic monument, coloured arcades",
      "EUR 35-60",
      "Recommended",
      "Dinner"
    ],
    "productTags": [
      "Contemporary"
    ],
    "why": "The Place de la Comédie's resident table — renovated historic monument, coloured arcades. To order: the Plaisir 5-course or Découverte 6-course; menus du Marché change weekly. Chefs Lucie & Guillaume Ferrier. Tue–Sat 11:30–14:00 and 19:00–22:00. Comté, Mont d'Or, Morteau and Jura wines throughout the menu.",
    "address": "65 Place de la Comédie, 39000 Lons-le-Saunier",
    "phone": "+33 3 84 24 20 66",
    "hours": "Dinner",
    "maps": "https://www.google.com/maps/search/?api=1&query=La+Comédie+Lons-le-Saunier"
  },
  {
    "id": "v05-la-petite-auberge",
    "cat": "shop",
    "tier": "several",
    "priority": 5,
    "badge": "CONTEMPOR",
    "name": "La Petite Auberge",
    "short": "La Petite Auberge",
    "lat": 46.694,
    "lng": 5.5648,
    "tags": [
      "Gault & Millau listed — chef's table on the northern approach",
      "EUR 29-42 menu",
      "Recommended",
      "Dinner"
    ],
    "productTags": [
      "Contemporary"
    ],
    "why": "Gault & Millau listed — chef's table on the northern approach. To order: morel & Vin Jaune crust; Jura trout with roasted bacon; Dombes duck; soufflé glacé au Macvin (Véronique's dessert). Chefs Véronique & Nicolas Narbey (ex-Château d'As Baume-les-Dames, ex-Matignon). Mon lunch; Tue-Fri lunch + dinner; Sun lunch. Closed Sat and Mon eve.",
    "address": "1985 route de Besançon, 39000 Lons-le-Saunier",
    "phone": "+33 3 84 47 23 35",
    "hours": "Dinner",
    "maps": "https://www.google.com/maps/search/?api=1&query=La+Petite+Auberge+Lons-le-Saunier"
  },
  {
    "id": "v06-le-bistrot-des-marronniers",
    "cat": "shop",
    "tier": "several",
    "priority": 6,
    "badge": "TRADITION",
    "name": "Le Bistrot des Marronniers",
    "short": "Le Bistrot des Marronnie",
    "lat": 46.6757,
    "lng": 5.5543,
    "tags": [
      "Lyonnais-Jura hybrid bouchon since 1987 — wood-fired grill in the room",
      "EUR 25-45",
      "Walk-in / phone",
      "Lunch"
    ],
    "productTags": [
      "Traditional",
      "Wine"
    ],
    "why": "Lyonnais-Jura hybrid bouchon since 1987 — wood-fired grill in the room. To order: tablier de sapeur (Lyonnais tripe), pike-perch fillet with Poulsard wine, calf liver with Macvin. Half Lyonnais bouchon, half Jura. David & Jean-Michel, co-proprietors. The grill is the centerpiece of the dining room.",
    "address": "22 rue de Vallière, 39000 Lons-le-Saunier",
    "phone": "+33 3 84 43 06 04",
    "hours": "Lunch",
    "maps": "https://www.google.com/maps/search/?api=1&query=Le+Bistrot+des+Marronniers+Lons-le-Saunier"
  },
  {
    "id": "v07-la-table-de-perraud",
    "cat": "shop",
    "tier": "several",
    "priority": 7,
    "badge": "TRADITION",
    "name": "La Table de Perraud",
    "short": "La Table de Perraud",
    "lat": 46.6746,
    "lng": 5.5519,
    "tags": [
      "Gault & Millau listed — reliable traditional table",
      "EUR 24-35 formula",
      "Walk-in",
      "Lunch"
    ],
    "productTags": [
      "Traditional"
    ],
    "why": "Gault & Millau listed — reliable traditional table. To order: pochouse jurassienne (the Jura's freshwater fish stew in white wine and cream), choucroute, andouillette with mustard cream, lamb shoulder. Chef Gabriel Janod. Named for the Jurassien sculptor Jean-Joseph Perraud. The pochouse is the Lyonnais-equivalent dish to test.",
    "address": "11 Place Perraud, 39000 Lons-le-Saunier",
    "phone": "+33 3 84 86 49 68",
    "hours": "Lunch",
    "maps": "https://www.google.com/maps/search/?api=1&query=La+Table+de+Perraud+Lons-le-Saunier"
  },
  {
    "id": "v08-la-finette-taverne-d-arbois",
    "cat": "shop",
    "tier": "several",
    "priority": 8,
    "badge": "TRADITION",
    "name": "La Finette — Taverne d'Arbois",
    "short": "La Finette — Taverne d'A",
    "lat": 46.9027,
    "lng": 5.7786,
    "tags": [
      "The canonical Jura tavern since 1961 — varnished log tables, vaulted cellar",
      "EUR 21-55 menu / 20.50 fondue per person",
      "Recommended",
      "Weekday lunch"
    ],
    "productTags": [
      "Traditional",
      "Wine"
    ],
    "why": "The canonical Jura tavern since 1961 — varnished log tables, vaulted cellar. To order: fondue de Comté (€20.50/person), poulet au Vin Jaune et morilles, Jura trout, Morteau sausage, Franche-Comté ice cream with Fougerolles cherries. Daily 11:45-14:30 and 18:45-22:30, year-round. Maximum Jura folk décor. Wines exclusively Jura.",
    "address": "22 avenue Louis Pasteur, 39600 Arbois",
    "phone": "+33 3 84 66 06 78",
    "hours": "Weekday lunch",
    "maps": "https://www.google.com/maps/search/?api=1&query=La+Finette+—+Taverne+d'Arbois+Lons-le-Saunier"
  },
  {
    "id": "v09-le-bistrot-des-claquets",
    "cat": "shop",
    "tier": "several",
    "priority": 9,
    "badge": "DRINK",
    "name": "Le Bistrot des Claquets",
    "short": "Le Bistrot des Claquets",
    "lat": 46.9012,
    "lng": 5.7754,
    "tags": [
      "Le Fooding selected — the cave à manger / natural-wine bistro of Arbois since 2010",
      "EUR 12-22",
      "Phone only",
      "Lunch"
    ],
    "productTags": [
      "Wine",
      "Bacaro"
    ],
    "why": "Le Fooding selected — the cave à manger / natural-wine bistro of Arbois since 2010. To order: the daily-changing single main course + cold buffet (formula €12–19.50); aperitif boards with regional charcuterie and cheese. Personal natural & organic Jura wine selection — the team tastes everything before listing. Where the Jura vignerons drink lunch. AMAP farmer deliveries Tue and Wed.",
    "address": "Place Faramand, 39600 Arbois",
    "phone": "+33 3 84 66 04 19",
    "hours": "Lunch",
    "maps": "https://www.google.com/maps/search/?api=1&query=Le+Bistrot+des+Claquets+Lons-le-Saunier"
  },
  {
    "id": "v10-p-tisserie-chocolaterie-pelen",
    "cat": "shop",
    "tier": "several",
    "priority": 10,
    "badge": "CAFE",
    "name": "Pâtisserie Chocolaterie Pelen",
    "short": "Pâtisserie Chocolaterie ",
    "lat": 46.6742,
    "lng": 5.5504,
    "tags": [
      "Maison since 1899 — Gault & Millau listed chocolatier",
      "EUR 3-8",
      "Walk-in",
      "All day"
    ],
    "productTags": [
      "Cafe",
      "Bread"
    ],
    "why": "Maison since 1899 — Gault & Millau listed chocolatier. To order: Galet de Chalain (the praliné-and-nougatine signature, created 1984 by Dominique Pelen, named after Lac de Chalain), tarte au comté, éclair café, bean-to-bar chocolate. Arnaud Pelen, 4th generation. The Galet is the souvenir comestible to bring home. Note: address corrected — 175 rue Blaise Pascal, NOT rue du Commerce. Mon & Sat 08:00-12:00/14:30-19:00; Tue-Fri 08:30-12:00/13:45-17:30.",
    "address": "175 rue Blaise Pascal, 39000 Lons-le-Saunier",
    "phone": "+33 3 84 24 13 32",
    "hours": "All day",
    "maps": "https://www.google.com/maps/search/?api=1&query=Pâtisserie+Chocolaterie+Pelen+Lons-le-Saunier"
  },
  {
    "id": "v11-caveau-des-jacobins",
    "cat": "shop",
    "tier": "several",
    "priority": 11,
    "badge": "DRINK",
    "name": "Caveau des Jacobins",
    "short": "Caveau des Jacobins",
    "lat": 46.6744,
    "lng": 5.5524,
    "tags": [
      "Jura wine cave — sale and tasting of the seven varieties without driving",
      "EUR 6-15 glass / 18-150 bottle",
      "Walk-in",
      "All day"
    ],
    "productTags": [
      "Wine"
    ],
    "why": "Jura wine cave — sale and tasting of the seven varieties without driving. To order: Vin Jaune Macle or Tissot; Crémant brut; Macvin for the apéritif; a vertical of Ploussard from Pupillin. For understanding the seven Jura varieties before driving up to Château-Chalon. The caviste explains without bla-bla.",
    "address": "12 Rue Richebourg, 39000 Lons-le-Saunier",
    "phone": "",
    "hours": "All day",
    "maps": "https://www.google.com/maps/search/?api=1&query=Caveau+des+Jacobins+Lons-le-Saunier"
  },
  {
    "id": "v12-march-de-lons-le-saunier",
    "cat": "market",
    "tier": "plenty",
    "priority": 12,
    "badge": "MARKET",
    "name": "Marché de Lons-le-Saunier",
    "short": "Marché de Lons-le-Saunie",
    "lat": 46.6738,
    "lng": 5.553,
    "tags": [
      "The largest market in the Jura department — Thursday (main) + Saturday (food) + Wednesday (producers, 17h-19h30)",
      "EUR variable",
      "Walk-in",
      "Thursday morning"
    ],
    "productTags": [
      "Market",
      "Produce",
      "Cheese"
    ],
    "why": "The largest market in the Jura department — Thursday (main) + Saturday (food) + Wednesday (producers, 17h-19h30). To order: Comté from Marcel Petite (Fort Saint-Antoine), Saucisse de Morteau IGP from a tuyé producer, cancoillotte, Mont d'Or in season, miel de sapin, eight-month Bleu de Gex. Thursday is the big market — Place du 11 Novembre (manufactured goods, all day) + Place de Verdun (food, morning). Saturday: Cours Sully food morning. Wednesday: 17:00-19:30 producers, Place du 11 Novembre.",
    "address": "Place de la Comédie + Place du 11 Novembre, 39000 Lons-le-Saunier",
    "phone": "",
    "hours": "Thursday morning",
    "maps": "https://www.google.com/maps/search/?api=1&query=Marché+de+Lons-le-Saunier+Lons-le-Saunier"
  },
  {
    "id": "v13-maison-du-comt-poligny",
    "cat": "market",
    "tier": "plenty",
    "priority": 13,
    "badge": "PRODUCE",
    "name": "Maison du Comté — Poligny",
    "short": "Maison du Comté — Polign",
    "lat": 46.8389,
    "lng": 5.7064,
    "tags": [
      "Official Comté AOP interpretation centre — visit + tasting",
      "EUR 8.90 adult / 6.50 child",
      "Walk-in (groups book)",
      "Mornings"
    ],
    "productTags": [
      "Cheese"
    ],
    "why": "Official Comté AOP interpretation centre — visit + tasting. To order: the three-space visit (farm + dairy + cellar) with comparative tasting of three ages of Comté and Marcel Petite's Fort Saint-Antoine cuvée. Note: the Maison du Comté MOVED — new building on the site of the former municipal stadium with traditional Haut-Doubs farm architecture references. The old Avenue de la Résistance address is no longer current. Three themed spaces, tasting at the end.",
    "address": "Site of the former municipal stadium, 39800 Poligny",
    "phone": "+33 3 84 37 78 40",
    "hours": "Mornings",
    "maps": "https://www.google.com/maps/search/?api=1&query=Maison+du+Comté+—+Poligny+Lons-le-Saunier"
  },
  {
    "id": "v14-domaine-macle",
    "cat": "shop",
    "tier": "plenty",
    "priority": 14,
    "badge": "CULT",
    "name": "Domaine Macle",
    "short": "Domaine Macle",
    "lat": 46.7556,
    "lng": 5.6394,
    "tags": [
      "The canonical Château-Chalon house — family settled in 1850, 8th generation in 2025",
      "EUR 25-95 bottle",
      "Essential — visit by appointment only",
      "Afternoon"
    ],
    "productTags": [
      "Wine"
    ],
    "why": "The canonical Château-Chalon house — family settled in 1850, 8th generation in 2025. To order: Château-Chalon (Vin Jaune); Côtes du Jura blanc tradition (Chardonnay ouillé); Crémant. Laurent Macle since 1995 (7th gen); Carmen Macle joined January 2025 (8th gen). 12 ha total: 8 ha Chardonnay (Côtes du Jura) + 4 ha Savagnin (Château-Chalon). Tastings in the family cellar, no theatre. Château-Chalon declassified years: 1974, 1980, 1984, 2001.",
    "address": "Rue de la Roche, 39210 Château-Chalon",
    "phone": "+33 3 84 85 21 85",
    "hours": "Afternoon",
    "maps": "https://www.google.com/maps/search/?api=1&query=Domaine+Macle+Lons-le-Saunier"
  },
  {
    "id": "v15-domaine-st-phane-tissot",
    "cat": "shop",
    "tier": "plenty",
    "priority": 15,
    "badge": "CULT",
    "name": "Domaine Stéphane Tissot",
    "short": "Domaine Stéphane Tissot",
    "lat": 46.9244,
    "lng": 5.7853,
    "tags": [
      "The biodynamic reference of the Jura — Demeter certified since 2004",
      "EUR 18-120 bottle",
      "Recommended for cellar; shop walk-in",
      "All day"
    ],
    "productTags": [
      "Wine"
    ],
    "why": "The biodynamic reference of the Jura — Demeter certified since 2004. To order: Arbois Trousseau Singulier; Vin Jaune; Vin de Paille; Crémant Indigène; the parcellaire Chardonnays. Bénédicte & Stéphane Tissot, 50 ha, organic 1999 + biodynamic Demeter 2004. Over 30 cuvées on blue and grey marls, limestone and clay — the broadest serious gamme in the Jura. Same village where Pasteur ran his vine experiments.",
    "address": "39 Rue de Curon, 39600 Montigny-lès-Arsures",
    "phone": "+33 3 84 66 08 27",
    "hours": "All day",
    "maps": "https://www.google.com/maps/search/?api=1&query=Domaine+Stéphane+Tissot+Lons-le-Saunier"
  },
  {
    "id": "v16-maison-de-louis-pasteur",
    "cat": "shop",
    "tier": "plenty",
    "priority": 16,
    "badge": "CULT",
    "name": "Maison de Louis Pasteur",
    "short": "Maison de Louis Pasteur",
    "lat": 46.9039,
    "lng": 5.7758,
    "tags": [
      "Maison des Illustres (2013) — Pasteur's home laboratory, preserved intact",
      "EUR 7-9",
      "Walk-in or guided slot",
      "Late morning"
    ],
    "productTags": [
      "Cult"
    ],
    "why": "Maison des Illustres (2013) — Pasteur's home laboratory, preserved intact. To order: the 1-hour guided visit; the experimental vineyard in Pupillin (Clos Pasteur) is still maintained. Family moved here 1827, when Pasteur was four. His 1857 Mémoire on lactic fermentation (Académie des Sciences, 30 November) was the foundational fermentation paper — not a doctoral thesis (his doctorate, 1847, was on crystallography). The Arbois lab is among the best-preserved 19th-c. scientific workplaces in France. One hour.",
    "address": "83 Rue de Courcelles, 39600 Arbois",
    "phone": "+33 3 84 66 11 72",
    "hours": "Late morning",
    "maps": "https://www.google.com/maps/search/?api=1&query=Maison+de+Louis+Pasteur+Lons-le-Saunier"
  },
  {
    "id": "v17-salines-royales-d-arc-et-senans-unes",
    "cat": "shop",
    "tier": "plenty",
    "priority": 17,
    "badge": "CULT",
    "name": "Salines Royales d'Arc-et-Senans (UNESCO)",
    "short": "Salines Royales d'Arc-et",
    "lat": 47.0331,
    "lng": 5.7767,
    "tags": [
      "UNESCO 1982 (Arc-et-Senans) + 2009 extension (Salins-les-Bains) — Claude-Nicolas Ledoux 1775",
      "EUR 13-15",
      "Walk-in",
      "All day"
    ],
    "productTags": [
      "Cult"
    ],
    "why": "UNESCO 1982 (Arc-et-Senans) + 2009 extension (Salins-les-Bains) — Claude-Nicolas Ledoux 1775. To order: the visit + the Festival des Jardins (June–October); the semicircular layout of Ledoux's industrial city. Construction 1775; operations 1779–1895; UNESCO 1982; Salins-les-Bains added 29 June 2009. Ledoux's semicircular ideal-city layout, the Director's house at the focal point. Brine arrived via the 21.25-km saumoduc from Salins (wooden pipeline, cast iron from 1782, ~30 % loss to leaks and smugglers).",
    "address": "Grande Rue, 25610 Arc-et-Senans",
    "phone": "+33 3 81 54 45 45",
    "hours": "All day",
    "maps": "https://www.google.com/maps/search/?api=1&query=Salines+Royales+d'Arc-et-Senans+(UNESCO)+Lons-le-Saunier"
  }
];
    const NEIGHBORHOODS = [
  {
    "id": "n-place-liberte",
    "name": "Place de la Liberté & rue du Commerce",
    "center": [
      46.6748,
      5.5544
    ],
    "radius": 180,
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Place+de+la+Libert%C3%A9+Lons-le-Saunier"
  },
  {
    "id": "n-place-comedie",
    "name": "Place de la Comédie / Halles",
    "center": [
      46.6738,
      5.553
    ],
    "radius": 130,
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Place+de+la+Com%C3%A9die+Lons-le-Saunier"
  },
  {
    "id": "n-chevalerie",
    "name": "Quartier de la Chevalerie & Source Salée",
    "center": [
      46.6722,
      5.548
    ],
    "radius": 280,
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Parc+de+la+Chevalerie+Lons-le-Saunier"
  },
  {
    "id": "n-place-perraud",
    "name": "Place Perraud & rue Émile Monot",
    "center": [
      46.6748,
      5.552
    ],
    "radius": 150,
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Place+Perraud+Lons-le-Saunier"
  },
  {
    "id": "n-chille",
    "name": "Montciel & Chille",
    "center": [
      46.69,
      5.57
    ],
    "radius": 600,
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Chille+Jura"
  },
  {
    "id": "n-arbois",
    "name": "Arbois (Jura wine capital, 15 km north)",
    "center": [
      46.9036,
      5.7747
    ],
    "radius": 700,
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Arbois+Jura"
  },
  {
    "id": "n-pupillin-chateau-chalon",
    "name": "Pupillin & Château-Chalon",
    "center": [
      46.7556,
      5.6394
    ],
    "radius": 1200,
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Ch%C3%A2teau-Chalon"
  },
  {
    "id": "n-poligny",
    "name": "Poligny (Comté capital)",
    "center": [
      46.8389,
      5.7064
    ],
    "radius": 500,
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Poligny+Jura"
  },
  {
    "id": "n-out-of-town",
    "name": "Port-Lesney / Sampans / Dole — the star territory",
    "center": [
      47.05,
      5.6
    ],
    "radius": 1500,
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Port-Lesney+Jura"
  }
];
    const WALKS = [
  {
    "id": "p-walk-rue-commerce-aube",
    "name": "Rue du Commerce arcades at dawn",
    "start": [
      46.6748,
      5.5544
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Rue+du+Commerce+Lons-le-Saunier"
  },
  {
    "id": "p-walk-chateau-chalon",
    "name": "Château-Chalon vineyard walk",
    "start": [
      46.7556,
      5.6394
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Ch%C3%A2teau-Chalon+vignoble"
  },
  {
    "id": "p-walk-arbois",
    "name": "Arbois old town + Pasteur lab",
    "start": [
      46.9036,
      5.7747
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Arbois+centre+ville"
  },
  {
    "id": "p-walk-baume-les-messieurs",
    "name": "Baume-les-Messieurs cirque + abbey",
    "start": [
      46.7095,
      5.645
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Baume-les-Messieurs"
  },
  {
    "id": "p-walk-cascades-herisson",
    "name": "Cascades du Hérisson",
    "start": [
      46.63,
      5.88
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Cascades+du+H%C3%A9risson"
  },
  {
    "id": "p-walk-belvedere-4-lacs",
    "name": "Belvédère des Quatre Lacs",
    "start": [
      46.61,
      5.91
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Belv%C3%A9d%C3%A8re+4+Lacs+Jura"
  }
];
    const WORK_SPOTS = [
  {
    "id": "p-work-parc-bains",
    "name": "Parc des Bains & Source Salée",
    "start": [
      46.6722,
      5.548
    ]
  },
  {
    "id": "p-work-mediatheque",
    "name": "Médiathèque",
    "start": [
      46.674,
      5.552
    ]
  },
  {
    "id": "p-work-cafe-comedie",
    "name": "Café de la Comédie",
    "start": [
      46.6736,
      5.5532
    ]
  },
  {
    "id": "p-work-rue-commerce-arcades",
    "name": "Rue du Commerce arcades",
    "start": [
      46.6748,
      5.5544
    ]
  }
];
    const LANDMARKS = [
  {
    "id": "l-rouget-de-lisle",
    "name": "Maison natale Rouget de Lisle",
    "coords": [
      46.6748,
      5.5546
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=24+rue+du+Commerce+Lons"
  },
  {
    "id": "l-source-salee",
    "name": "Source Salée — Parc des Bains",
    "coords": [
      46.6722,
      5.5485
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Source+Sal%C3%A9e+Lons"
  },
  {
    "id": "l-saint-desire",
    "name": "Église Saint-Désiré",
    "coords": [
      46.6735,
      5.5552
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Eglise+Saint-Desire+Lons"
  },
  {
    "id": "l-cordeliers",
    "name": "Église des Cordeliers",
    "coords": [
      46.6742,
      5.5539
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Eglise+des+Cordeliers+Lons"
  },
  {
    "id": "l-pasteur-arbois",
    "name": "Maison de Louis Pasteur — Arbois",
    "coords": [
      46.9039,
      5.7758
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Maison+Pasteur+Arbois"
  },
  {
    "id": "l-chateau-chalon",
    "name": "Château-Chalon (AOC capital)",
    "coords": [
      46.7556,
      5.6394
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Ch%C3%A2teau-Chalon"
  },
  {
    "id": "l-saline-royale",
    "name": "Saline Royale d'Arc-et-Senans",
    "coords": [
      47.0331,
      5.7767
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Saline+Royale+Arc-et-Senans"
  }
];
    return { VENUES, COLORS, CAT_LABELS, PRODUCT_COLORS, NEIGHBORHOODS, WALKS, WORK_SPOTS, LANDMARKS };
})();
