/* Terroir — Lons-le-Saunier — auto-generated by publish-terroir.py */
window.PCV_DATA = (function () {
    const COLORS = { berth:'#c4a35a', market:'#d97706', shop:'#059669', mainland:'#7c3aed', logistics:'#2d4a5e' };
    const CAT_LABELS = { berth:'Signature', market:'Marché / Direct', shop:'Restaurant / Bar', mainland:'Hors-ville', logistics:'Logistique' };
    const PRODUCT_COLORS = {
    'Michelin':'#7f1d1d','Contemporary':'#1f2937','Traditional':'#a16207',
    'Cult':'#7c3aed','Cafe':'#92400e','Wine':'#7c2d12','Bacaro':'#7c3aed',
    'Drink':'#0ea5e9','Street Food':'#dc2626','Market':'#d97706',
    'Produce':'#15803d','Fish':'#3b82f6','Meat':'#b91c1c',
    'Cheese':'#eab308','Bread':'#a16207','Charcuterie':'#9d174d',
    'Hi-Fi':'#1f2937'
};
    const VENUES = [
  {
    "id": "v01-restaurant-jean-paul-jeunet",
    "cat": "shop",
    "tier": "berth_top",
    "priority": 1,
    "badge": "MICHELIN",
    "name": "Restaurant Jean-Paul Jeunet",
    "neighborhood": "Arbois — centre historique",
    "short": "Restaurant Jean-Paul Jeu",
    "lat": 46.9036,
    "lng": 5.7747,
    "tags": [
      "Michelin Guide — table historique d'Arbois, Vin Jaune comme religion",
      "EUR 75-130 menu",
      "Essential",
      "Dinner"
    ],
    "productTags": [
      "Michelin"
    ],
    "why": "Michelin Guide — table historique d'Arbois, Vin Jaune comme religion. What to order: Poularde de Bresse au Vin Jaune et morilles ; truite de Doubs ; tarte au comté 36 mois. Le sanctuaire du Vin Jaune à table. Carte des Jaune anciens (Macle 1986, Tissot 1990) à voir et boire. Réserver 10 jours avant en saison.",
    "address": "9 rue de l'Hôtel de Ville, 39600 Arbois",
    "phone": "+33 3 84 66 05 67",
    "hours": "Dinner",
    "maps": "https://www.google.com/maps/search/?api=1&query=Restaurant+Jean-Paul+Jeunet+Lons-le-Saunier"
  },
  {
    "id": "v02-la-maison-carr-e-vincent-mercier",
    "cat": "shop",
    "tier": "berth_top",
    "priority": 2,
    "badge": "MICHELIN",
    "name": "La Maison Carrée — Vincent Mercier",
    "neighborhood": "Arbois — centre",
    "short": "La Maison Carrée — Vince",
    "lat": 46.902,
    "lng": 5.7726,
    "tags": [
      "Bib Gourmand — bistronomie jurassienne contemporaine",
      "EUR 35-55 mains",
      "Recommended",
      "All day"
    ],
    "productTags": [
      "Michelin",
      "Contemporary"
    ],
    "why": "Bib Gourmand — bistronomie jurassienne contemporaine. What to order: Tartare de bœuf montbéliarde au Trousseau ; sandre, cancoillotte fumée ; gaufre, miel de sapin. Plus jeune et plus libre que Jeunet. La salle est minuscule, terrasse l'été. Carte des vins jaunes au verre, rare.",
    "address": "Rue de Faramand, 39600 Arbois",
    "phone": "",
    "hours": "All day",
    "maps": "https://www.google.com/maps/search/?api=1&query=La+Maison+Carrée+—+Vincent+Mercier+Lons-le-Saunier"
  },
  {
    "id": "v03-le-comtois",
    "cat": "shop",
    "tier": "berth_top",
    "priority": 3,
    "badge": "TRADITION",
    "name": "Le Comtois",
    "neighborhood": "Lons centre — quartier du marché",
    "short": "Le Comtois",
    "lat": 46.676,
    "lng": 5.555,
    "tags": [
      "Bistrot du marché — cuisine jurassienne sans folklore",
      "EUR 18-28 plats",
      "Recommended",
      "Lunch"
    ],
    "productTags": [
      "Traditional"
    ],
    "why": "Bistrot du marché — cuisine jurassienne sans folklore. What to order: Saucisse de Morteau, lentilles vertes du Jura ; coq au Vin Jaune ; fondue au Comté trois âges. Bondé le jour du marché (jeudi, samedi). Carte courte ardoise, cancoillotte maison. À midi, formule à 22 € qui tient la route.",
    "address": "Rue de Pavigny, 39000 Lons-le-Saunier",
    "phone": "",
    "hours": "Lunch",
    "maps": "https://www.google.com/maps/search/?api=1&query=Le+Comtois+Lons-le-Saunier"
  },
  {
    "id": "v04-le-bistrot-des-halles",
    "cat": "shop",
    "tier": "several",
    "priority": 4,
    "badge": "TRADITION",
    "name": "Le Bistrot des Halles",
    "neighborhood": "Place de la Comédie / Halles",
    "short": "Le Bistrot des Halles",
    "lat": 46.6738,
    "lng": 5.553,
    "tags": [
      "Adresse de marché — clientèle d'habitués",
      "EUR 14-24 plats",
      "Walk-in",
      "Lunch"
    ],
    "productTags": [
      "Traditional"
    ],
    "why": "Adresse de marché — clientèle d'habitués. What to order: Plat du jour ardoise ; entrecôte montbéliarde ; tête de veau (jeudi). Y aller à midi le jour du marché, jamais le soir. Carte des vins jaunes courte mais propre.",
    "address": "Place de la Comédie, 39000 Lons-le-Saunier",
    "phone": "",
    "hours": "Lunch",
    "maps": "https://www.google.com/maps/search/?api=1&query=Le+Bistrot+des+Halles+Lons-le-Saunier"
  },
  {
    "id": "v05-h-tel-restaurant-le-parenth-se",
    "cat": "shop",
    "tier": "several",
    "priority": 5,
    "badge": "CONTEMPOR",
    "name": "Hôtel-Restaurant Le Parenthèse",
    "neighborhood": "Chille (5 min de Lons)",
    "short": "Hôtel-Restaurant Le Pare",
    "lat": 46.69,
    "lng": 5.57,
    "tags": [
      "Cuisine de produit — équipe jeune",
      "EUR 38-58 menu",
      "Recommended",
      "Dinner"
    ],
    "productTags": [
      "Contemporary"
    ],
    "why": "Cuisine de produit — équipe jeune. What to order: Risotto au comté 24 mois ; truite ikejime, beurre noisette ; ris de veau, sauce au Macvin. Hors centre — 5 minutes en voiture. Salle calme, terrasse jardin. Bon rapport qualité-prix le midi en semaine.",
    "address": "Route de Besançon, 39570 Chille",
    "phone": "",
    "hours": "Dinner",
    "maps": "https://www.google.com/maps/search/?api=1&query=Hôtel-Restaurant+Le+Parenthèse+Lons-le-Saunier"
  },
  {
    "id": "v06-le-bouchon-du-stade",
    "cat": "shop",
    "tier": "several",
    "priority": 6,
    "badge": "TRADITION",
    "name": "Le Bouchon du Stade",
    "neighborhood": "Lons — quartier du Stade",
    "short": "Le Bouchon du Stade",
    "lat": 46.673,
    "lng": 5.547,
    "tags": [
      "Cantine ouvrière — viandes de pays",
      "EUR 14-22 plats",
      "Walk-in",
      "Lunch"
    ],
    "productTags": [
      "Traditional"
    ],
    "why": "Cantine ouvrière — viandes de pays. What to order: Andouillette AAAAA ; entrecôte au Trousseau ; planche fromages comtois. Cantine sans chichi. Pas de site, paye en CB ou cash. À éviter le samedi soir (foot).",
    "address": "Avenue Camille Prost, 39000 Lons-le-Saunier",
    "phone": "",
    "hours": "Lunch",
    "maps": "https://www.google.com/maps/search/?api=1&query=Le+Bouchon+du+Stade+Lons-le-Saunier"
  },
  {
    "id": "v07-p-tisserie-chocolaterie-pelen",
    "cat": "shop",
    "tier": "several",
    "priority": 7,
    "badge": "CAFE",
    "name": "Pâtisserie Chocolaterie Pelen",
    "neighborhood": "Rue du Commerce (arcades)",
    "short": "Pâtisserie Chocolaterie ",
    "lat": 46.6748,
    "lng": 5.5544,
    "tags": [
      "Maison fondée 1899 — galets de l'Ain (chocolat-praliné)",
      "EUR 3-8",
      "Walk-in",
      "All day"
    ],
    "productTags": [
      "Cafe"
    ],
    "why": "Maison fondée 1899 — galets de l'Ain (chocolat-praliné). What to order: Galet de l'Ain ; tarte au comté ; éclair café. Institution. Le galet est le souvenir comestible à ramener. Salon de thé à l'étage.",
    "address": "1 Rue du Commerce, 39000 Lons-le-Saunier",
    "phone": "+33 3 84 24 13 32",
    "hours": "All day",
    "maps": "https://www.google.com/maps/search/?api=1&query=Pâtisserie+Chocolaterie+Pelen+Lons-le-Saunier"
  },
  {
    "id": "v08-le-caf-de-la-com-die",
    "cat": "shop",
    "tier": "several",
    "priority": 8,
    "badge": "CAFE",
    "name": "Le Café de la Comédie",
    "neighborhood": "Place de la Comédie",
    "short": "Le Café de la Comédie",
    "lat": 46.6736,
    "lng": 5.5532,
    "tags": [
      "Café terrasse face au théâtre 1840",
      "EUR 2-12",
      "Walk-in",
      "All day"
    ],
    "productTags": [
      "Cafe"
    ],
    "why": "Café terrasse face au théâtre 1840. What to order: Espresso ; verre de Crémant ; planche comté-saucisson. La meilleure terrasse pour observer le marché. Pas de spécialité, mais le café est correct et l'emplacement bat tout.",
    "address": "Place de la Comédie, 39000 Lons-le-Saunier",
    "phone": "",
    "hours": "All day",
    "maps": "https://www.google.com/maps/search/?api=1&query=Le+Café+de+la+Comédie+Lons-le-Saunier"
  },
  {
    "id": "v09-caveau-des-jacobins",
    "cat": "shop",
    "tier": "several",
    "priority": 9,
    "badge": "DRINK",
    "name": "Caveau des Jacobins",
    "neighborhood": "Lons centre — Richebourg",
    "short": "Caveau des Jacobins",
    "lat": 46.6744,
    "lng": 5.5524,
    "tags": [
      "Cave à vins jurassiens — vente et dégustation",
      "EUR 6-15 verre",
      "Walk-in",
      "All day"
    ],
    "productTags": [
      "Wine"
    ],
    "why": "Cave à vins jurassiens — vente et dégustation. What to order: Vin Jaune Macle ou Tissot ; Crémant brut ; Macvin pour l'apéritif. Pour comprendre les sept cépages avant de monter à Château-Chalon. Le caviste explique vraiment, pas de bla-bla.",
    "address": "12 Rue Richebourg, 39000 Lons-le-Saunier",
    "phone": "",
    "hours": "All day",
    "maps": "https://www.google.com/maps/search/?api=1&query=Caveau+des+Jacobins+Lons-le-Saunier"
  },
  {
    "id": "v10-march-de-lons-le-saunier",
    "cat": "market",
    "tier": "plenty",
    "priority": 10,
    "badge": "MARKET",
    "name": "Marché de Lons-le-Saunier",
    "neighborhood": "Place de la Comédie",
    "short": "Marché de Lons-le-Saunie",
    "lat": 46.6738,
    "lng": 5.553,
    "tags": [
      "Marché jeudi & samedi matin — l'un des plus beaux du Jura",
      "EUR variable",
      "Walk-in",
      "All day"
    ],
    "productTags": [
      "Market",
      "Produce",
      "Cheese"
    ],
    "why": "Marché jeudi & samedi matin — l'un des plus beaux du Jura. What to order: Comté de Marcel Petite (Fort Saint-Antoine) ; Morteau d'un tuyé ; cancoillotte ; miel de sapin. 7h-13h, jeudi et samedi. Jeudi est plus paysan, samedi plus dense. Producteurs montés du plateau (Hauts-Jura, Bresse).",
    "address": "Place de la Comédie, 39000 Lons-le-Saunier",
    "phone": "",
    "hours": "All day",
    "maps": "https://www.google.com/maps/search/?api=1&query=Marché+de+Lons-le-Saunier+Lons-le-Saunier"
  },
  {
    "id": "v11-fromagerie-vagne",
    "cat": "market",
    "tier": "plenty",
    "priority": 11,
    "badge": "PRODUCE",
    "name": "Fromagerie Vagne",
    "neighborhood": "Rue du Commerce (arcades)",
    "short": "Fromagerie Vagne",
    "lat": 46.675,
    "lng": 5.5546,
    "tags": [
      "Fromager-affineur du centre — Comté de plusieurs maisons",
      "EUR 5-25",
      "Walk-in",
      "All day"
    ],
    "productTags": [
      "Cheese",
      "Produce"
    ],
    "why": "Fromager-affineur du centre — Comté de plusieurs maisons. What to order: Plateau dégustation comté 18/24/36 mois ; Bleu de Gex ; Mont d'Or (oct-mai) ; cancoillotte. Demandez à goûter trois âges côte à côte — c'est la base. Sous-vide possible pour rapporter au bateau.",
    "address": "Rue du Commerce, 39000 Lons-le-Saunier",
    "phone": "",
    "hours": "All day",
    "maps": "https://www.google.com/maps/search/?api=1&query=Fromagerie+Vagne+Lons-le-Saunier"
  },
  {
    "id": "v12-maison-du-comt",
    "cat": "shop",
    "tier": "plenty",
    "priority": 12,
    "badge": "CULT",
    "name": "Maison du Comté",
    "neighborhood": "Poligny (capitale du Comté)",
    "short": "Maison du Comté",
    "lat": 46.8389,
    "lng": 5.7064,
    "tags": [
      "Centre d'interprétation officiel du Comté AOP — visite cave",
      "EUR 8-12 visite",
      "Recommended",
      "All day"
    ],
    "productTags": [
      "Cheese"
    ],
    "why": "Centre d'interprétation officiel du Comté AOP — visite cave. What to order: Visite + dégustation comparative cave d'altitude vs cave de plaine. Le détour utile : on comprend pourquoi un comté de fruitière de plateau ne ressemble pas à un comté de plaine. 45 min.",
    "address": "Avenue de la Résistance, 39800 Poligny",
    "phone": "+33 3 84 37 78 40",
    "hours": "All day",
    "maps": "https://www.google.com/maps/search/?api=1&query=Maison+du+Comté+Lons-le-Saunier"
  },
  {
    "id": "v13-domaine-macle",
    "cat": "shop",
    "tier": "plenty",
    "priority": 13,
    "badge": "CULT",
    "name": "Domaine Macle",
    "neighborhood": "Château-Chalon (Vin Jaune)",
    "short": "Domaine Macle",
    "lat": 46.7556,
    "lng": 5.6394,
    "tags": [
      "Référence absolue du Vin Jaune de Château-Chalon",
      "EUR 25-95 bouteille",
      "Essential",
      "All day"
    ],
    "productTags": [
      "Wine"
    ],
    "why": "Référence absolue du Vin Jaune de Château-Chalon. What to order: Château-Chalon ; Côtes du Jura blanc tradition ; Crémant. Visite uniquement sur rendez-vous. Laurent Macle reçoit lui-même. Dégustation sérieuse, dans la cave familiale, sans mise en scène.",
    "address": "Rue de la Roche, 39210 Château-Chalon",
    "phone": "+33 3 84 85 21 85",
    "hours": "All day",
    "maps": "https://www.google.com/maps/search/?api=1&query=Domaine+Macle+Lons-le-Saunier"
  },
  {
    "id": "v14-domaine-st-phane-tissot",
    "cat": "shop",
    "tier": "plenty",
    "priority": 14,
    "badge": "CULT",
    "name": "Domaine Stéphane Tissot",
    "neighborhood": "Montigny-lès-Arsures (Arbois)",
    "short": "Domaine Stéphane Tissot",
    "lat": 46.9244,
    "lng": 5.7853,
    "tags": [
      "Le Jura biodynamique — gamme la plus complète",
      "EUR 18-120 bouteille",
      "Recommended",
      "All day"
    ],
    "productTags": [
      "Wine"
    ],
    "why": "Le Jura biodynamique — gamme la plus complète. What to order: Arbois Trousseau Singulier ; Vin Jaune ; Vin de Paille ; Crémant Indigène. Plus large que Macle, plus expérimental. Grande gamme parcellaire. Boutique ouverte, mais réserver pour visiter les caves.",
    "address": "39 Rue de Curon, 39600 Montigny-lès-Arsures",
    "phone": "+33 3 84 66 08 27",
    "hours": "All day",
    "maps": "https://www.google.com/maps/search/?api=1&query=Domaine+Stéphane+Tissot+Lons-le-Saunier"
  },
  {
    "id": "v15-maison-de-louis-pasteur",
    "cat": "shop",
    "tier": "plenty",
    "priority": 15,
    "badge": "CULT",
    "name": "Maison de Louis Pasteur",
    "neighborhood": "Arbois — centre historique",
    "short": "Maison de Louis Pasteur",
    "lat": 46.9039,
    "lng": 5.7758,
    "tags": [
      "Maison-laboratoire de Pasteur — préservée intacte",
      "EUR 7-9",
      "Recommended",
      "All day"
    ],
    "productTags": [
      "Cult"
    ],
    "why": "Maison-laboratoire de Pasteur — préservée intacte. What to order: Visite guidée du labo + vignoble expérimental. Sa thèse sur la fermentation alcoolique a démarré ici, sur le Vin Jaune de Pupillin. Le labo est le seul de France conservé en l'état. Une heure.",
    "address": "83 Rue de Courcelles, 39600 Arbois",
    "phone": "+33 3 84 66 11 72",
    "hours": "All day",
    "maps": "https://www.google.com/maps/search/?api=1&query=Maison+de+Louis+Pasteur+Lons-le-Saunier"
  },
  {
    "id": "v16-volaille-mi-ral-bresse",
    "cat": "market",
    "tier": "plenty",
    "priority": 16,
    "badge": "PRODUCE",
    "name": "Volaille Miéral (Bresse)",
    "neighborhood": "Bresse (Montrevel-en-Bresse)",
    "short": "Volaille Miéral (Bresse)",
    "lat": 46.3331,
    "lng": 5.1311,
    "tags": [
      "Volailler référent de la Bresse AOP — fournisseur de chefs",
      "EUR variable",
      "Recommended",
      "All day"
    ],
    "productTags": [
      "Meat"
    ],
    "why": "Volailler référent de la Bresse AOP — fournisseur de chefs. What to order: Poularde de Bresse fine entière ; chapon ; pintade ; foie de volaille. Pour la poularde au Vin Jaune. À 50 minutes de route. Commander 48h avant en saison. Sous-vide pour le bateau.",
    "address": "Place de la Grenette, 01340 Montrevel-en-Bresse",
    "phone": "+33 4 74 25 48 36",
    "hours": "All day",
    "maps": "https://www.google.com/maps/search/?api=1&query=Volaille+Miéral+(Bresse)+Lons-le-Saunier"
  },
  {
    "id": "v17-salines-royales-d-arc-et-senans-unes",
    "cat": "shop",
    "tier": "plenty",
    "priority": 17,
    "badge": "CULT",
    "name": "Salines Royales d'Arc-et-Senans (UNESCO)",
    "neighborhood": "Arc-et-Senans (UNESCO)",
    "short": "Salines Royales d'Arc-et",
    "lat": 47.0331,
    "lng": 5.7767,
    "tags": [
      "UNESCO 1982 — saline royale Ledoux 1775, architecture utopique",
      "EUR 13-15",
      "Walk-in",
      "All day"
    ],
    "productTags": [
      "Cult"
    ],
    "why": "UNESCO 1982 — saline royale Ledoux 1775, architecture utopique. What to order: Visite + festival des jardins (juin-oct). Pour comprendre la chaîne du sel jurassien : la saumure de Salins-les-Bains arrivait ici par saumoduc en bois pour y être évaporée. Architecture Ledoux, vraie fascination.",
    "address": "Grande Rue, 25610 Arc-et-Senans",
    "phone": "+33 3 81 54 45 45",
    "hours": "All day",
    "maps": "https://www.google.com/maps/search/?api=1&query=Salines+Royales+d'Arc-et-Senans+(UNESCO)+Lons-le-Saunier"
  }
];
    return { VENUES, COLORS, CAT_LABELS, PRODUCT_COLORS };
})();
