#!/usr/bin/env python3
"""Build data/draft-articles.json — the feed for draft.html (the review index).

Single source of truth = the files that actually exist in articles/:
  articles/draft-*.html   and   articles/preview-*.html

For each draft it extracts:
  slug        filename without .html
  title       <title>, with the " — LITTORALICIOUS" suffix stripped
  lede        <meta name="description">
  read_time   <span class="article__reading-time">N min</span>, else word-count estimate
  file        articles/<name>.html
  added       file mtime (YYYY-MM-DD)

Run from the project root:  python3 scripts/build-draft-index.py
"""
from __future__ import annotations
import html
import json
import re
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ARTICLES = ROOT / "articles"
OUT = ROOT / "data" / "draft-articles.json"


def text(pattern: str, blob: str) -> str:
    m = re.search(pattern, blob, re.IGNORECASE | re.DOTALL)
    return html.unescape(m.group(1).strip()) if m else ""


def build() -> dict:
    drafts = []
    files = sorted(
        list(ARTICLES.glob("draft-*.html")) + list(ARTICLES.glob("preview-*.html"))
    )
    for f in files:
        blob = f.read_text(encoding="utf-8", errors="replace")
        title = text(r"<title>(.*?)</title>", blob)
        title = re.sub(r"\s*[—-]\s*LITTORALICIOUS\s*$", "", title, flags=re.IGNORECASE)
        lede = text(r'<meta name="description" content="(.*?)">', blob)
        rt = text(r'class="article__reading-time">\s*(\d+)', blob)
        if rt:
            read_time = int(rt)
        else:
            words = len(re.sub(r"<[^>]+>", " ", blob).split())
            read_time = max(1, round(words / 220))
        drafts.append(
            {
                "slug": f.stem,
                "title": title or f.stem,
                "category": "uncategorised",
                "category_label": "Uncategorised",
                "read_time": read_time,
                "file": f"articles/{f.name}",
                "lede": lede,
                "added": datetime.fromtimestamp(f.stat().st_mtime).strftime("%Y-%m-%d"),
            }
        )
    return {
        "_comment": "Auto-generated by scripts/build-draft-index.py. Do not hand-edit. "
        "To add a draft: drop articles/draft-{slug}.html and run scripts/sync-drafts.sh.",
        "_generated_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "count": len(drafts),
        "drafts": drafts,
    }


if __name__ == "__main__":
    data = build()
    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"✓ {data['count']} drafts indexed → data/draft-articles.json")
    for d in data["drafts"]:
        print(f"  · {d['slug']}  ({d['read_time']} min)")
