/* Terroir — Dubrovnik — auto-generated by publish-terroir.py */
window.PCV_DATA = (function () {
    const COLORS = { berth:'#c4a35a', market:'#d97706', shop:'#059669', mainland:'#7c3aed', logistics:'#2d4a5e' };
    const CAT_LABELS = { berth:'Signature', market:'Market / Direct', shop:'Restaurant / Bar', mainland:'Out of town', logistics:'Logistics' };
    const PRODUCT_COLORS = {
    'Michelin':'#7f1d1d','Contemporary':'#1f2937','Traditional':'#a16207',
    'Cult':'#7c3aed','Cafe':'#92400e','Wine':'#7c2d12','Bacaro':'#7c3aed',
    'Drink':'#0ea5e9','Street Food':'#dc2626','Market':'#d97706',
    'Produce':'#15803d','Fish':'#3b82f6','Meat':'#b91c1c',
    'Cheese':'#eab308','Bread':'#a16207','Charcuterie':'#9d174d',
    'Hi-Fi':'#1f2937'
};
    const VENUES = [
  {
    "id": "v01-restaurant-360",
    "cat": "shop",
    "tier": "berth_top",
    "priority": 1,
    "badge": "MICHELIN",
    "name": "Restaurant 360",
    "short": "Restaurant 360",
    "lat": 42.642,
    "lng": 18.1118,
    "tags": [
      "★ since 2018 · Michelin Plate before that · seasonal — opens 27 March 2026",
      "EUR 230–280 menu (pairing +120)",
      "Essential — book 2–3 months ahead, weekend dinners go first",
      "Dinner; sunset from the wall arches"
    ],
    "productTags": [
      "Michelin",
      "Wall-top",
      "Tasting menu"
    ],
    "why": "★ since 2018 · Michelin Plate before that · seasonal — opens 27 March 2026. À commander : the tasting menu only — Chef Marijo Curić's Adriatic-meets-Asia line, ~10 courses. Built into the arches above the Old Port — service is exposed to the sea, dinners stop when Jugo blows hard. Closed Nov–March.",
    "address": "Sv. Dominika bb, 20000 Dubrovnik",
    "phone": "+385 20 322 222",
    "hours": "Dinner; sunset from the wall arches",
    "maps": "https://www.google.com/maps/search/?api=1&query=Restaurant+360+Dubrovnik"
  },
  {
    "id": "v02-stara-lo-a-prijeko-palace",
    "cat": "shop",
    "tier": "berth_top",
    "priority": 2,
    "badge": "FINE DINI",
    "name": "Stara Loža (Prijeko Palace)",
    "short": "Stara Loža (Prijeko Pala",
    "lat": 42.6418,
    "lng": 18.11,
    "tags": [
      "Michelin Guide listed continuously since 2017",
      "EUR 80–140 pp",
      "Book the 16-seat rooftop 3+ weeks ahead",
      "Dinner, rooftop"
    ],
    "productTags": [
      "Michelin Guide",
      "Rooftop",
      "Seasonal"
    ],
    "why": "Michelin Guide listed continuously since 2017. À commander : the chef's day-market menu; oysters from Mali Ston when in season; sea bass in salt crust. Three spaces stacked vertically — street terrace, 3rd-floor salon, 16-seat rooftop. The one Prijeko Street address that is not a trap.",
    "address": "Prijeko 22, 20000 Dubrovnik",
    "phone": "+385 20 321 145",
    "hours": "Dinner, rooftop",
    "maps": "https://www.google.com/maps/search/?api=1&query=Stara+Loža+(Prijeko+Palace)+Dubrovnik"
  },
  {
    "id": "v03-proto-fish-restaurant",
    "cat": "shop",
    "tier": "berth_top",
    "priority": 3,
    "badge": "CLASSIC F",
    "name": "Proto Fish Restaurant",
    "short": "Proto Fish Restaurant",
    "lat": 42.6412,
    "lng": 18.1086,
    "tags": [
      "Founded 1886 — oldest operating fish house in Dubrovnik · Michelin Guide recommended",
      "EUR 70–110 pp",
      "Book 1 week ahead for the terrace",
      "Lunch on the terrace; dinner indoors"
    ],
    "productTags": [
      "Heritage 1886",
      "Fish",
      "Michelin Plate"
    ],
    "why": "Founded 1886 — oldest operating fish house in Dubrovnik · Michelin Guide recommended. À commander : king prawns alla buzara · Ston oysters · grilled sea bass on the bone · crni rižot. Edward VIII dined here in 1936 with Wallis Simpson on the way to Lokrum — the Esculap group runs it now without breaking the recipe book.",
    "address": "Široka 1, 20000 Dubrovnik",
    "phone": "+385 20 323 234",
    "hours": "Lunch on the terrace; dinner indoors",
    "maps": "https://www.google.com/maps/search/?api=1&query=Proto+Fish+Restaurant+Dubrovnik"
  },
  {
    "id": "v04-nautika",
    "cat": "shop",
    "tier": "several",
    "priority": 4,
    "badge": "CLASSIC L",
    "name": "Nautika",
    "short": "Nautika",
    "lat": 42.6418,
    "lng": 18.1059,
    "tags": [
      "Set in the former Nautical School (1881); on the city's classic-luxury short list",
      "EUR 120–180 pp",
      "Essential for the sea-side terrace; 2+ weeks",
      "Dinner at sunset — Bokar and Lovrijenac frame the view"
    ],
    "productTags": [
      "Sunset view",
      "Special-occasion",
      "Fine dining"
    ],
    "why": "Set in the former Nautical School (1881); on the city's classic-luxury short list. À commander : lobster bisque · whole turbot for two · soufflé glacé Grand Marnier. The conservative anniversary dinner. Chef Mario Bunda. No experimentation; the room is the experience.",
    "address": "Brsalje 3, 20000 Dubrovnik",
    "phone": "+385 20 442 526",
    "hours": "Dinner at sunset — Bokar and Lovrijenac frame the view",
    "maps": "https://www.google.com/maps/search/?api=1&query=Nautika+Dubrovnik"
  },
  {
    "id": "v05-kopun",
    "cat": "shop",
    "tier": "several",
    "priority": 5,
    "badge": "OLD DUBRO",
    "name": "Kopun",
    "short": "Kopun",
    "lat": 42.6407,
    "lng": 18.1102,
    "tags": [
      "Michelin Plate · Marin Držić's 16th-c. capon recipe revived",
      "EUR 45–70 pp",
      "Book 5–7 days for the square terrace beside St Ignatius",
      "Dinner — the square lights at dusk"
    ],
    "productTags": [
      "Heritage recipes",
      "Capon",
      "Šporki makaruli"
    ],
    "why": "Michelin Plate · Marin Držić's 16th-c. capon recipe revived. À commander : kopun (slow-roasted capon with oranges & honey, the Držić recipe) · šporki makaruli · arancini for dessert. The dishes you cannot order elsewhere. Beside the Boškovićeva (Jesuit) Stairs of Game of Thrones Walk-of-Shame fame.",
    "address": "Poljana Ruđera Boškovića 7, 20000 Dubrovnik",
    "phone": "+385 20 323 969",
    "hours": "Dinner — the square lights at dusk",
    "maps": "https://www.google.com/maps/search/?api=1&query=Kopun+Dubrovnik"
  },
  {
    "id": "v06-konoba-dubrava",
    "cat": "shop",
    "tier": "several",
    "priority": 6,
    "badge": "COUNTRYSI",
    "name": "Konoba Dubrava",
    "short": "Konoba Dubrava",
    "lat": 42.6532,
    "lng": 18.1297,
    "tags": [
      "The reference peka above the city — order 3 h ahead",
      "EUR 35–55 pp",
      "Call by 14:00 for an evening peka; 11:00 for lunch",
      "Lunch with the Old Town view; sunset from the terrace"
    ],
    "productTags": [
      "Peka",
      "Lamb",
      "Pre-order"
    ],
    "why": "The reference peka above the city — order 3 h ahead. À commander : lamb peka (3 h pre-order) · veal peka · octopus peka · house-made bread. The bell over embers, the right way: salt, rosemary, olive oil, time. Big-sky views down to Lokrum and across the islands.",
    "address": "Bosanka 5, 20207 Dubrovnik (10 min by car above Old Town)",
    "phone": "+385 20 411 030",
    "hours": "Lunch with the Old Town view; sunset from the terrace",
    "maps": "https://www.google.com/maps/search/?api=1&query=Konoba+Dubrava+Dubrovnik"
  },
  {
    "id": "v07-bota-are-mali-ston",
    "cat": "shop",
    "tier": "several",
    "priority": 7,
    "badge": "OYSTER BA",
    "name": "Bota Šare Mali Ston",
    "short": "Bota Šare Mali Ston",
    "lat": 42.8497,
    "lng": 17.7042,
    "tags": [
      "On-quay oyster bar; runs its own boat trip from the dock",
      "EUR 40–70 pp",
      "Walk-in possible at lunch; book dinner Apr–Sep",
      "Lunch, then a boat run across the bay to the oyster beds"
    ],
    "productTags": [
      "PDO oysters",
      "At-source",
      "Sushi line"
    ],
    "why": "On-quay oyster bar; runs its own boat trip from the dock. À commander : 12 Mali Ston oysters with lemon and Pošip · oyster tempura · sea-bass crudo · mussels na buzaru. The PDO Ostrea edulis at one hour and zero kilometres from the boat. Bring your own bottle of Korčula Pošip if you prefer; corkage is friendly.",
    "address": "Mali Ston bb, 20230 Ston (15th-c. salt warehouse)",
    "phone": "+385 20 754 482",
    "hours": "Lunch, then a boat run across the bay to the oyster beds",
    "maps": "https://www.google.com/maps/search/?api=1&query=Bota+Šare+Mali+Ston+Dubrovnik"
  },
  {
    "id": "v08-vila-koruna",
    "cat": "shop",
    "tier": "several",
    "priority": 8,
    "badge": "OYSTER BA",
    "name": "Vila Koruna",
    "short": "Vila Koruna",
    "lat": 42.8496,
    "lng": 17.7038,
    "tags": [
      "One of the original Mali Ston oyster houses — operating since 1973",
      "EUR 35–55 pp",
      "Walk-in fine outside high summer",
      "Lunch off-season; early dinner in summer"
    ],
    "productTags": [
      "Oyster house since 1973",
      "Rustic",
      "Rooms above"
    ],
    "why": "One of the original Mali Ston oyster houses — operating since 1973. À commander : oysters au naturel · mussels na buzaru · octopus salad · grilled scampi. Less polished than Bota Šare, more honest. Rooms above the restaurant if a Pelješac stay is the plan.",
    "address": "Mali Ston bb, 20230 Ston",
    "phone": "+385 20 754 999",
    "hours": "Lunch off-season; early dinner in summer",
    "maps": "https://www.google.com/maps/search/?api=1&query=Vila+Koruna+Dubrovnik"
  },
  {
    "id": "v09-konoba-konavoski-dvori",
    "cat": "shop",
    "tier": "several",
    "priority": 9,
    "badge": "RIVER KON",
    "name": "Konoba Konavoski Dvori",
    "short": "Konoba Konavoski Dvori",
    "lat": 42.5532,
    "lng": 18.3447,
    "tags": [
      "Restored old watermill on the Ljuta — Esculap group · in the Michelin Guide",
      "EUR 45–65 pp",
      "Book 1 week for weekend lunches",
      "Lunch — the cold river runs through the dining room"
    ],
    "productTags": [
      "Watermill",
      "Frog brodet",
      "Traditional dress"
    ],
    "why": "Restored old watermill on the Ljuta — Esculap group · in the Michelin Guide. À commander : žaba na brodet (frog brodet) · river trout · lamb peka · asparagus in season. Waitstaff in traditional Konavle dress. The frog brodet is one of the dishes you cannot get in the city. The river is the air conditioning.",
    "address": "Ljuta bb, 20210 Cavtat (Konavle, 35 min south of Dubrovnik)",
    "phone": "+385 20 791 039",
    "hours": "Lunch — the cold river runs through the dining room",
    "maps": "https://www.google.com/maps/search/?api=1&query=Konoba+Konavoski+Dvori+Dubrovnik"
  },
  {
    "id": "v10-konoba-atlantic-kitchen",
    "cat": "shop",
    "tier": "several",
    "priority": 10,
    "badge": "FAMILY KO",
    "name": "Konoba Atlantic Kitchen",
    "short": "Konoba Atlantic Kitchen",
    "lat": 42.6614,
    "lng": 18.0688,
    "tags": [
      "TripAdvisor Travellers' Choice — quiet local reputation since 2017",
      "EUR 30–45 pp",
      "Book the small terrace 3–5 days ahead",
      "Evening on the Lapad bay side"
    ],
    "productTags": [
      "Family-run",
      "Pasta",
      "Crew-friendly"
    ],
    "why": "TripAdvisor Travellers' Choice — quiet local reputation since 2017. À commander : house-made pappardelle with prawn-walnut sauce · cuttlefish-ink ravioli · grilled tuna. When the Old Town is full of cruise traffic, this is where the city's professionals eat. Smaller portions, sharper plating than the konobas inside the walls.",
    "address": "Kardinala Alojzija Stepinca 42, 20000 Dubrovnik",
    "phone": "+385 20 435 726",
    "hours": "Evening on the Lapad bay side",
    "maps": "https://www.google.com/maps/search/?api=1&query=Konoba+Atlantic+Kitchen+Dubrovnik"
  },
  {
    "id": "v11-lady-pi-pi",
    "cat": "shop",
    "tier": "several",
    "priority": 11,
    "badge": "GRILL",
    "name": "Lady Pi-Pi",
    "short": "Lady Pi-Pi",
    "lat": 42.6424,
    "lng": 18.1098,
    "tags": [
      "Cult Old Town grill — no reservations, queue from 17:00",
      "EUR 25–40 pp",
      "Walk-in only — queue starts forming at 17:00",
      "Early dinner before the queue, or 21:30+"
    ],
    "productTags": [
      "Charcoal grill",
      "Vine terrace",
      "Walk-in only"
    ],
    "why": "Cult Old Town grill — no reservations, queue from 17:00. À commander : mixed grill platter · grilled squid · house sausages · the lemon-and-oil potatoes. Open charcoal in the corner — you eat on a vine-covered terrace within the walls. Cash welcome; cards yes but slow.",
    "address": "Peline 1, 20000 Dubrovnik (climb past Sv. Spas)",
    "phone": "+385 20 321 154",
    "hours": "Early dinner before the queue, or 21:30+",
    "maps": "https://www.google.com/maps/search/?api=1&query=Lady+Pi-Pi+Dubrovnik"
  },
  {
    "id": "v12-buffet-kola",
    "cat": "shop",
    "tier": "several",
    "priority": 12,
    "badge": "SANDWICH",
    "name": "Buffet Škola",
    "short": "Buffet Škola",
    "lat": 42.6416,
    "lng": 18.1088,
    "tags": [
      "Tiny family sandwich shop · over 50 years on the same lane",
      "EUR 8–15 pp",
      "Walk-in only, three tables outside",
      "Crew breakfast 09:00–11:00; quick lunch any time"
    ],
    "productTags": [
      "50+ years",
      "Pršut",
      "Cash"
    ],
    "why": "Tiny family sandwich shop · over 50 years on the same lane. À commander : homemade-bread sandwich with Drniš pršut and Konavle cheese · domestic glass of red. Bread baked on site. Cash strongly preferred. The pršut comes off Drniš bone; the cheese is the Konavle hard-pressed sheep.",
    "address": "Antuninska 1, 20000 Dubrovnik",
    "phone": "+385 20 321 096",
    "hours": "Crew breakfast 09:00–11:00; quick lunch any time",
    "maps": "https://www.google.com/maps/search/?api=1&query=Buffet+Škola+Dubrovnik"
  },
  {
    "id": "v13-pizzeria-tabasco",
    "cat": "shop",
    "tier": "several",
    "priority": 13,
    "badge": "PIZZA",
    "name": "Pizzeria Tabasco",
    "short": "Pizzeria Tabasco",
    "lat": 42.6428,
    "lng": 18.1158,
    "tags": [
      "Long-running local pizzeria — the antidote to Stradun frozen pizza",
      "EUR 15–25 pp",
      "Walk-in usually fine; book the terrace in July–Aug",
      "Late dinner, terrace looks at the lit walls"
    ],
    "productTags": [
      "Decade-deep",
      "Walls view",
      "Late dinner"
    ],
    "why": "Long-running local pizzeria — the antidote to Stradun frozen pizza. À commander : Tabasco house pizza (salami, jalapeño, tabasco-honey drizzle) · seafood spaghetti · house tiramisu. Family-friendly, fast, honest. Where local crews eat after service. Pizza is wood-fired, dough is rested overnight.",
    "address": "Hvarska 48a, 20000 Dubrovnik",
    "phone": "+385 20 429 595",
    "hours": "Late dinner, terrace looks at the lit walls",
    "maps": "https://www.google.com/maps/search/?api=1&query=Pizzeria+Tabasco+Dubrovnik"
  },
  {
    "id": "v14-d-vino-wine-bar",
    "cat": "shop",
    "tier": "several",
    "priority": 14,
    "badge": "WINE BAR",
    "name": "D'vino Wine Bar",
    "short": "D'vino Wine Bar",
    "lat": 42.6416,
    "lng": 18.1089,
    "tags": [
      "The reference Croatian-wine bar of the Old Town · ten consecutive Michelin Guide editions",
      "EUR 25–55 pp (flights ~EUR 15–25)",
      "Book the cellar table; bar walk-in",
      "Aperitivo 18:00–20:00 before a Stara Loža dinner"
    ],
    "productTags": [
      "Croatian wines only",
      "60+ by glass",
      "Flights"
    ],
    "why": "The reference Croatian-wine bar of the Old Town · ten consecutive Michelin Guide editions. À commander : Plavac Mali flight (Grgić · Miloš · Madirazza · Saints Hills) · Pošip flight · Grk single-pour from Lumbarda. Map your Pelješac and Korčula wine list in one sitting. Owner Saša will pour you Grk you cannot find anywhere else in the Old Town.",
    "address": "Palmotićeva 4a, 20000 Dubrovnik",
    "phone": "+385 20 321 130",
    "hours": "Aperitivo 18:00–20:00 before a Stara Loža dinner",
    "maps": "https://www.google.com/maps/search/?api=1&query=D'vino+Wine+Bar+Dubrovnik"
  },
  {
    "id": "v15-glam-caf-beer-therapy",
    "cat": "shop",
    "tier": "several",
    "priority": 15,
    "badge": "BAR",
    "name": "Glam Café (Beer Therapy)",
    "short": "Glam Café (Beer Therapy)",
    "lat": 42.6416,
    "lng": 18.109,
    "tags": [
      "Cupboard-sized Croatian craft-beer + cocktail bar",
      "EUR 7–14 pp",
      "Walk-in only",
      "After-dinner, the lane stays lively to 01:00"
    ],
    "productTags": [
      "Craft beer",
      "Cocktails",
      "Late"
    ],
    "why": "Cupboard-sized Croatian craft-beer + cocktail bar. À commander : Garden Brewery IPA · Nova Runda lager · old fashioned with Maraschino float. The Croatian craft-beer fridge changes weekly. Useful when D'vino next door is full.",
    "address": "Palmotićeva 5, 20000 Dubrovnik",
    "phone": "+385 20 321 130",
    "hours": "After-dinner, the lane stays lively to 01:00",
    "maps": "https://www.google.com/maps/search/?api=1&query=Glam+Café+(Beer+Therapy)+Dubrovnik"
  },
  {
    "id": "v16-gru-market-tr-nica-gru",
    "cat": "market",
    "tier": "several",
    "priority": 16,
    "badge": "MARKET",
    "name": "Gruž Market (Tržnica Gruž)",
    "short": "Gruž Market (Tržnica Gru",
    "lat": 42.6612,
    "lng": 18.089,
    "tags": [
      "The provisioning market — closest fresh-fish market to ACI Marina",
      "Bring small bills",
      "—",
      "06:30–09:00 — boats land 06:30, fish gone by 10:00"
    ],
    "productTags": [
      "Provisioning",
      "Fish hall",
      "Cash"
    ],
    "why": "The provisioning market — closest fresh-fish market to ACI Marina. À commander : fish-hall: scorpionfish, sea bream, monkfish, the morning's octopus · outdoor: tomato, fig, mandolins of olive oil, herbs. Cash only on most stalls. The walk from Gruž ACI Marina is 8 minutes. Mondays are quiet; the rest of the week is the run.",
    "address": "Obala Stjepana Radića, 20000 Dubrovnik",
    "phone": "—",
    "hours": "06:30–09:00 — boats land 06:30, fish gone by 10:00",
    "maps": "https://www.google.com/maps/search/?api=1&query=Gruž+Market+(Tržnica+Gruž)+Dubrovnik"
  },
  {
    "id": "v17-grgi-vina-cellar-door",
    "cat": "shop",
    "tier": "several",
    "priority": 17,
    "badge": "WINERY",
    "name": "Grgić Vina (cellar door)",
    "short": "Grgić Vina (cellar door)",
    "lat": 42.9067,
    "lng": 17.4847,
    "tags": [
      "Founded 1996 by Miljenko \"Mike\" Grgich — Paris-1976 winemaker's homecoming",
      "Tasting EUR 25–45 pp",
      "Email at least 1 week ahead — small, by-appointment tastings",
      "Late-morning, then lunch at Bota Šare 50 min away"
    ],
    "productTags": [
      "Mike Grgich",
      "Plavac Mali",
      "Pošip"
    ],
    "why": "Founded 1996 by Miljenko \"Mike\" Grgich — Paris-1976 winemaker's homecoming. À commander : Plavac Mali Grgić (the multi-vintage flagship) · Pošip Grgić. Mike Grgich died in 2023; his daughter Violet and nephew Ivo Jeramaz run the estate. Two wines only, every year, no exceptions.",
    "address": "Trstenik 78, 20244 Trstenik",
    "phone": "+385 20 748 090",
    "hours": "Late-morning, then lunch at Bota Šare 50 min away",
    "maps": "https://www.google.com/maps/search/?api=1&query=Grgić+Vina+(cellar+door)+Dubrovnik"
  },
  {
    "id": "v18-milo-stagnum",
    "cat": "shop",
    "tier": "several",
    "priority": 18,
    "badge": "WINERY",
    "name": "Miloš Stagnum",
    "short": "Miloš Stagnum",
    "lat": 42.9105,
    "lng": 17.491,
    "tags": [
      "Hugh Johnson called Stagnum \"Croatia's first cult wine\" · wild yeast, 3 years in old oak",
      "Tasting EUR 35–60 pp",
      "Visit by appointment only — Frano Miloš personally pours",
      "Late afternoon — the 45° slopes catch the last light"
    ],
    "productTags": [
      "Cult wine",
      "Organic",
      "Old Slavonian oak"
    ],
    "why": "Hugh Johnson called Stagnum \"Croatia's first cult wine\" · wild yeast, 3 years in old oak. À commander : Stagnum (top cuvée, 3 y oak) · Plavac Mali base · Pošip Korčula. 15 ha across south-facing 150–250 m slopes. The 1993 Stagnum the wine that put Croatia on the international map after the war.",
    "address": "Ponikve 15, 20244 Ponikve (Pelješac)",
    "phone": "+385 20 742 393",
    "hours": "Late afternoon — the 45° slopes catch the last light",
    "maps": "https://www.google.com/maps/search/?api=1&query=Miloš+Stagnum+Dubrovnik"
  }
];
    const NEIGHBORHOODS = [
  {
    "id": "n-old-town",
    "name": "Old Town (Stari Grad)",
    "coords": [
      42.6414,
      18.1083
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Old+Town+Dubrovnik"
  },
  {
    "id": "n-ploce",
    "name": "Ploče",
    "coords": [
      42.6428,
      18.1158
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Ploce+Dubrovnik"
  },
  {
    "id": "n-pile",
    "name": "Pile",
    "coords": [
      42.6422,
      18.1056
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Pile+Gate+Dubrovnik"
  },
  {
    "id": "n-gruz",
    "name": "Gruž",
    "coords": [
      42.6612,
      18.089
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Gruz+Dubrovnik"
  },
  {
    "id": "n-lapad",
    "name": "Lapad",
    "coords": [
      42.662,
      18.0644
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Lapad+Dubrovnik"
  },
  {
    "id": "n-lokrum",
    "name": "Lokrum",
    "coords": [
      42.6275,
      18.1208
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Lokrum+island"
  },
  {
    "id": "n-peljesac",
    "name": "Pelješac peninsula",
    "coords": [
      42.9067,
      17.4847
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Peljesac+Dingac"
  },
  {
    "id": "n-konavle",
    "name": "Konavle",
    "coords": [
      42.5532,
      18.3447
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Konavle+Cavtat"
  },
  {
    "id": "n-elaphiti",
    "name": "Elaphiti islands",
    "coords": [
      42.6886,
      17.9425
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Elaphiti+Lopud"
  },
  {
    "id": "n-korcula",
    "name": "Korčula",
    "coords": [
      42.9233,
      16.8964
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Korcula+Smokvica"
  },
  {
    "id": "n-cavtat",
    "name": "Cavtat",
    "coords": [
      42.5806,
      18.2122
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Cavtat+harbor"
  }
];
    const WALKS = [
  {
    "id": "w-walls-loop",
    "name": "City Walls loop (Pile → Pile, ~2 km)",
    "coords": [
      42.6422,
      18.1075
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Walls+of+Dubrovnik+Pile+entry"
  },
  {
    "id": "w-srdj-cable",
    "name": "Mount Srđ cable car (412 m summit)",
    "coords": [
      42.6469,
      18.1119
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Mount+Srd+cable+car+Dubrovnik"
  },
  {
    "id": "w-lokrum-trail",
    "name": "Lokrum island circuit + Mrtvo More",
    "coords": [
      42.6275,
      18.1208
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Lokrum+Mrtvo+More"
  },
  {
    "id": "w-stradun",
    "name": "Stradun stroll Pile → Ploče (300 m)",
    "coords": [
      42.6414,
      18.1083
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Stradun+Dubrovnik"
  },
  {
    "id": "w-konavle-ljuta",
    "name": "Konavle Ljuta river walk + watermills",
    "coords": [
      42.5532,
      18.3447
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Ljuta+river+Konavle"
  },
  {
    "id": "w-ston-walls",
    "name": "Ston walls walk (5.5 km, longest in Europe)",
    "coords": [
      42.8364,
      17.69
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Ston+walls"
  },
  {
    "id": "w-cavtat-promenade",
    "name": "Cavtat harbour promenade + Račić mausoleum",
    "coords": [
      42.5806,
      18.2122
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Cavtat+Racic+mausoleum"
  }
];
    const WORK_SPOTS = [
  {
    "id": "ws-cogito-gruz",
    "name": "Cogito Coffee Gruž (work-friendly espresso)",
    "coords": [
      42.6608,
      18.0889
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Cogito+Coffee+Dubrovnik"
  },
  {
    "id": "ws-mara-cafe",
    "name": "Mara's Bar (Old Town, fast Wi-Fi)",
    "coords": [
      42.6418,
      18.1094
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Maras+Bar+Dubrovnik"
  },
  {
    "id": "ws-lapad-mlinar",
    "name": "Mlinar Lapad (quiet seat + Wi-Fi)",
    "coords": [
      42.6622,
      18.0688
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Mlinar+Lapad"
  },
  {
    "id": "ws-aci-marina",
    "name": "ACI Marina lounge (Gruž)",
    "coords": [
      42.6593,
      18.0856
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=ACI+Marina+Dubrovnik"
  },
  {
    "id": "ws-libertas-rixos",
    "name": "Rixos Libertas lobby (Pile)",
    "coords": [
      42.6422,
      18.1031
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Rixos+Libertas+Dubrovnik"
  }
];
    const LANDMARKS = [
  {
    "id": "l-stradun",
    "name": "Stradun (Onofrio's fountain)",
    "coords": [
      42.6414,
      18.1075
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Stradun+Onofrio+Fountain"
  },
  {
    "id": "l-rector-palace",
    "name": "Rector's Palace",
    "coords": [
      42.6408,
      18.111
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Rectors+Palace+Dubrovnik"
  },
  {
    "id": "l-sponza",
    "name": "Sponza Palace · Memorial of the Defenders",
    "coords": [
      42.6418,
      18.1108
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Sponza+Palace+Dubrovnik"
  },
  {
    "id": "l-lovrijenac",
    "name": "Lovrijenac fortress",
    "coords": [
      42.6415,
      18.1063
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Lovrijenac+Fortress"
  },
  {
    "id": "l-mincta",
    "name": "Minčeta tower",
    "coords": [
      42.6432,
      18.1077
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Minceta+Tower+Dubrovnik"
  },
  {
    "id": "l-st-blaise",
    "name": "St Blaise's Church",
    "coords": [
      42.6416,
      18.1107
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Church+of+Saint+Blaise+Dubrovnik"
  },
  {
    "id": "l-franciscan-pharmacy",
    "name": "Franciscan Monastery + 1317 Pharmacy",
    "coords": [
      42.6421,
      18.1075
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Franciscan+Monastery+Dubrovnik"
  },
  {
    "id": "l-cathedral",
    "name": "Cathedral of the Assumption",
    "coords": [
      42.6403,
      18.1108
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Dubrovnik+Cathedral"
  },
  {
    "id": "l-sokol-grad",
    "name": "Sokol Grad fortress",
    "coords": [
      42.5036,
      18.425
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Sokol+Grad+Konavle"
  },
  {
    "id": "l-ston-walls",
    "name": "Ston walls + salt pans",
    "coords": [
      42.8364,
      17.69
    ],
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Ston+walls"
  }
];
    return { VENUES, COLORS, CAT_LABELS, PRODUCT_COLORS, NEIGHBORHOODS, WALKS, WORK_SPOTS, LANDMARKS };
})();
