#!/usr/bin/env node
// tools/build.mjs — regenerate every derived file from data/articles.json.
// Run: node tools/build.mjs            (write)
//      node tools/build.mjs --check    (CI gate: exit 1 if anything would change)
// Regenerates: homepage card block, opted-in category pages, sitemap.xml, feed.xml,
//              data/draft-articles.json. Never touches hand-written prose.
import fs from "node:fs";
import {
  ROOT, ORIGIN, HOMEPAGE_LIMIT, FEED_LIMIT, p, read, exists,
  loadArticles, live, drafts, homepageCard, dispatchCard, replaceBetween,
  esc, log, warn,
} from "./lib.mjs";

const CHECK = process.argv.includes("--check");
let drift = 0;
const writeFile = (rel, next) => {
  const f = p(rel);
  const prev = exists(f) ? read(f) : null;
  if (prev === next) return;
  drift++;
  if (CHECK) { warn(`${rel} is out of date — run \`npm run build\` and commit.`); return; }
  fs.mkdirSync(require_dir(f), { recursive: true });
  fs.writeFileSync(f, next);
  log(`  wrote  ${rel}`);
};
const require_dir = (f) => f.slice(0, f.lastIndexOf("/"));

const { cats, articles } = loadArticles();
const published = live(articles);
const drafted = drafts(articles);

// 1) HOMEPAGE — fill the existing <!-- HOMEPAGE-ARTICLES:BEGIN/END --> block.
if (exists(p("index.html"))) {
  const cards = published.slice(0, HOMEPAGE_LIMIT).map((a) => "                " + homepageCard(a)).join("\n");
  const r = replaceBetween(read(p("index.html")), "HOMEPAGE-ARTICLES", cards);
  if (!r.found) warn("index.html has no HOMEPAGE-ARTICLES markers — homepage cards not regenerated.");
  else writeFile("index.html", r.html);
} else if (!CHECK) warn("index.html missing — recover it from production first.");

// 2) CATEGORY PAGES — any page containing <!-- CATEGORY-ARTICLES:BEGIN/END --> opts in.
//    The category is taken from the file's <body data-category="..."> or filename.
const CATEGORY_PAGES = {
  "the-method.html": "the-method",
  "shore-larder.html": "shore-larder",
  "littoral-heritage.html": "littoral-heritage",
  "the-evidence.html": "the-evidence",
  "the-bridge.html": "the-bridge",
};
for (const [file, cat] of Object.entries(CATEGORY_PAGES)) {
  if (!exists(p(file))) continue;
  const html = read(p(file));
  const inCat = published.filter((a) => a.category === cat);
  const cards = inCat.map((a) => "                " + dispatchCard(a)).join("\n\n");
  const r = replaceBetween(html, "CATEGORY-ARTICLES", cards);
  if (r.found) writeFile(file, r.html); // silent if no markers (opt-in)
}

// 3) SITEMAP — every live article + core pages (fixes robots.txt + SEO).
const CORE = ["", "the-method.html", "shore-larder.html", "littoral-heritage.html",
  "the-evidence.html", "the-bridge.html", "archive.html", "newsletter.html"];
const today = newestDate(published);
const urls = [
  ...CORE.map((u) => ({ loc: `${ORIGIN}/${u}`, lastmod: today })),
  ...published.map((a) => ({ loc: a.url, lastmod: a.date || today })),
];
const sitemap =
  `<?xml version="1.0" encoding="UTF-8"?>\n` +
  `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n` +
  urls.map((u) => `  <url><loc>${esc(u.loc)}</loc>${u.lastmod ? `<lastmod>${u.lastmod}</lastmod>` : ""}</url>`).join("\n") +
  `\n</urlset>\n`;
writeFile("sitemap.xml", sitemap);

// 4) RSS FEED — latest FEED_LIMIT live articles.
const items = published.slice(0, FEED_LIMIT).map((a) =>
  `    <item>\n` +
  `      <title>${esc(a.title)}</title>\n` +
  `      <link>${a.url}</link>\n` +
  `      <guid isPermaLink="true">${a.url}</guid>\n` +
  (a.date ? `      <pubDate>${rfc822(a.date)}</pubDate>\n` : "") +
  (a.category_label ? `      <category>${esc(a.category_label)}</category>\n` : "") +
  (a.lede ? `      <description>${esc(a.lede)}</description>\n` : "") +
  `    </item>`
).join("\n");
const feed =
  `<?xml version="1.0" encoding="UTF-8"?>\n` +
  `<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">\n` +
  `  <channel>\n` +
  `    <title>Littoralicious</title>\n` +
  `    <link>${ORIGIN}/</link>\n` +
  `    <atom:link href="${ORIGIN}/feed.xml" rel="self" type="application/rss+xml"/>\n` +
  `    <description>Modern science and regional littoral cooking for yacht chefs.</description>\n` +
  `    <language>en</language>\n` +
  items + "\n" +
  `  </channel>\n</rss>\n`;
writeFile("feed.xml", feed);

// 5) DRAFT INDEX — replaces scripts/build-draft-articles-json.py output.
const draftList = drafted.map((a) => ({
  slug: a.slug, title: a.title, category: a.category, category_label: a.category_label,
  read_time: a.read_time || 0, file: a.file, lede: a.lede, added: a.date || "",
})).sort((x, y) => String(y.added).localeCompare(String(x.added)) || x.slug.localeCompare(y.slug));
const draftJson = stripTimestamp(JSON.stringify({
  _comment: "Auto-generated by tools/build.mjs. Do not hand-edit. Run `npm run build`.",
  _generated_at: "STAMP",
  drafts: draftList,
}, null, 2)) + "\n";
// In --check mode compare without the timestamp line; on write, stamp it.
if (CHECK) {
  const cur = exists(p("data/draft-articles.json")) ? stripTimestamp(read(p("data/draft-articles.json"))) : "";
  if (cur.trim() !== draftJson.trim()) { drift++; warn("data/draft-articles.json out of date."); }
} else {
  writeFile("data/draft-articles.json", draftJson.replace('"STAMP"', `"${new Date().toISOString().replace(/\.\d+Z$/, "Z")}"`));
}

// ---- summary ----------------------------------------------------------------
log("");
log(`  ${published.length} live · ${drafted.length} draft · sitemap ${urls.length} urls · feed ${Math.min(published.length, FEED_LIMIT)} items`);
if (CHECK) {
  if (drift) { console.error(`\n✗ ${drift} file(s) out of date. Run \`npm run build\`.`); process.exit(1); }
  log("✓ everything up to date.");
} else log(drift ? `✓ build complete (${drift} file(s) updated).` : "✓ build complete (no changes).");

// ---- helpers ----------------------------------------------------------------
function newestDate(list) { return list.reduce((m, a) => (a.date && a.date > m ? a.date : m), ""); }
function stripTimestamp(s) { return s.replace(/"_generated_at":\s*"[^"]*"/, '"_generated_at": "STAMP"'); }
function rfc822(d) {
  const dt = new Date(d + "T12:00:00Z");
  return isNaN(dt) ? "" : dt.toUTCString();
}
